// French Quiz Data
const frenchQuizData = {
    A1: [
        { word: "Maison", options: ["House", "Tree", "Car", "Dog"], correct: "House" },
    { word: "Chat", options: ["Cat", "Mouse", "Bird", "Horse"], correct: "Cat" },
    { word: "Chien", options: ["Dog", "Cat", "Fish", "Rabbit"], correct: "Dog" },
    { word: "Voiture", options: ["Bike", "Car", "Bus", "Train"], correct: "Car" },
    { word: "Arbre", options: ["Tree", "Flower", "Bush", "Grass"], correct: "Tree" },
    { word: "Livre", options: ["Pen", "Book", "Table", "Chair"], correct: "Book" },
    { word: "École", options: ["School", "Restaurant", "Park", "Hospital"], correct: "School" },
    { word: "Fleur", options: ["Flower", "Tree", "Plant", "Bush"], correct: "Flower" },
    { word: "Fenêtre", options: ["Window", "Door", "Wall", "Roof"], correct: "Window" },
    { word: "Café", options: ["Tea", "Coffee", "Milk", "Juice"], correct: "Coffee" },
    { word: "Pomme", options: ["Apple", "Banana", "Orange", "Grape"], correct: "Apple" },
    { word: "Pain", options: ["Bread", "Butter", "Cheese", "Jam"], correct: "Bread" },
    { word: "Salade", options: ["Soup", "Salad", "Sandwich", "Fruit"], correct: "Salad" },
    { word: "Chocolat", options: ["Chocolate", "Candy", "Cake", "Ice cream"], correct: "Chocolate" },
    { word: "Voisin", options: ["Neighbor", "Friend", "Family", "Stranger"], correct: "Neighbor" },
    { word: "Chambre", options: ["Room", "Kitchen", "Living room", "Bathroom"], correct: "Room" },
    { word: "Soleil", options: ["Moon", "Sun", "Star", "Cloud"], correct: "Sun" },
    { word: "Lune", options: ["Star", "Cloud", "Sun", "Moon"], correct: "Moon" },
    { word: "Plage", options: ["Mountain", "Lake", "Beach", "Forest"], correct: "Beach" },
    { word: "Mer", options: ["Lake", "Ocean", "River", "Sea"], correct: "Sea" },
    { word: "Montagne", options: ["Hill", "Mountain", "Valley", "Desert"], correct: "Mountain" },
    { word: "Vélo", options: ["Car", "Bicycle", "Bus", "Truck"], correct: "Bicycle" },
    { word: "Chapeau", options: ["Shirt", "Shoes", "Hat", "Pants"], correct: "Hat" },
    { word: "Pantalon", options: ["Shirt", "Shorts", "Trousers", "Jacket"], correct: "Trousers" },
    { word: "Jupe", options: ["Shirt", "Pants", "Skirt", "Coat"], correct: "Skirt" },
    { word: "Chaussures", options: ["Gloves", "Shoes", "Socks", "Hats"], correct: "Shoes" },
    { word: "Pull", options: ["Sweater", "Shirt", "T-shirt", "Jacket"], correct: "Sweater" },
    { word: "Manteau", options: ["Coat", "Jacket", "Sweater", "Shirt"], correct: "Coat" },
    { word: "Hiver", options: ["Winter", "Spring", "Autumn", "Summer"], correct: "Winter" },
    { word: "Été", options: ["Summer", "Winter", "Spring", "Autumn"], correct: "Summer" },
    { word: "Automne", options: ["Spring", "Summer", "Autumn", "Winter"], correct: "Autumn" },
    { word: "Printemps", options: ["Spring", "Summer", "Autumn", "Winter"], correct: "Spring" },
    { word: "Jour", options: ["Night", "Day", "Morning", "Evening"], correct: "Day" },
    { word: "Nuit", options: ["Morning", "Night", "Afternoon", "Evening"], correct: "Night" },
    { word: "Matin", options: ["Morning", "Afternoon", "Night", "Evening"], correct: "Morning" },
    { word: "Soir", options: ["Evening", "Morning", "Afternoon", "Night"], correct: "Evening" },
    { word: "Heure", options: ["Minute", "Hour", "Day", "Week"], correct: "Hour" },
    { word: "Semaine", options: ["Week", "Month", "Year", "Day"], correct: "Week" },
    { word: "Mois", options: ["Month", "Year", "Day", "Week"], correct: "Month" },
    { word: "Année", options: ["Day", "Year", "Month", "Week"], correct: "Year" },
    { word: "Numéro", options: ["Letter", "Number", "Word", "Sentence"], correct: "Number" },
    { word: "Période", options: ["Period", "Point", "Comma", "Exclamation"], correct: "Period" },
    { word: "Téléphone", options: ["Computer", "Phone", "Tablet", "TV"], correct: "Phone" },
    { word: "Tablette", options: ["Book", "Pen", "Tablet", "Phone"], correct: "Tablet" },
    { word: "Ordinateur", options: ["Phone", "Tablet", "Laptop", "Computer"], correct: "Computer" },
    { word: "Télévision", options: ["Radio", "Computer", "Phone", "TV"], correct: "TV" },
    { word: "Chanson", options: ["Song", "Dance", "Poem", "Story"], correct: "Song" },
    { word: "Film", options: ["Show", "Movie", "Series", "Play"], correct: "Movie" },
    { word: "Musique", options: ["Dance", "Music", "Theatre", "Poetry"], correct: "Music" },
    { word: "Livre", options: ["Magazine", "Book", "Newspaper", "Guide"], correct: "Book" },
    { word: "Magasin", options: ["Store", "School", "Market", "Library"], correct: "Store" },
    { word: "Supermarché", options: ["Supermarket", "Restaurant", "Bank", "Post office"], correct: "Supermarket" },
    { word: "Poste", options: ["Post office", "Bank", "Store", "School"], correct: "Post office" },
    { word: "Banque", options: ["School", "Restaurant", "Bank", "Shop"], correct: "Bank" },
    { word: "Bureau", options: ["Office", "Classroom", "Library", "Restaurant"], correct: "Office" },
    { word: "Église", options: ["Church", "Temple", "Mosque", "Synagogue"], correct: "Church" },
    { word: "Mosquée", options: ["Church", "Synagogue", "Temple", "Mosque"], correct: "Mosque" },
    { word: "Temple", options: ["Church", "Temple", "Mosque", "Synagogue"], correct: "Temple" },
    { word: "Hôpital", options: ["Hospital", "Clinic", "School", "Store"], correct: "Hospital" },
    { word: "Médecin", options: ["Teacher", "Doctor", "Nurse", "Patient"], correct: "Doctor" },
    { word: "Infirmière", options: ["Nurse", "Patient", "Doctor", "Teacher"], correct: "Nurse" },
    { word: "Patient", options: ["Doctor", "Nurse", "Patient", "Teacher"], correct: "Patient" },
    { word: "Femme", options: ["Woman", "Man", "Child", "Baby"], correct: "Woman" },
    { word: "Homme", options: ["Man", "Woman", "Child", "Baby"], correct: "Man" },
    { word: "Enfant", options: ["Woman", "Man", "Child", "Baby"], correct: "Child" },
    { word: "Bébé", options: ["Baby", "Child", "Man", "Woman"], correct: "Baby" },
    { word: "Amie", options: ["Friend", "Family", "Neighbor", "Stranger"], correct: "Friend" },
    { word: "Famille", options: ["Family", "Neighbor", "Friend", "Stranger"], correct: "Family" },
    { word: "Voiture", options: ["Car", "Bus", "Truck", "Bicycle"], correct: "Car" },
    { word: "Voleur", options: ["Thief", "Police", "Judge", "Teacher"], correct: "Thief" },
    { word: "Police", options: ["Police", "Firefighter", "Soldier", "Teacher"], correct: "Police" },
    { word: "Soldat", options: ["Soldier", "Policeman", "Firefighter", "Teacher"], correct: "Soldier" },
    { word: "Pompier", options: ["Firefighter", "Policeman", "Soldier", "Teacher"], correct: "Firefighter" },
    { word: "Bureau", options: ["Desk", "Library", "Office", "Classroom"], correct: "Office" },
    { word: "Clé", options: ["Key", "Lock", "Door", "Window"], correct: "Key" },
    { word: "Étoile", options: ["Star", "Moon", "Planet", "Sun"], correct: "Star" },
    { word: "Chocolat", options: ["Chocolate", "Candy", "Cake", "Ice cream"], correct: "Chocolate" },
    { word: "Ciel", options: ["Sky", "Earth", "Ocean", "Cloud"], correct: "Sky" },
    { word: "Oiseau", options: ["Bird", "Fish", "Animal", "Insect"], correct: "Bird" },
    { word: "Voiture", options: ["Car", "Bus", "Bicycle", "Truck"], correct: "Car" },
    { word: "Aéroport", options: ["Airport", "Train station", "Bus stop", "Port"], correct: "Airport" },
    { word: "Bateau", options: ["Boat", "Car", "Train", "Bicycle"], correct: "Boat" },
    { word: "Réseau", options: ["Network", "Phone", "Television", "Computer"], correct: "Network" },
    { word: "Roue", options: ["Wheel", "Pedal", "Handlebar", "Seat"], correct: "Wheel" },
    { word: "Cadeau", options: ["Gift", "Money", "Food", "Clothes"], correct: "Gift" },
    { word: "Chiffre", options: ["Number", "Letter", "Word", "Shape"], correct: "Number" },
    { word: "Élève", options: ["Student", "Teacher", "Principal", "Parent"], correct: "Student" },
    { word: "Souris", options: ["Mouse", "Rat", "Cat", "Dog"], correct: "Mouse" },
    { word: "Tracteur", options: ["Tractor", "Car", "Truck", "Motorcycle"], correct: "Tractor" },
    { word: "Poisson", options: ["Fish", "Shark", "Whale", "Dolphin"], correct: "Fish" },
    { word: "Fenêtre", options: ["Window", "Door", "Wall", "Roof"], correct: "Window" },
    { word: "Papi", options: ["Grandfather", "Father", "Brother", "Uncle"], correct: "Grandfather" },
    { word: "Maman", options: ["Mother", "Father", "Sister", "Brother"], correct: "Mother" },
    { word: "Papa", options: ["Father", "Grandfather", "Uncle", "Brother"], correct: "Father" },
    { word: "Tante", options: ["Aunt", "Uncle", "Mother", "Sister"], correct: "Aunt" },
    { word: "Frère", options: ["Brother", "Sister", "Father", "Uncle"], correct: "Brother" },
    { word: "Sœur", options: ["Sister", "Brother", "Aunt", "Mother"], correct: "Sister" },
    { word: "Fille", options: ["Girl", "Boy", "Child", "Woman"], correct: "Girl" },
    { word: "Garçon", options: ["Boy", "Girl", "Child", "Man"], correct: "Boy" },
    { word: "Mignon", options: ["Cute", "Big", "Old", "Sad"], correct: "Cute" },
    { word: "Grand", options: ["Big", "Small", "Fast", "Slow"], correct: "Big" },
    { word: "Petit", options: ["Small", "Big", "Slow", "Fast"], correct: "Small" },
    { word: "Vieux", options: ["Old", "New", "Young", "Fast"], correct: "Old" },
    { word: "Jeune", options: ["Young", "Old", "Middle-aged", "Big"], correct: "Young" },
    { word: "Mauvais", options: ["Bad", "Good", "Better", "Worst"], correct: "Bad" },
    { word: "Bon", options: ["Good", "Bad", "Better", "Best"], correct: "Good" },
    { word: "Meilleur", options: ["Better", "Good", "Best", "Worst"], correct: "Better" },
    { word: "Meilleur", options: ["Best", "Good", "Better", "Worst"], correct: "Best" },
    { word: "Écouter", options: ["Listen", "Speak", "Read", "Write"], correct: "Listen" },
    { word: "Regarder", options: ["Look", "Listen", "Speak", "Read"], correct: "Look" },
    { word: "Manger", options: ["Eat", "Drink", "Sleep", "Run"], correct: "Eat" },
    { word: "Boire", options: ["Drink", "Eat", "Sleep", "Run"], correct: "Drink" },
    { word: "Dormir", options: ["Sleep", "Run", "Play", "Walk"], correct: "Sleep" },
    { word: "Jouer", options: ["Play", "Work", "Sleep", "Eat"], correct: "Play" },
    { word: "Marcher", options: ["Walk", "Run", "Sit", "Jump"], correct: "Walk" },
    { word: "Courir", options: ["Run", "Walk", "Jump", "Sit"], correct: "Run" },
    { word: "Sauter", options: ["Jump", "Sit", "Run", "Walk"], correct: "Jump" },
    { word: "Écrire", options: ["Write", "Read", "Listen", "Speak"], correct: "Write" },
    { word: "Lire", options: ["Read", "Write", "Speak", "Listen"], correct: "Read" },
    { word: "Parler", options: ["Speak", "Listen", "Read", "Write"], correct: "Speak" },
    { word: "Écrire", options: ["Write", "Speak", "Read", "Listen"], correct: "Write" },
    { word: "Lire", options: ["Read", "Write", "Listen", "Speak"], correct: "Read" },
    { word: "Vendre", options: ["Sell", "Buy", "Exchange", "Donate"], correct: "Sell" },
    { word: "Acheter", options: ["Buy", "Sell", "Give", "Take"], correct: "Buy" },
    { word: "Donner", options: ["Give", "Take", "Buy", "Sell"], correct: "Give" },
    { word: "Prendre", options: ["Take", "Give", "Buy", "Sell"], correct: "Take" },
    { word: "Mettre", options: ["Put", "Take", "Give", "Sell"], correct: "Put" },
    { word: "Journée", options: ["Day", "Night", "Month", "Year"], correct: "Day" },
    { word: "Anniversaire", options: ["Birthday", "Holiday", "Wedding", "Celebration"], correct: "Birthday" },
    { word: "Vacances", options: ["Vacation", "Work", "Study", "Play"], correct: "Vacation" },
    { word: "Fête", options: ["Party", "Work", "Meeting", "Class"], correct: "Party" },
    { word: "Mariage", options: ["Marriage", "Birth", "Death", "Anniversary"], correct: "Marriage" },
    { word: "Naissance", options: ["Birth", "Death", "Anniversary", "Marriage"], correct: "Birth" },
    { word: "Hôpital", options: ["Hospital", "School", "Restaurant", "Market"], correct: "Hospital" },
    { word: "Médecin", options: ["Doctor", "Nurse", "Teacher", "Driver"], correct: "Doctor" },
    { word: "Malade", options: ["Sick", "Healthy", "Tired", "Happy"], correct: "Sick" },
    { word: "Santé", options: ["Health", "Wealth", "Happiness", "Energy"], correct: "Health" },
    { word: "Urgence", options: ["Emergency", "Help", "Hospital", "Doctor"], correct: "Emergency" },
    { word: "Saison", options: ["Season", "Month", "Year", "Day"], correct: "Season" },
    { word: "Froid", options: ["Cold", "Hot", "Warm", "Cool"], correct: "Cold" },
    { word: "Chaud", options: ["Hot", "Cold", "Warm", "Cool"], correct: "Hot" },
    { word: "Pluie", options: ["Rain", "Sun", "Wind", "Snow"], correct: "Rain" },
    { word: "Neige", options: ["Snow", "Rain", "Wind", "Fog"], correct: "Snow" },
    { word: "Nuage", options: ["Cloud", "Sun", "Moon", "Star"], correct: "Cloud" },
    { word: "Vente", options: ["Wind", "Rain", "Storm", "Cloud"], correct: "Wind" },
    { word: "Temps", options: ["Weather", "Time", "Season", "Day"], correct: "Weather" },
    { word: "Bruit", options: ["Noise", "Silence", "Sound", "Word"], correct: "Noise" },
    { word: "Silence", options: ["Silence", "Noise", "Sound", "Word"], correct: "Silence" },
    { word: "Soleil", options: ["Sun", "Moon", "Star", "Planet"], correct: "Sun" },
    { word: "Lune", options: ["Moon", "Star", "Sun", "Planet"], correct: "Moon" },
    { word: "Mois", options: ["Month", "Year", "Week", "Day"], correct: "Month" },
    { word: "Année", options: ["Year", "Month", "Day", "Week"], correct: "Year" }
    ],
    A2: [
        { word: "Bureau", options: ["Office", "Room", "School", "Home"], correct: "Office" },
    { word: "Voyage", options: ["Trip", "Car", "Journey", "Flight"], correct: "Trip" },
    { word: "Gâteau", options: ["Cake", "Bread", "Pasta", "Fruit"], correct: "Cake" },
    { word: "Rêver", options: ["Dream", "Think", "Sleep", "Wake"], correct: "Dream" },
    { word: "Louer", options: ["Rent", "Buy", "Sell", "Borrow"], correct: "Rent" },
    { word: "Arriver", options: ["Arrive", "Leave", "Go", "Stay"], correct: "Arrive" },
    { word: "Vêtements", options: ["Clothes", "Shoes", "Accessories", "Hats"], correct: "Clothes" },
    { word: "Plage", options: ["Beach", "Mountain", "Lake", "Forest"], correct: "Beach" },
    { word: "Cuisine", options: ["Kitchen", "Bedroom", "Living room", "Bathroom"], correct: "Kitchen" },
    { word: "Légumes", options: ["Vegetables", "Fruits", "Meat", "Spices"], correct: "Vegetables" },
    { word: "Français", options: ["French", "English", "German", "Spanish"], correct: "French" },
    { word: "Temps", options: ["Weather", "Time", "Year", "Day"], correct: "Time" },
    { word: "Maison", options: ["House", "Apartment", "Building", "Room"], correct: "House" },
    { word: "Musique", options: ["Music", "Song", "Movie", "Dance"], correct: "Music" },
    { word: "Voiture", options: ["Car", "Bus", "Train", "Bike"], correct: "Car" },
    { word: "Chambre", options: ["Room", "Living room", "Kitchen", "Bathroom"], correct: "Room" },
    { word: "Bateau", options: ["Boat", "Car", "Train", "Plane"], correct: "Boat" },
    { word: "Hôpital", options: ["Hospital", "School", "Shop", "Restaurant"], correct: "Hospital" },
    { word: "Répondre", options: ["Answer", "Ask", "Question", "Talk"], correct: "Answer" },
    { word: "Demander", options: ["Ask", "Answer", "Give", "Tell"], correct: "Ask" },
    { word: "Café", options: ["Coffee", "Tea", "Juice", "Water"], correct: "Coffee" },
    { word: "Thé", options: ["Tea", "Coffee", "Water", "Juice"], correct: "Tea" },
    { word: "Trop", options: ["Too much", "Enough", "Not enough", "Very"], correct: "Too much" },
    { word: "Parler", options: ["Speak", "Listen", "Read", "Write"], correct: "Speak" },
    { word: "Lire", options: ["Read", "Write", "Speak", "Listen"], correct: "Read" },
    { word: "Écrire", options: ["Write", "Read", "Listen", "Speak"], correct: "Write" },
    { word: "Attendre", options: ["Wait", "Go", "Run", "Stop"], correct: "Wait" },
    { word: "Aider", options: ["Help", "Talk", "Call", "Give"], correct: "Help" },
    { word: "Jouer", options: ["Play", "Watch", "Sing", "Dance"], correct: "Play" },
    { word: "Faire", options: ["Do", "Make", "Watch", "Read"], correct: "Do" },
    { word: "Continuer", options: ["Continue", "Stop", "Start", "Pause"], correct: "Continue" },
    { word: "Commencer", options: ["Start", "Finish", "Continue", "Stop"], correct: "Start" },
    { word: "Finir", options: ["Finish", "Start", "Continue", "Pause"], correct: "Finish" },
    { word: "Parler", options: ["Speak", "Listen", "Read", "Write"], correct: "Speak" },
    { word: "Rire", options: ["Laugh", "Cry", "Talk", "Smile"], correct: "Laugh" },
    { word: "Manger", options: ["Eat", "Drink", "Sleep", "Run"], correct: "Eat" },
    { word: "Boire", options: ["Drink", "Eat", "Sleep", "Run"], correct: "Drink" },
    { word: "Dîner", options: ["Dinner", "Breakfast", "Lunch", "Snack"], correct: "Dinner" },
    { word: "Déjeuner", options: ["Lunch", "Dinner", "Breakfast", "Snack"], correct: "Lunch" },
    { word: "Petit-déjeuner", options: ["Breakfast", "Lunch", "Dinner", "Snack"], correct: "Breakfast" },
    { word: "Fort", options: ["Strong", "Weak", "Slow", "Fast"], correct: "Strong" },
    { word: "Faible", options: ["Weak", "Strong", "Slow", "Fast"], correct: "Weak" },
    { word: "Lent", options: ["Slow", "Fast", "Strong", "Weak"], correct: "Slow" },
    { word: "Rapide", options: ["Fast", "Slow", "Weak", "Strong"], correct: "Fast" },
    { word: "Chaud", options: ["Hot", "Cold", "Warm", "Cool"], correct: "Hot" },
    { word: "Froid", options: ["Cold", "Hot", "Warm", "Cool"], correct: "Cold" },
    { word: "Gagner", options: ["Win", "Lose", "Play", "Watch"], correct: "Win" },
    { word: "Perdre", options: ["Lose", "Win", "Play", "Watch"], correct: "Lose" },
    { word: "Connaître", options: ["Know", "Meet", "See", "Talk"], correct: "Know" },
    { word: "Rencontrer", options: ["Meet", "Know", "Talk", "Listen"], correct: "Meet" },
    { word: "Visiter", options: ["Visit", "See", "Meet", "Talk"], correct: "Visit" },
    { word: "Marcher", options: ["Walk", "Run", "Sit", "Stand"], correct: "Walk" },
    { word: "Courir", options: ["Run", "Walk", "Sit", "Stand"], correct: "Run" },
    { word: "Arrêter", options: ["Stop", "Go", "Run", "Walk"], correct: "Stop" },
    { word: "Vendre", options: ["Sell", "Buy", "Give", "Take"], correct: "Sell" },
    { word: "Acheter", options: ["Buy", "Sell", "Give", "Take"], correct: "Buy" },
    { word: "Apprendre", options: ["Learn", "Teach", "Help", "Give"], correct: "Learn" },
    { word: "Enseigner", options: ["Teach", "Learn", "Give", "Help"], correct: "Teach" },
    { word: "Regarder", options: ["Look", "See", "Watch", "Read"], correct: "Watch" },
    { word: "Voir", options: ["See", "Look", "Watch", "Read"], correct: "See" },
    { word: "Écouter", options: ["Listen", "Speak", "Read", "Write"], correct: "Listen" },
    { word: "Entendre", options: ["Hear", "Listen", "Talk", "Speak"], correct: "Hear" },
    { word: "Aimer", options: ["Like", "Love", "Hate", "Dislike"], correct: "Like" },
    { word: "Détester", options: ["Hate", "Like", "Love", "Dislike"], correct: "Hate" },
    { word: "Regarder", options: ["Look", "See", "Watch", "Read"], correct: "Look" },
    { word: "Attendre", options: ["Wait", "Go", "Run", "Stop"], correct: "Wait" },
    { word: "Tant", options: ["So much", "So little", "Not much", "Not little"], correct: "So much" },
    { word: "Savoir", options: ["Know", "Learn", "Understand", "Talk"], correct: "Know" },
    { word: "Comprendre", options: ["Understand", "Talk", "Learn", "Read"], correct: "Understand" },
    { word: "Voler", options: ["Steal", "Fly", "Run", "Walk"], correct: "Steal" },
    { word: "Promettre", options: ["Promise", "Break", "Ask", "Tell"], correct: "Promise" },
    { word: "Crier", options: ["Shout", "Speak", "Talk", "Whisper"], correct: "Shout" },
    { word: "Manger", options: ["Eat", "Drink", "Sleep", "Run"], correct: "Eat" },
    { word: "Plier", options: ["Fold", "Open", "Close", "Tie"], correct: "Fold" },{ word: "Amis", options: ["Friends", "Enemies", "Teachers", "Parents"], correct: "Friends" },
    { word: "Chocolat", options: ["Chocolate", "Cake", "Candy", "Fruit"], correct: "Chocolate" },
    { word: "Soleil", options: ["Sun", "Moon", "Cloud", "Star"], correct: "Sun" },
    { word: "Vêtements", options: ["Clothes", "Shoes", "Hats", "Accessories"], correct: "Clothes" },
    { word: "Bureau", options: ["Office", "Room", "Kitchen", "Bedroom"], correct: "Office" },
    { word: "Fleur", options: ["Flower", "Tree", "Bush", "Plant"], correct: "Flower" },
    { word: "Chanson", options: ["Song", "Movie", "Story", "Game"], correct: "Song" },
    { word: "Maison", options: ["House", "Apartment", "Building", "Store"], correct: "House" },
    { word: "Rivière", options: ["River", "Lake", "Ocean", "Mountain"], correct: "River" },
    { word: "Forêt", options: ["Forest", "Desert", "Island", "Ocean"], correct: "Forest" },
    { word: "Chien", options: ["Dog", "Cat", "Horse", "Rabbit"], correct: "Dog" },
    { word: "Chat", options: ["Cat", "Dog", "Fish", "Bird"], correct: "Cat" },
    { word: "Table", options: ["Table", "Chair", "Sofa", "Bed"], correct: "Table" },
    { word: "Voiture", options: ["Car", "Bike", "Train", "Plane"], correct: "Car" },
    { word: "Vélo", options: ["Bike", "Car", "Bus", "Train"], correct: "Bike" },
    { word: "Eau", options: ["Water", "Juice", "Tea", "Milk"], correct: "Water" },
    { word: "Pain", options: ["Bread", "Rice", "Pasta", "Pizza"], correct: "Bread" },
    { word: "Fromage", options: ["Cheese", "Bread", "Rice", "Fruit"], correct: "Cheese" },
    { word: "Pomme", options: ["Apple", "Banana", "Orange", "Grape"], correct: "Apple" },
    { word: "Banane", options: ["Banana", "Apple", "Orange", "Pear"], correct: "Banana" },
    { word: "Orange", options: ["Orange", "Apple", "Banana", "Grapes"], correct: "Orange" },
    { word: "Lait", options: ["Milk", "Water", "Juice", "Tea"], correct: "Milk" },
    { word: "École", options: ["School", "University", "Library", "Cafe"], correct: "School" },
    { word: "Université", options: ["University", "School", "College", "Library"], correct: "University" },
    { word: "Livre", options: ["Book", "Pen", "Notebook", "Bag"], correct: "Book" },
    { word: "Cahier", options: ["Notebook", "Pen", "Book", "Bag"], correct: "Notebook" },
    { word: "Stylo", options: ["Pen", "Pencil", "Book", "Paper"], correct: "Pen" },
    { word: "Crayon", options: ["Pencil", "Pen", "Eraser", "Book"], correct: "Pencil" },
    { word: "Portefeuille", options: ["Wallet", "Bag", "Phone", "Watch"], correct: "Wallet" },
    { word: "Téléphone", options: ["Phone", "Computer", "Tablet", "Watch"], correct: "Phone" },
    { word: "Montre", options: ["Watch", "Ring", "Bracelet", "Earrings"], correct: "Watch" },
    { word: "Sac", options: ["Bag", "Suitcase", "Backpack", "Box"], correct: "Bag" },
    { word: "Chapeau", options: ["Hat", "Scarf", "Gloves", "Shirt"], correct: "Hat" },
    { word: "Manteau", options: ["Coat", "Shirt", "Pants", "Sweater"], correct: "Coat" },
    { word: "Jupe", options: ["Skirt", "Pants", "Shirt", "Dress"], correct: "Skirt" },
    { word: "Robe", options: ["Dress", "Shirt", "Skirt", "Pants"], correct: "Dress" },
    { word: "Pantalon", options: ["Pants", "Shirt", "Jacket", "Sweater"], correct: "Pants" },
    { word: "T-shirt", options: ["T-shirt", "Shirt", "Sweater", "Jacket"], correct: "T-shirt" },
    { word: "Chaussures", options: ["Shoes", "Socks", "Hat", "Gloves"], correct: "Shoes" },
    { word: "Chaussettes", options: ["Socks", "Shoes", "Hat", "Scarf"], correct: "Socks" },
    { word: "Gloves", options: ["Gants", "Écharpe", "Chapeau", "Chaussettes"], correct: "Gants" },
    { word: "Écharpe", options: ["Scarf", "Gloves", "Hat", "Jacket"], correct: "Scarf" },
    { word: "Voix", options: ["Voice", "Sound", "Face", "Ear"], correct: "Voice" },
    { word: "Oreilles", options: ["Ears", "Eyes", "Mouth", "Nose"], correct: "Ears" },
    { word: "Yeux", options: ["Eyes", "Ears", "Mouth", "Nose"], correct: "Eyes" },
    { word: "Bouche", options: ["Mouth", "Nose", "Eyes", "Ears"], correct: "Mouth" },
    { word: "Nez", options: ["Nose", "Mouth", "Eyes", "Ears"], correct: "Nose" },
    { word: "Visage", options: ["Face", "Head", "Ear", "Eye"], correct: "Face" },
    { word: "Cheveux", options: ["Hair", "Eyes", "Nose", "Mouth"], correct: "Hair" },
    { word: "Dent", options: ["Tooth", "Eye", "Nose", "Mouth"], correct: "Tooth" },
    { word: "Bouche", options: ["Mouth", "Teeth", "Ear", "Nose"], correct: "Mouth" },
    { word: "Tête", options: ["Head", "Hand", "Foot", "Leg"], correct: "Head" },
    { word: "Poitrine", options: ["Chest", "Hand", "Foot", "Leg"], correct: "Chest" },
    { word: "Bras", options: ["Arm", "Leg", "Foot", "Hand"], correct: "Arm" },
    { word: "Jambes", options: ["Legs", "Hands", "Feet", "Arms"], correct: "Legs" },
    { word: "Mains", options: ["Hands", "Feet", "Arms", "Legs"], correct: "Hands" },
    { word: "Pieds", options: ["Feet", "Hands", "Arms", "Legs"], correct: "Feet" },
    { word: "Ciel", options: ["Sky", "Ground", "Sea", "Mountain"], correct: "Sky" },
    { word: "Mer", options: ["Sea", "Ocean", "Mountain", "River"], correct: "Sea" },
    { word: "Montagne", options: ["Mountain", "Hill", "Forest", "Desert"], correct: "Mountain" },
    { word: "Plage", options: ["Beach", "Mountain", "River", "Lake"], correct: "Beach" },
    { word: "Neige", options: ["Snow", "Rain", "Sun", "Wind"], correct: "Snow" },
    { word: "Pluie", options: ["Rain", "Sun", "Clouds", "Wind"], correct: "Rain" },
    { word: "Vent", options: ["Wind", "Sun", "Rain", "Snow"], correct: "Wind" },
    { word: "Nuage", options: ["Cloud", "Rain", "Sun", "Wind"], correct: "Cloud" },
    { word: "Temps", options: ["Weather", "Time", "Season", "Day"], correct: "Weather" },
    { word: "Année", options: ["Year", "Month", "Week", "Day"], correct: "Year" },
    { word: "Saison", options: ["Season", "Year", "Month", "Week"], correct: "Season" },
    { word: "Jour", options: ["Day", "Month", "Year", "Week"], correct: "Day" },
    { word: "Heure", options: ["Hour", "Minute", "Second", "Day"], correct: "Hour" },
    { word: "Minute", options: ["Minute", "Second", "Hour", "Day"], correct: "Minute" },
    { word: "Seconde", options: ["Second", "Minute", "Hour", "Day"], correct: "Second" },
    { word: "Demain", options: ["Tomorrow", "Yesterday", "Today", "Week"], correct: "Tomorrow" }
    ],
    B1: [
        {
            word: "Liberté",
            options: ["Freedom", "Justice", "Peace", "Honor"],
            correct: "Freedom"
        }
    ],
    B2: [
        {
            word: "Progrès",
            options: ["Progress", "Decline", "Start", "Stop"],
            correct: "Progress"
        }
    ],
    C1: [
        {
            word: "Harmonie",
            options: ["Harmony", "Chaos", "Peace", "Disagreement"],
            correct: "Harmony"
        }
    ],
    C2: [
        {
            word: "Perfection",
            options: ["Perfection", "Imperfection", "Mediocrity", "Excellence"],
            correct: "Perfection"
        }
    ]
};

// French Word of the Day Data
const frenchWordList = [
    {
        word: "Chien",
        meaning: "Dog",
        plural: "Chiens",
        indefinite: "un",
        definite: "le"
    },
    {
        word: "Livre",
        meaning: "Book",
        plural: "Livres",
        indefinite: "un",
        definite: "le"
    },
    {
        word: "Mer",
        meaning: "Sea",
        plural: "Mers",
        indefinite: "une",
        definite: "la"
    }
];

module.exports = { frenchQuizData, frenchWordList };