// French Quiz Data
const frenchQuizData = {
    A1: [
        { word: "Maison", options: ["House", "Tree", "Car", "Dog"], correct: "House" },
    { word: "Chat", options: ["Cat", "Mouse", "Bird", "Horse"], correct: "Cat" },
    { word: "Chien", options: ["Dog", "Cat", "Fish", "Rabbit"], correct: "Dog" },
    { word: "Voiture", options: ["Bike", "Car", "Bus", "Train"], correct: "Car" },
    { word: "Arbre", options: ["Tree", "Flower", "Bush", "Grass"], correct: "Tree" },
    { word: "Livre", options: ["Pen", "Book", "Table", "Chair"], correct: "Book" },
    { word: "École", options: ["School", "Restaurant", "Park", "Hospital"], correct: "School" },
    { word: "Fleur", options: ["Flower", "Tree", "Plant", "Bush"], correct: "Flower" },
    { word: "Fenêtre", options: ["Window", "Door", "Wall", "Roof"], correct: "Window" },
    { word: "Café", options: ["Tea", "Coffee", "Milk", "Juice"], correct: "Coffee" },
    { word: "Pomme", options: ["Apple", "Banana", "Orange", "Grape"], correct: "Apple" },
    { word: "Pain", options: ["Bread", "Butter", "Cheese", "Jam"], correct: "Bread" },
    { word: "Salade", options: ["Soup", "Salad", "Sandwich", "Fruit"], correct: "Salad" },
    { word: "Chocolat", options: ["Chocolate", "Candy", "Cake", "Ice cream"], correct: "Chocolate" },
    { word: "Voisin", options: ["Neighbor", "Friend", "Family", "Stranger"], correct: "Neighbor" },
    { word: "Chambre", options: ["Room", "Kitchen", "Living room", "Bathroom"], correct: "Room" },
    { word: "Soleil", options: ["Moon", "Sun", "Star", "Cloud"], correct: "Sun" },
    { word: "Lune", options: ["Star", "Cloud", "Sun", "Moon"], correct: "Moon" },
    { word: "Plage", options: ["Mountain", "Lake", "Beach", "Forest"], correct: "Beach" },
    { word: "Mer", options: ["Lake", "Ocean", "River", "Sea"], correct: "Sea" },
    { word: "Montagne", options: ["Hill", "Mountain", "Valley", "Desert"], correct: "Mountain" },
    { word: "Vélo", options: ["Car", "Bicycle", "Bus", "Truck"], correct: "Bicycle" },
    { word: "Chapeau", options: ["Shirt", "Shoes", "Hat", "Pants"], correct: "Hat" },
    { word: "Pantalon", options: ["Shirt", "Shorts", "Trousers", "Jacket"], correct: "Trousers" },
    { word: "Jupe", options: ["Shirt", "Pants", "Skirt", "Coat"], correct: "Skirt" },
    { word: "Chaussures", options: ["Gloves", "Shoes", "Socks", "Hats"], correct: "Shoes" },
    { word: "Pull", options: ["Sweater", "Shirt", "T-shirt", "Jacket"], correct: "Sweater" },
    { word: "Manteau", options: ["Coat", "Jacket", "Sweater", "Shirt"], correct: "Coat" },
    { word: "Hiver", options: ["Winter", "Spring", "Autumn", "Summer"], correct: "Winter" },
    { word: "Été", options: ["Summer", "Winter", "Spring", "Autumn"], correct: "Summer" },
    { word: "Automne", options: ["Spring", "Summer", "Autumn", "Winter"], correct: "Autumn" },
    { word: "Printemps", options: ["Spring", "Summer", "Autumn", "Winter"], correct: "Spring" },
    { word: "Jour", options: ["Night", "Day", "Morning", "Evening"], correct: "Day" },
    { word: "Nuit", options: ["Morning", "Night", "Afternoon", "Evening"], correct: "Night" },
    { word: "Matin", options: ["Morning", "Afternoon", "Night", "Evening"], correct: "Morning" },
    { word: "Soir", options: ["Evening", "Morning", "Afternoon", "Night"], correct: "Evening" },
    { word: "Heure", options: ["Minute", "Hour", "Day", "Week"], correct: "Hour" },
    { word: "Semaine", options: ["Week", "Month", "Year", "Day"], correct: "Week" },
    { word: "Mois", options: ["Month", "Year", "Day", "Week"], correct: "Month" },
    { word: "Année", options: ["Day", "Year", "Month", "Week"], correct: "Year" },
    { word: "Numéro", options: ["Letter", "Number", "Word", "Sentence"], correct: "Number" },
    { word: "Période", options: ["Period", "Point", "Comma", "Exclamation"], correct: "Period" },
    { word: "Téléphone", options: ["Computer", "Phone", "Tablet", "TV"], correct: "Phone" },
    { word: "Tablette", options: ["Book", "Pen", "Tablet", "Phone"], correct: "Tablet" },
    { word: "Ordinateur", options: ["Phone", "Tablet", "Laptop", "Computer"], correct: "Computer" },
    { word: "Télévision", options: ["Radio", "Computer", "Phone", "TV"], correct: "TV" },
    { word: "Chanson", options: ["Song", "Dance", "Poem", "Story"], correct: "Song" },
    { word: "Film", options: ["Show", "Movie", "Series", "Play"], correct: "Movie" },
    { word: "Musique", options: ["Dance", "Music", "Theatre", "Poetry"], correct: "Music" },
    { word: "Livre", options: ["Magazine", "Book", "Newspaper", "Guide"], correct: "Book" },
    { word: "Magasin", options: ["Store", "School", "Market", "Library"], correct: "Store" },
    { word: "Supermarché", options: ["Supermarket", "Restaurant", "Bank", "Post office"], correct: "Supermarket" },
    { word: "Poste", options: ["Post office", "Bank", "Store", "School"], correct: "Post office" },
    { word: "Banque", options: ["School", "Restaurant", "Bank", "Shop"], correct: "Bank" },
    { word: "Bureau", options: ["Office", "Classroom", "Library", "Restaurant"], correct: "Office" },
    { word: "Église", options: ["Church", "Temple", "Mosque", "Synagogue"], correct: "Church" },
    { word: "Mosquée", options: ["Church", "Synagogue", "Temple", "Mosque"], correct: "Mosque" },
    { word: "Temple", options: ["Church", "Temple", "Mosque", "Synagogue"], correct: "Temple" },
    { word: "Hôpital", options: ["Hospital", "Clinic", "School", "Store"], correct: "Hospital" },
    { word: "Médecin", options: ["Teacher", "Doctor", "Nurse", "Patient"], correct: "Doctor" },
    { word: "Infirmière", options: ["Nurse", "Patient", "Doctor", "Teacher"], correct: "Nurse" },
    { word: "Patient", options: ["Doctor", "Nurse", "Patient", "Teacher"], correct: "Patient" },
    { word: "Femme", options: ["Woman", "Man", "Child", "Baby"], correct: "Woman" },
    { word: "Homme", options: ["Man", "Woman", "Child", "Baby"], correct: "Man" },
    { word: "Enfant", options: ["Woman", "Man", "Child", "Baby"], correct: "Child" },
    { word: "Bébé", options: ["Baby", "Child", "Man", "Woman"], correct: "Baby" },
    { word: "Amie", options: ["Friend", "Family", "Neighbor", "Stranger"], correct: "Friend" },
    { word: "Famille", options: ["Family", "Neighbor", "Friend", "Stranger"], correct: "Family" },
    { word: "Voiture", options: ["Car", "Bus", "Truck", "Bicycle"], correct: "Car" },
    { word: "Voleur", options: ["Thief", "Police", "Judge", "Teacher"], correct: "Thief" },
    { word: "Police", options: ["Police", "Firefighter", "Soldier", "Teacher"], correct: "Police" },
    { word: "Soldat", options: ["Soldier", "Policeman", "Firefighter", "Teacher"], correct: "Soldier" },
    { word: "Pompier", options: ["Firefighter", "Policeman", "Soldier", "Teacher"], correct: "Firefighter" },
    { word: "Bureau", options: ["Desk", "Library", "Office", "Classroom"], correct: "Office" },
    { word: "Clé", options: ["Key", "Lock", "Door", "Window"], correct: "Key" },
    { word: "Étoile", options: ["Star", "Moon", "Planet", "Sun"], correct: "Star" },
    { word: "Chocolat", options: ["Chocolate", "Candy", "Cake", "Ice cream"], correct: "Chocolate" },
    { word: "Ciel", options: ["Sky", "Earth", "Ocean", "Cloud"], correct: "Sky" },
    { word: "Oiseau", options: ["Bird", "Fish", "Animal", "Insect"], correct: "Bird" },
    { word: "Voiture", options: ["Car", "Bus", "Bicycle", "Truck"], correct: "Car" },
    { word: "Aéroport", options: ["Airport", "Train station", "Bus stop", "Port"], correct: "Airport" },
    { word: "Bateau", options: ["Boat", "Car", "Train", "Bicycle"], correct: "Boat" },
    { word: "Réseau", options: ["Network", "Phone", "Television", "Computer"], correct: "Network" },
    { word: "Roue", options: ["Wheel", "Pedal", "Handlebar", "Seat"], correct: "Wheel" },
    { word: "Cadeau", options: ["Gift", "Money", "Food", "Clothes"], correct: "Gift" },
    { word: "Chiffre", options: ["Number", "Letter", "Word", "Shape"], correct: "Number" },
    { word: "Élève", options: ["Student", "Teacher", "Principal", "Parent"], correct: "Student" },
    { word: "Souris", options: ["Mouse", "Rat", "Cat", "Dog"], correct: "Mouse" },
    { word: "Tracteur", options: ["Tractor", "Car", "Truck", "Motorcycle"], correct: "Tractor" },
    { word: "Poisson", options: ["Fish", "Shark", "Whale", "Dolphin"], correct: "Fish" },
    { word: "Fenêtre", options: ["Window", "Door", "Wall", "Roof"], correct: "Window" },
    { word: "Papi", options: ["Grandfather", "Father", "Brother", "Uncle"], correct: "Grandfather" },
    { word: "Maman", options: ["Mother", "Father", "Sister", "Brother"], correct: "Mother" },
    { word: "Papa", options: ["Father", "Grandfather", "Uncle", "Brother"], correct: "Father" },
    { word: "Tante", options: ["Aunt", "Uncle", "Mother", "Sister"], correct: "Aunt" },
    { word: "Frère", options: ["Brother", "Sister", "Father", "Uncle"], correct: "Brother" },
    { word: "Sœur", options: ["Sister", "Brother", "Aunt", "Mother"], correct: "Sister" },
    { word: "Fille", options: ["Girl", "Boy", "Child", "Woman"], correct: "Girl" },
    { word: "Garçon", options: ["Boy", "Girl", "Child", "Man"], correct: "Boy" },
    { word: "Mignon", options: ["Cute", "Big", "Old", "Sad"], correct: "Cute" },
    { word: "Grand", options: ["Big", "Small", "Fast", "Slow"], correct: "Big" },
    { word: "Petit", options: ["Small", "Big", "Slow", "Fast"], correct: "Small" },
    { word: "Vieux", options: ["Old", "New", "Young", "Fast"], correct: "Old" },
    { word: "Jeune", options: ["Young", "Old", "Middle-aged", "Big"], correct: "Young" },
    { word: "Mauvais", options: ["Bad", "Good", "Better", "Worst"], correct: "Bad" },
    { word: "Bon", options: ["Good", "Bad", "Better", "Best"], correct: "Good" },
    { word: "Meilleur", options: ["Better", "Good", "Best", "Worst"], correct: "Better" },
    { word: "Meilleur", options: ["Best", "Good", "Better", "Worst"], correct: "Best" },
    { word: "Écouter", options: ["Listen", "Speak", "Read", "Write"], correct: "Listen" },
    { word: "Regarder", options: ["Look", "Listen", "Speak", "Read"], correct: "Look" },
    { word: "Manger", options: ["Eat", "Drink", "Sleep", "Run"], correct: "Eat" },
    { word: "Boire", options: ["Drink", "Eat", "Sleep", "Run"], correct: "Drink" },
    { word: "Dormir", options: ["Sleep", "Run", "Play", "Walk"], correct: "Sleep" },
    { word: "Jouer", options: ["Play", "Work", "Sleep", "Eat"], correct: "Play" },
    { word: "Marcher", options: ["Walk", "Run", "Sit", "Jump"], correct: "Walk" },
    { word: "Courir", options: ["Run", "Walk", "Jump", "Sit"], correct: "Run" },
    { word: "Sauter", options: ["Jump", "Sit", "Run", "Walk"], correct: "Jump" },
    { word: "Écrire", options: ["Write", "Read", "Listen", "Speak"], correct: "Write" },
    { word: "Lire", options: ["Read", "Write", "Speak", "Listen"], correct: "Read" },
    { word: "Parler", options: ["Speak", "Listen", "Read", "Write"], correct: "Speak" },
    { word: "Écrire", options: ["Write", "Speak", "Read", "Listen"], correct: "Write" },
    { word: "Lire", options: ["Read", "Write", "Listen", "Speak"], correct: "Read" },
    { word: "Vendre", options: ["Sell", "Buy", "Exchange", "Donate"], correct: "Sell" },
    { word: "Acheter", options: ["Buy", "Sell", "Give", "Take"], correct: "Buy" },
    { word: "Donner", options: ["Give", "Take", "Buy", "Sell"], correct: "Give" },
    { word: "Prendre", options: ["Take", "Give", "Buy", "Sell"], correct: "Take" },
    { word: "Mettre", options: ["Put", "Take", "Give", "Sell"], correct: "Put" },
    { word: "Journée", options: ["Day", "Night", "Month", "Year"], correct: "Day" },
    { word: "Anniversaire", options: ["Birthday", "Holiday", "Wedding", "Celebration"], correct: "Birthday" },
    { word: "Vacances", options: ["Vacation", "Work", "Study", "Play"], correct: "Vacation" },
    { word: "Fête", options: ["Party", "Work", "Meeting", "Class"], correct: "Party" },
    { word: "Mariage", options: ["Marriage", "Birth", "Death", "Anniversary"], correct: "Marriage" },
    { word: "Naissance", options: ["Birth", "Death", "Anniversary", "Marriage"], correct: "Birth" },
    { word: "Hôpital", options: ["Hospital", "School", "Restaurant", "Market"], correct: "Hospital" },
    { word: "Médecin", options: ["Doctor", "Nurse", "Teacher", "Driver"], correct: "Doctor" },
    { word: "Malade", options: ["Sick", "Healthy", "Tired", "Happy"], correct: "Sick" },
    { word: "Santé", options: ["Health", "Wealth", "Happiness", "Energy"], correct: "Health" },
    { word: "Urgence", options: ["Emergency", "Help", "Hospital", "Doctor"], correct: "Emergency" },
    { word: "Saison", options: ["Season", "Month", "Year", "Day"], correct: "Season" },
    { word: "Froid", options: ["Cold", "Hot", "Warm", "Cool"], correct: "Cold" },
    { word: "Chaud", options: ["Hot", "Cold", "Warm", "Cool"], correct: "Hot" },
    { word: "Pluie", options: ["Rain", "Sun", "Wind", "Snow"], correct: "Rain" },
    { word: "Neige", options: ["Snow", "Rain", "Wind", "Fog"], correct: "Snow" },
    { word: "Nuage", options: ["Cloud", "Sun", "Moon", "Star"], correct: "Cloud" },
    { word: "Vente", options: ["Wind", "Rain", "Storm", "Cloud"], correct: "Wind" },
    { word: "Temps", options: ["Weather", "Time", "Season", "Day"], correct: "Weather" },
    { word: "Bruit", options: ["Noise", "Silence", "Sound", "Word"], correct: "Noise" },
    { word: "Silence", options: ["Silence", "Noise", "Sound", "Word"], correct: "Silence" },
    { word: "Soleil", options: ["Sun", "Moon", "Star", "Planet"], correct: "Sun" },
    { word: "Lune", options: ["Moon", "Star", "Sun", "Planet"], correct: "Moon" },
    { word: "Mois", options: ["Month", "Year", "Week", "Day"], correct: "Month" },
    { word: "Année", options: ["Year", "Month", "Day", "Week"], correct: "Year" }
    ],
    A2: [
        {
            word: "Amitié",
            options: ["Friendship", "Love", "Anger", "Sadness"],
            correct: "Friendship"
        }
    ],
    B1: [
        {
            word: "Liberté",
            options: ["Freedom", "Justice", "Peace", "Honor"],
            correct: "Freedom"
        }
    ],
    B2: [
        {
            word: "Progrès",
            options: ["Progress", "Decline", "Start", "Stop"],
            correct: "Progress"
        }
    ],
    C1: [
        {
            word: "Harmonie",
            options: ["Harmony", "Chaos", "Peace", "Disagreement"],
            correct: "Harmony"
        }
    ],
    C2: [
        {
            word: "Perfection",
            options: ["Perfection", "Imperfection", "Mediocrity", "Excellence"],
            correct: "Perfection"
        }
    ]
};

// French Word of the Day Data
const frenchWordList = [
    {
        word: "Chien",
        meaning: "Dog",
        plural: "Chiens",
        indefinite: "un",
        definite: "le"
    },
    {
        word: "Livre",
        meaning: "Book",
        plural: "Livres",
        indefinite: "un",
        definite: "le"
    },
    {
        word: "Mer",
        meaning: "Sea",
        plural: "Mers",
        indefinite: "une",
        definite: "la"
    }
];

module.exports = { frenchQuizData, frenchWordList };