// French Quiz Data
const frenchQuizData = {
    A1: [
        { word: "Maison", options: ["House", "Car", "Dog", "Tree"], correct: "House" },
    { word: "Chat", options: ["Cat", "Bird", "Horse", "Mouse"], correct: "Cat" },
    { word: "Voiture", options: ["Car", "Bus", "Train", "Bicycle"], correct: "Car" },
    { word: "Chien", options: ["Dog", "Cat", "Fish", "Bird"], correct: "Dog" },
    { word: "Arbre", options: ["Tree", "Flower", "Plant", "Bush"], correct: "Tree" },
    { word: "Fleur", options: ["Flower", "Tree", "Bush", "Plant"], correct: "Flower" },
    { word: "Livre", options: ["Book", "Pen", "Notebook", "Paper"], correct: "Book" },
    { word: "Table", options: ["Table", "Chair", "Sofa", "Desk"], correct: "Table" },
    { word: "Chaise", options: ["Chair", "Table", "Sofa", "Bed"], correct: "Chair" },
    { word: "Ciel", options: ["Sky", "Ocean", "Earth", "Moon"], correct: "Sky" },
    { word: "Soleil", options: ["Sun", "Moon", "Star", "Cloud"], correct: "Sun" },
    { word: "Lune", options: ["Moon", "Sun", "Cloud", "Star"], correct: "Moon" },
    { word: "Eau", options: ["Water", "Milk", "Juice", "Tea"], correct: "Water" },
    { word: "Pain", options: ["Bread", "Rice", "Potato", "Pasta"], correct: "Bread" },
    { word: "Fromage", options: ["Cheese", "Meat", "Fruit", "Vegetable"], correct: "Cheese" },
    { word: "Fruit", options: ["Fruit", "Vegetable", "Bread", "Meat"], correct: "Fruit" },
    { word: "Légume", options: ["Vegetable", "Fruit", "Bread", "Meat"], correct: "Vegetable" },
    { word: "Poisson", options: ["Fish", "Meat", "Bread", "Vegetable"], correct: "Fish" },
    { word: "Viande", options: ["Meat", "Fish", "Fruit", "Vegetable"], correct: "Meat" },
    { word: "Voix", options: ["Voice", "Ear", "Eye", "Mouth"], correct: "Voice" },
    { word: "Main", options: ["Hand", "Foot", "Leg", "Arm"], correct: "Hand" },
    { word: "Pied", options: ["Foot", "Hand", "Arm", "Leg"], correct: "Foot" },
    { word: "Bouche", options: ["Mouth", "Nose", "Ear", "Eye"], correct: "Mouth" },
    { word: "Oreille", options: ["Ear", "Eye", "Mouth", "Nose"], correct: "Ear" },
    { word: "Œil", options: ["Eye", "Ear", "Mouth", "Nose"], correct: "Eye" },
    { word: "Nez", options: ["Nose", "Ear", "Mouth", "Eye"], correct: "Nose" },
    { word: "Cheveux", options: ["Hair", "Teeth", "Eyes", "Hands"], correct: "Hair" },
    { word: "Dent", options: ["Tooth", "Tongue", "Ear", "Mouth"], correct: "Tooth" },
    { word: "Tête", options: ["Head", "Hand", "Foot", "Leg"], correct: "Head" },
    { word: "Corps", options: ["Body", "Arm", "Leg", "Foot"], correct: "Body" },
    { word: "Amis", options: ["Friends", "Family", "Neighbors", "Colleagues"], correct: "Friends" },
    { word: "Famille", options: ["Family", "Friends", "Neighbors", "Classmates"], correct: "Family" },
    { word: "École", options: ["School", "Library", "Park", "Hospital"], correct: "School" },
    { word: "Université", options: ["University", "School", "Library", "College"], correct: "University" },
    { word: "Travail", options: ["Work", "Study", "Play", "Eat"], correct: "Work" },
    { word: "Manger", options: ["Eat", "Sleep", "Drink", "Walk"], correct: "Eat" },
    { word: "Boire", options: ["Drink", "Eat", "Sleep", "Run"], correct: "Drink" },
    { word: "Marcher", options: ["Walk", "Run", "Jump", "Climb"], correct: "Walk" },
    { word: "Courir", options: ["Run", "Walk", "Sleep", "Jump"], correct: "Run" },
    { word: "Dormir", options: ["Sleep", "Eat", "Work", "Run"], correct: "Sleep" },
    { word: "Vêtements", options: ["Clothes", "Shoes", "Bags", "Glasses"], correct: "Clothes" },
    { word: "Chaussures", options: ["Shoes", "Bags", "Clothes", "Socks"], correct: "Shoes" },
    { word: "Sac", options: ["Bag", "Shoe", "Hat", "Jacket"], correct: "Bag" },
    { word: "Chapeau", options: ["Hat", "Gloves", "Scarf", "Socks"], correct: "Hat" },
    { word: "Pantalon", options: ["Pants", "Shirt", "Shoes", "Hat"], correct: "Pants" },
    { word: "Chemise", options: ["Shirt", "Pants", "Socks", "Shoes"], correct: "Shirt" },
    { word: "Jupe", options: ["Skirt", "Pants", "Shirt", "Sweater"], correct: "Skirt" },
    { word: "Robe", options: ["Dress", "Shirt", "Skirt", "Pants"], correct: "Dress" },
    { word: "Chaud", options: ["Hot", "Cold", "Warm", "Cool"], correct: "Hot" },
    { word: "Froid", options: ["Cold", "Hot", "Warm", "Cool"], correct: "Cold" },
    { word: "Soleil", options: ["Sun", "Moon", "Cloud", "Star"], correct: "Sun" },
    { word: "Pluie", options: ["Rain", "Snow", "Wind", "Cloud"], correct: "Rain" },
    { word: "Neige", options: ["Snow", "Rain", "Wind", "Cloud"], correct: "Snow" },
    { word: "Vent", options: ["Wind", "Rain", "Snow", "Cloud"], correct: "Wind" },
    { word: "Chaud", options: ["Warm", "Hot", "Cold", "Cool"], correct: "Warm" },
    { word: "Hiver", options: ["Winter", "Spring", "Summer", "Autumn"], correct: "Winter" },
    { word: "Été", options: ["Summer", "Winter", "Spring", "Autumn"], correct: "Summer" },
    { word: "Automne", options: ["Autumn", "Winter", "Spring", "Summer"], correct: "Autumn" },
    { word: "Printemps", options: ["Spring", "Winter", "Summer", "Autumn"], correct: "Spring" },
    { word: "Maison", options: ["House", "Tree", "Car", "Dog"], correct: "House" },
    { word: "Chat", options: ["Horse", "Cat", "Bird", "Mouse"], correct: "Cat" },
    { word: "Voiture", options: ["Bicycle", "Car", "Bus", "Train"], correct: "Car" },
    { word: "Chien", options: ["Fish", "Bird", "Dog", "Cat"], correct: "Dog" },
    { word: "Arbre", options: ["Tree", "Flower", "Plant", "Bush"], correct: "Tree" },
    { word: "Fleur", options: ["Flower", "Bush", "Plant", "Tree"], correct: "Flower" },
    { word: "Livre", options: ["Pen", "Notebook", "Book", "Paper"], correct: "Book" },
    { word: "Table", options: ["Desk", "Sofa", "Table", "Chair"], correct: "Table" },
    { word: "Chaise", options: ["Chair", "Table", "Bed", "Sofa"], correct: "Chair" },
    { word: "Ciel", options: ["Ocean", "Earth", "Moon", "Sky"], correct: "Sky" },
    { word: "Soleil", options: ["Sun", "Moon", "Cloud", "Star"], correct: "Sun" },
    { word: "Lune", options: ["Moon", "Star", "Sun", "Cloud"], correct: "Moon" },
    { word: "Eau", options: ["Milk", "Tea", "Water", "Juice"], correct: "Water" },
    { word: "Pain", options: ["Rice", "Potato", "Bread", "Pasta"], correct: "Bread" },
    { word: "Fromage", options: ["Fruit", "Cheese", "Vegetable", "Meat"], correct: "Cheese" },
    { word: "Fruit", options: ["Vegetable", "Bread", "Fruit", "Meat"], correct: "Fruit" },
    { word: "Légume", options: ["Meat", "Vegetable", "Fruit", "Bread"], correct: "Vegetable" },
    { word: "Poisson", options: ["Vegetable", "Fish", "Meat", "Bread"], correct: "Fish" },
    { word: "Viande", options: ["Fish", "Meat", "Fruit", "Vegetable"], correct: "Meat" },
    { word: "Voix", options: ["Mouth", "Ear", "Eye", "Voice"], correct: "Voice" },
    { word: "Main", options: ["Foot", "Hand", "Leg", "Arm"], correct: "Hand" },
    { word: "Pied", options: ["Foot", "Leg", "Hand", "Arm"], correct: "Foot" },
    { word: "Bouche", options: ["Nose", "Ear", "Mouth", "Eye"], correct: "Mouth" },
    { word: "Oreille", options: ["Eye", "Mouth", "Ear", "Nose"], correct: "Ear" },
    { word: "Œil", options: ["Eye", "Nose", "Mouth", "Ear"], correct: "Eye" },
    { word: "Nez", options: ["Ear", "Eye", "Mouth", "Nose"], correct: "Nose" },
    { word: "Cheveux", options: ["Eyes", "Teeth", "Hair", "Hands"], correct: "Hair" },
    { word: "Dent", options: ["Tongue", "Tooth", "Ear", "Mouth"], correct: "Tooth" },
    { word: "Tête", options: ["Head", "Foot", "Hand", "Leg"], correct: "Head" },
    { word: "Corps", options: ["Foot", "Body", "Arm", "Leg"], correct: "Body" },
    { word: "Amis", options: ["Classmates", "Neighbors", "Family", "Friends"], correct: "Friends" },
    { word: "Famille", options: ["Friends", "Family", "Neighbors", "Classmates"], correct: "Family" },
    { word: "École", options: ["School", "Park", "Hospital", "Library"], correct: "School" },
    { word: "Université", options: ["School", "College", "University", "Library"], correct: "University" },
    { word: "Travail", options: ["Play", "Eat", "Work", "Study"], correct: "Work" },
    { word: "Manger", options: ["Work", "Eat", "Sleep", "Drink"], correct: "Eat" },
    { word: "Boire", options: ["Sleep", "Run", "Drink", "Eat"], correct: "Drink" },
    { word: "Marcher", options: ["Run", "Jump", "Walk", "Climb"], correct: "Walk" },
    { word: "Courir", options: ["Jump", "Run", "Walk", "Climb"], correct: "Run" },
    { word: "Dormir", options: ["Drink", "Eat", "Sleep", "Work"], correct: "Sleep" },
    { word: "Vêtements", options: ["Bags", "Glasses", "Clothes", "Shoes"], correct: "Clothes" },
    { word: "Chaussures", options: ["Bags", "Shoes", "Clothes", "Socks"], correct: "Shoes" },
    { word: "Sac", options: ["Shoe", "Bag", "Jacket", "Hat"], correct: "Bag" },
    { word: "Chapeau", options: ["Socks", "Gloves", "Hat", "Scarf"], correct: "Hat" },
    { word: "Pantalon", options: ["Shirt", "Pants", "Hat", "Shoes"], correct: "Pants" },
    { word: "Chemise", options: ["Shirt", "Shoes", "Socks", "Pants"], correct: "Shirt" },
    { word: "Jupe", options: ["Shirt", "Skirt", "Sweater", "Pants"], correct: "Skirt" },
    { word: "Robe", options: ["Skirt", "Pants", "Dress", "Shirt"], correct: "Dress" },
    { word: "Chaud", options: ["Hot", "Cold", "Cool", "Warm"], correct: "Hot" },
    { word: "Froid", options: ["Cold", "Warm", "Cool", "Hot"], correct: "Cold" },
    { word: "Soleil", options: ["Star", "Cloud", "Sun", "Moon"], correct: "Sun" },
    { word: "Pluie", options: ["Rain", "Wind", "Cloud", "Snow"], correct: "Rain" },
    { word: "Neige", options: ["Cloud", "Wind", "Snow", "Rain"], correct: "Snow" },
    { word: "Vent", options: ["Wind", "Rain", "Snow", "Cloud"], correct: "Wind" },
    { word: "Chaud", options: ["Cool", "Cold", "Warm", "Hot"], correct: "Warm" },
    { word: "Hiver", options: ["Autumn", "Winter", "Summer", "Spring"], correct: "Winter" },
    { word: "Été", options: ["Summer", "Autumn", "Winter", "Spring"], correct: "Summer" },
    { word: "Automne", options: ["Autumn", "Summer", "Spring", "Winter"], correct: "Autumn" },
    { word: "Printemps", options: ["Spring", "Winter", "Summer", "Autumn"], correct: "Spring" }
]
    ],
    A2: [
        { word: "Bureau", options: ["Office", "Room", "School", "Home"], correct: "Office" },
    { word: "Voyage", options: ["Trip", "Car", "Journey", "Flight"], correct: "Trip" },
    { word: "Gâteau", options: ["Cake", "Bread", "Pasta", "Fruit"], correct: "Cake" },
    { word: "Rêver", options: ["Dream", "Think", "Sleep", "Wake"], correct: "Dream" },
    { word: "Louer", options: ["Rent", "Buy", "Sell", "Borrow"], correct: "Rent" },
    { word: "Arriver", options: ["Arrive", "Leave", "Go", "Stay"], correct: "Arrive" },
    { word: "Vêtements", options: ["Clothes", "Shoes", "Accessories", "Hats"], correct: "Clothes" },
    { word: "Plage", options: ["Beach", "Mountain", "Lake", "Forest"], correct: "Beach" },
    { word: "Cuisine", options: ["Kitchen", "Bedroom", "Living room", "Bathroom"], correct: "Kitchen" },
    { word: "Légumes", options: ["Vegetables", "Fruits", "Meat", "Spices"], correct: "Vegetables" },
    { word: "Français", options: ["French", "English", "German", "Spanish"], correct: "French" },
    { word: "Temps", options: ["Weather", "Time", "Year", "Day"], correct: "Time" },
    { word: "Maison", options: ["House", "Apartment", "Building", "Room"], correct: "House" },
    { word: "Musique", options: ["Music", "Song", "Movie", "Dance"], correct: "Music" },
    { word: "Voiture", options: ["Car", "Bus", "Train", "Bike"], correct: "Car" },
    { word: "Chambre", options: ["Room", "Living room", "Kitchen", "Bathroom"], correct: "Room" },
    { word: "Bateau", options: ["Boat", "Car", "Train", "Plane"], correct: "Boat" },
    { word: "Hôpital", options: ["Hospital", "School", "Shop", "Restaurant"], correct: "Hospital" },
    { word: "Répondre", options: ["Answer", "Ask", "Question", "Talk"], correct: "Answer" },
    { word: "Demander", options: ["Ask", "Answer", "Give", "Tell"], correct: "Ask" },
    { word: "Café", options: ["Coffee", "Tea", "Juice", "Water"], correct: "Coffee" },
    { word: "Thé", options: ["Tea", "Coffee", "Water", "Juice"], correct: "Tea" },
    { word: "Trop", options: ["Too much", "Enough", "Not enough", "Very"], correct: "Too much" },
    { word: "Parler", options: ["Speak", "Listen", "Read", "Write"], correct: "Speak" },
    { word: "Lire", options: ["Read", "Write", "Speak", "Listen"], correct: "Read" },
    { word: "Écrire", options: ["Write", "Read", "Listen", "Speak"], correct: "Write" },
    { word: "Attendre", options: ["Wait", "Go", "Run", "Stop"], correct: "Wait" },
    { word: "Aider", options: ["Help", "Talk", "Call", "Give"], correct: "Help" },
    { word: "Jouer", options: ["Play", "Watch", "Sing", "Dance"], correct: "Play" },
    { word: "Faire", options: ["Do", "Make", "Watch", "Read"], correct: "Do" },
    { word: "Continuer", options: ["Continue", "Stop", "Start", "Pause"], correct: "Continue" },
    { word: "Commencer", options: ["Start", "Finish", "Continue", "Stop"], correct: "Start" },
    { word: "Finir", options: ["Finish", "Start", "Continue", "Pause"], correct: "Finish" },
    { word: "Parler", options: ["Speak", "Listen", "Read", "Write"], correct: "Speak" },
    { word: "Rire", options: ["Laugh", "Cry", "Talk", "Smile"], correct: "Laugh" },
    { word: "Manger", options: ["Eat", "Drink", "Sleep", "Run"], correct: "Eat" },
    { word: "Boire", options: ["Drink", "Eat", "Sleep", "Run"], correct: "Drink" },
    { word: "Dîner", options: ["Dinner", "Breakfast", "Lunch", "Snack"], correct: "Dinner" },
    { word: "Déjeuner", options: ["Lunch", "Dinner", "Breakfast", "Snack"], correct: "Lunch" },
    { word: "Petit-déjeuner", options: ["Breakfast", "Lunch", "Dinner", "Snack"], correct: "Breakfast" },
    { word: "Fort", options: ["Strong", "Weak", "Slow", "Fast"], correct: "Strong" },
    { word: "Faible", options: ["Weak", "Strong", "Slow", "Fast"], correct: "Weak" },
    { word: "Lent", options: ["Slow", "Fast", "Strong", "Weak"], correct: "Slow" },
    { word: "Rapide", options: ["Fast", "Slow", "Weak", "Strong"], correct: "Fast" },
    { word: "Chaud", options: ["Hot", "Cold", "Warm", "Cool"], correct: "Hot" },
    { word: "Froid", options: ["Cold", "Hot", "Warm", "Cool"], correct: "Cold" },
    { word: "Gagner", options: ["Win", "Lose", "Play", "Watch"], correct: "Win" },
    { word: "Perdre", options: ["Lose", "Win", "Play", "Watch"], correct: "Lose" },
    { word: "Connaître", options: ["Know", "Meet", "See", "Talk"], correct: "Know" },
    { word: "Rencontrer", options: ["Meet", "Know", "Talk", "Listen"], correct: "Meet" },
    { word: "Visiter", options: ["Visit", "See", "Meet", "Talk"], correct: "Visit" },
    { word: "Marcher", options: ["Walk", "Run", "Sit", "Stand"], correct: "Walk" },
    { word: "Courir", options: ["Run", "Walk", "Sit", "Stand"], correct: "Run" },
    { word: "Arrêter", options: ["Stop", "Go", "Run", "Walk"], correct: "Stop" },
    { word: "Vendre", options: ["Sell", "Buy", "Give", "Take"], correct: "Sell" },
    { word: "Acheter", options: ["Buy", "Sell", "Give", "Take"], correct: "Buy" },
    { word: "Apprendre", options: ["Learn", "Teach", "Help", "Give"], correct: "Learn" },
    { word: "Enseigner", options: ["Teach", "Learn", "Give", "Help"], correct: "Teach" },
    { word: "Regarder", options: ["Look", "See", "Watch", "Read"], correct: "Watch" },
    { word: "Voir", options: ["See", "Look", "Watch", "Read"], correct: "See" },
    { word: "Écouter", options: ["Listen", "Speak", "Read", "Write"], correct: "Listen" },
    { word: "Entendre", options: ["Hear", "Listen", "Talk", "Speak"], correct: "Hear" },
    { word: "Aimer", options: ["Like", "Love", "Hate", "Dislike"], correct: "Like" },
    { word: "Détester", options: ["Hate", "Like", "Love", "Dislike"], correct: "Hate" },
    { word: "Regarder", options: ["Look", "See", "Watch", "Read"], correct: "Look" },
    { word: "Attendre", options: ["Wait", "Go", "Run", "Stop"], correct: "Wait" },
    { word: "Tant", options: ["So much", "So little", "Not much", "Not little"], correct: "So much" },
    { word: "Savoir", options: ["Know", "Learn", "Understand", "Talk"], correct: "Know" },
    { word: "Comprendre", options: ["Understand", "Talk", "Learn", "Read"], correct: "Understand" },
    { word: "Voler", options: ["Steal", "Fly", "Run", "Walk"], correct: "Steal" },
    { word: "Promettre", options: ["Promise", "Break", "Ask", "Tell"], correct: "Promise" },
    { word: "Crier", options: ["Shout", "Speak", "Talk", "Whisper"], correct: "Shout" },
    { word: "Manger", options: ["Eat", "Drink", "Sleep", "Run"], correct: "Eat" },
    { word: "Plier", options: ["Fold", "Open", "Close", "Tie"], correct: "Fold" },{ word: "Amis", options: ["Friends", "Enemies", "Teachers", "Parents"], correct: "Friends" },
    { word: "Chocolat", options: ["Chocolate", "Cake", "Candy", "Fruit"], correct: "Chocolate" },
    { word: "Soleil", options: ["Sun", "Moon", "Cloud", "Star"], correct: "Sun" },
    { word: "Vêtements", options: ["Clothes", "Shoes", "Hats", "Accessories"], correct: "Clothes" },
    { word: "Bureau", options: ["Office", "Room", "Kitchen", "Bedroom"], correct: "Office" },
    { word: "Fleur", options: ["Flower", "Tree", "Bush", "Plant"], correct: "Flower" },
    { word: "Chanson", options: ["Song", "Movie", "Story", "Game"], correct: "Song" },
    { word: "Maison", options: ["House", "Apartment", "Building", "Store"], correct: "House" },
    { word: "Rivière", options: ["River", "Lake", "Ocean", "Mountain"], correct: "River" },
    { word: "Forêt", options: ["Forest", "Desert", "Island", "Ocean"], correct: "Forest" },
    { word: "Chien", options: ["Dog", "Cat", "Horse", "Rabbit"], correct: "Dog" },
    { word: "Chat", options: ["Cat", "Dog", "Fish", "Bird"], correct: "Cat" },
    { word: "Table", options: ["Table", "Chair", "Sofa", "Bed"], correct: "Table" },
    { word: "Voiture", options: ["Car", "Bike", "Train", "Plane"], correct: "Car" },
    { word: "Vélo", options: ["Bike", "Car", "Bus", "Train"], correct: "Bike" },
    { word: "Eau", options: ["Water", "Juice", "Tea", "Milk"], correct: "Water" },
    { word: "Pain", options: ["Bread", "Rice", "Pasta", "Pizza"], correct: "Bread" },
    { word: "Fromage", options: ["Cheese", "Bread", "Rice", "Fruit"], correct: "Cheese" },
    { word: "Pomme", options: ["Apple", "Banana", "Orange", "Grape"], correct: "Apple" },
    { word: "Banane", options: ["Banana", "Apple", "Orange", "Pear"], correct: "Banana" },
    { word: "Orange", options: ["Orange", "Apple", "Banana", "Grapes"], correct: "Orange" },
    { word: "Lait", options: ["Milk", "Water", "Juice", "Tea"], correct: "Milk" },
    { word: "École", options: ["School", "University", "Library", "Cafe"], correct: "School" },
    { word: "Université", options: ["University", "School", "College", "Library"], correct: "University" },
    { word: "Livre", options: ["Book", "Pen", "Notebook", "Bag"], correct: "Book" },
    { word: "Cahier", options: ["Notebook", "Pen", "Book", "Bag"], correct: "Notebook" },
    { word: "Stylo", options: ["Pen", "Pencil", "Book", "Paper"], correct: "Pen" },
    { word: "Crayon", options: ["Pencil", "Pen", "Eraser", "Book"], correct: "Pencil" },
    { word: "Portefeuille", options: ["Wallet", "Bag", "Phone", "Watch"], correct: "Wallet" },
    { word: "Téléphone", options: ["Phone", "Computer", "Tablet", "Watch"], correct: "Phone" },
    { word: "Montre", options: ["Watch", "Ring", "Bracelet", "Earrings"], correct: "Watch" },
    { word: "Sac", options: ["Bag", "Suitcase", "Backpack", "Box"], correct: "Bag" },
    { word: "Chapeau", options: ["Hat", "Scarf", "Gloves", "Shirt"], correct: "Hat" },
    { word: "Manteau", options: ["Coat", "Shirt", "Pants", "Sweater"], correct: "Coat" },
    { word: "Jupe", options: ["Skirt", "Pants", "Shirt", "Dress"], correct: "Skirt" },
    { word: "Robe", options: ["Dress", "Shirt", "Skirt", "Pants"], correct: "Dress" },
    { word: "Pantalon", options: ["Pants", "Shirt", "Jacket", "Sweater"], correct: "Pants" },
    { word: "T-shirt", options: ["T-shirt", "Shirt", "Sweater", "Jacket"], correct: "T-shirt" },
    { word: "Chaussures", options: ["Shoes", "Socks", "Hat", "Gloves"], correct: "Shoes" },
    { word: "Chaussettes", options: ["Socks", "Shoes", "Hat", "Scarf"], correct: "Socks" },
    { word: "Gloves", options: ["Gants", "Écharpe", "Chapeau", "Chaussettes"], correct: "Gants" },
    { word: "Écharpe", options: ["Scarf", "Gloves", "Hat", "Jacket"], correct: "Scarf" },
    { word: "Voix", options: ["Voice", "Sound", "Face", "Ear"], correct: "Voice" },
    { word: "Oreilles", options: ["Ears", "Eyes", "Mouth", "Nose"], correct: "Ears" },
    { word: "Yeux", options: ["Eyes", "Ears", "Mouth", "Nose"], correct: "Eyes" },
    { word: "Bouche", options: ["Mouth", "Nose", "Eyes", "Ears"], correct: "Mouth" },
    { word: "Nez", options: ["Nose", "Mouth", "Eyes", "Ears"], correct: "Nose" },
    { word: "Visage", options: ["Face", "Head", "Ear", "Eye"], correct: "Face" },
    { word: "Cheveux", options: ["Hair", "Eyes", "Nose", "Mouth"], correct: "Hair" },
    { word: "Dent", options: ["Tooth", "Eye", "Nose", "Mouth"], correct: "Tooth" },
    { word: "Bouche", options: ["Mouth", "Teeth", "Ear", "Nose"], correct: "Mouth" },
    { word: "Tête", options: ["Head", "Hand", "Foot", "Leg"], correct: "Head" },
    { word: "Poitrine", options: ["Chest", "Hand", "Foot", "Leg"], correct: "Chest" },
    { word: "Bras", options: ["Arm", "Leg", "Foot", "Hand"], correct: "Arm" },
    { word: "Jambes", options: ["Legs", "Hands", "Feet", "Arms"], correct: "Legs" },
    { word: "Mains", options: ["Hands", "Feet", "Arms", "Legs"], correct: "Hands" },
    { word: "Pieds", options: ["Feet", "Hands", "Arms", "Legs"], correct: "Feet" },
    { word: "Ciel", options: ["Sky", "Ground", "Sea", "Mountain"], correct: "Sky" },
    { word: "Mer", options: ["Sea", "Ocean", "Mountain", "River"], correct: "Sea" },
    { word: "Montagne", options: ["Mountain", "Hill", "Forest", "Desert"], correct: "Mountain" },
    { word: "Plage", options: ["Beach", "Mountain", "River", "Lake"], correct: "Beach" },
    { word: "Neige", options: ["Snow", "Rain", "Sun", "Wind"], correct: "Snow" },
    { word: "Pluie", options: ["Rain", "Sun", "Clouds", "Wind"], correct: "Rain" },
    { word: "Vent", options: ["Wind", "Sun", "Rain", "Snow"], correct: "Wind" },
    { word: "Nuage", options: ["Cloud", "Rain", "Sun", "Wind"], correct: "Cloud" },
    { word: "Temps", options: ["Weather", "Time", "Season", "Day"], correct: "Weather" },
    { word: "Année", options: ["Year", "Month", "Week", "Day"], correct: "Year" },
    { word: "Saison", options: ["Season", "Year", "Month", "Week"], correct: "Season" },
    { word: "Jour", options: ["Day", "Month", "Year", "Week"], correct: "Day" },
    { word: "Heure", options: ["Hour", "Minute", "Second", "Day"], correct: "Hour" },
    { word: "Minute", options: ["Minute", "Second", "Hour", "Day"], correct: "Minute" },
    { word: "Seconde", options: ["Second", "Minute", "Hour", "Day"], correct: "Second" },
    { word: "Demain", options: ["Tomorrow", "Yesterday", "Today", "Week"], correct: "Tomorrow" }
    ],
    B1: [
        { word: "Tranquille", options: ["Calm", "Loud", "Angry", "Excited"], correct: "Calm" },
    { word: "Connaître", options: ["To know", "To see", "To hear", "To speak"], correct: "To know" },
    { word: "Souhaiter", options: ["To wish", "To want", "To need", "To prefer"], correct: "To wish" },
    { word: "Rapide", options: ["Fast", "Slow", "Heavy", "Light"], correct: "Fast" },
    { word: "Payer", options: ["To pay", "To sell", "To buy", "To save"], correct: "To pay" },
    { word: "Sourire", options: ["To smile", "To cry", "To laugh", "To speak"], correct: "To smile" },
    { word: "Ranger", options: ["To tidy", "To break", "To fix", "To make"], correct: "To tidy" },
    { word: "Inviter", options: ["To invite", "To decline", "To accept", "To refuse"], correct: "To invite" },
    { word: "Attirer", options: ["To attract", "To repel", "To ignore", "To distract"], correct: "To attract" },
    { word: "Déjeuner", options: ["To have lunch", "To eat", "To drink", "To snack"], correct: "To have lunch" },
    { word: "Repas", options: ["Meal", "Snack", "Drink", "Fruit"], correct: "Meal" },
    { word: "Manger", options: ["To eat", "To drink", "To cook", "To serve"], correct: "To eat" },
    { word: "Bureau", options: ["Office", "Bedroom", "Kitchen", "Living room"], correct: "Office" },
    { word: "Régler", options: ["To solve", "To start", "To check", "To repair"], correct: "To solve" },
    { word: "Contrôler", options: ["To control", "To cancel", "To ignore", "To forget"], correct: "To control" },
    { word: "Formidable", options: ["Wonderful", "Bad", "Normal", "Average"], correct: "Wonderful" },
    { word: "Rencontrer", options: ["To meet", "To lose", "To find", "To miss"], correct: "To meet" },
    { word: "Libérer", options: ["To free", "To capture", "To imprison", "To steal"], correct: "To free" },
    { word: "Négocier", options: ["To negotiate", "To agree", "To reject", "To buy"], correct: "To negotiate" },
    { word: "Prendre", options: ["To take", "To give", "To bring", "To show"], correct: "To take" },
    { word: "Gagner", options: ["To win", "To lose", "To tie", "To forfeit"], correct: "To win" },
    { word: "Finir", options: ["To finish", "To start", "To continue", "To pause"], correct: "To finish" },
    { word: "Lancer", options: ["To throw", "To catch", "To keep", "To return"], correct: "To throw" },
    { word: "Économiser", options: ["To save", "To spend", "To waste", "To buy"], correct: "To save" },
    { word: "Saison", options: ["Season", "Month", "Year", "Week"], correct: "Season" },
    { word: "Jouer", options: ["To play", "To watch", "To listen", "To study"], correct: "To play" },
    { word: "Régime", options: ["Diet", "Exercise", "Routine", "Habit"], correct: "Diet" },
    { word: "Accueillir", options: ["To welcome", "To leave", "To forget", "To start"], correct: "To welcome" },
    { word: "Événement", options: ["Event", "Plan", "Discussion", "Travel"], correct: "Event" },
    { word: "Parler", options: ["To speak", "To listen", "To read", "To write"], correct: "To speak" },
    { word: "Mouvement", options: ["Movement", "Stillness", "Position", "Change"], correct: "Movement" },
    { word: "Expérience", options: ["Experience", "Adventure", "Story", "Lesson"], correct: "Experience" },
    { word: "Douter", options: ["To doubt", "To trust", "To believe", "To understand"], correct: "To doubt" },
    { word: "Année", options: ["Year", "Month", "Week", "Day"], correct: "Year" },
    { word: "Sécurité", options: ["Safety", "Danger", "Risk", "Fear"], correct: "Safety" },
    { word: "Calculer", options: ["To calculate", "To read", "To write", "To count"], correct: "To calculate" },
    { word: "Délai", options: ["Deadline", "Plan", "Goal", "Task"], correct: "Deadline" },
    { word: "Récupérer", options: ["To recover", "To lose", "To find", "To save"], correct: "To recover" },
    { word: "Médicament", options: ["Medicine", "Food", "Book", "Tool"], correct: "Medicine" },
    { word: "Étudiant", options: ["Student", "Teacher", "Doctor", "Engineer"], correct: "Student" },
    { word: "Système", options: ["System", "Part", "Piece", "Task"], correct: "System" },
    { word: "Vitesse", options: ["Speed", "Distance", "Height", "Depth"], correct: "Speed" },
    { word: "Louer", options: ["To rent", "To buy", "To sell", "To give"], correct: "To rent" },
    { word: "Changer", options: ["To change", "To keep", "To start", "To stop"], correct: "To change" },
    { word: "Analyser", options: ["To analyze", "To ignore", "To forget", "To decide"], correct: "To analyze" },
    { word: "Décision", options: ["Decision", "Action", "Plan", "Result"], correct: "Decision" },
    { word: "Estimer", options: ["To estimate", "To decide", "To doubt", "To create"], correct: "To estimate" },
    { word: "Critiquer", options: ["To criticize", "To encourage", "To praise", "To explain"], correct: "To criticize" },
    { word: "Considérer", options: ["To consider", "To ignore", "To believe", "To think"], correct: "To consider" },
    { word: "Proposer", options: ["To propose", "To refuse", "To accept", "To expect"], correct: "To propose" },
    { word: "Croire", options: ["To believe", "To think", "To know", "To hope"], correct: "To believe" },
    { word: "Conseil", options: ["Advice", "Mistake", "Suggestion", "Command"], correct: "Advice" },
    { word: "Motivation", options: ["Motivation", "Energy", "Excitement", "Interest"], correct: "Motivation" },
    { word: "Soutenir", options: ["To support", "To resist", "To give", "To oppose"], correct: "To support" },
    { word: "Essayer", options: ["To try", "To ignore", "To quit", "To succeed"], correct: "To try" },
    { word: "Légume", options: ["Vegetable", "Fruit", "Grain", "Seed"], correct: "Vegetable" },
    { word: "Fruit", options: ["Fruit", "Vegetable", "Seed", "Leaf"], correct: "Fruit" },
    { word: "Chiffre", options: ["Number", "Letter", "Symbol", "Word"], correct: "Number" },
    { word: "Propriétaire", options: ["Owner", "Tenant", "Buyer", "Seller"], correct: "Owner" },
    { word: "Habitude", options: ["Habit", "Choice", "Action", "Plan"], correct: "Habit" },
    { word: "Loyer", options: ["Rent", "Sale", "Lease", "Fee"], correct: "Rent" },
    { word: "Logement", options: ["Housing", "Rent", "Residence", "Building"], correct: "Housing" },
    { word: "Payer", options: ["To pay", "To charge", "To rent", "To lend"], correct: "To pay" },
    { word: "Rembourser", options: ["To refund", "To charge", "To pay", "To borrow"], correct: "To refund" },
    { word: "Endroit", options: ["Place", "Position", "Direction", "Area"], correct: "Place" },
    { word: "Rechercher", options: ["To search", "To find", "To lose", "To ignore"], correct: "To search" },
    { word: "Repenser", options: ["To rethink", "To forget", "To ignore", "To consider"], correct: "To rethink" },
    { word: "Résoudre", options: ["To solve", "To delay", "To refuse", "To forget"], correct: "To solve" },
    { word: "Convenir", options: ["To suit", "To reject", "To accept", "To refuse"], correct: "To suit" },
    { word: "Apprendre", options: ["To learn", "To teach", "To forget", "To ignore"], correct: "To learn" },
    { word: "Attendre", options: ["To wait", "To ask", "To act", "To know"], correct: "To wait" },
    { word: "Changer", options: ["To change", "To stay", "To improve", "To wait"], correct: "To change" },
    { word: "Douter", options: ["To doubt", "To trust", "To forget", "To believe"], correct: "To doubt" },
    { word: "Essayer", options: ["To try", "To fail", "To avoid", "To ignore"], correct: "To try" },
    { word: "Finir", options: ["To finish", "To start", "To continue", "To create"], correct: "To finish" },
    { word: "Gagner", options: ["To win", "To lose", "To play", "To fight"], correct: "To win" },
    { word: "Habiter", options: ["To live", "To visit", "To travel", "To leave"], correct: "To live" },
    { word: "Jouer", options: ["To play", "To work", "To rest", "To study"], correct: "To play" },
    { word: "Lancer", options: ["To launch", "To catch", "To stop", "To keep"], correct: "To launch" },
    { word: "Manger", options: ["To eat", "To drink", "To sleep", "To speak"], correct: "To eat" },
    { word: "Nager", options: ["To swim", "To walk", "To run", "To ride"], correct: "To swim" },
    { word: "Oublier", options: ["To forget", "To remember", "To search", "To learn"], correct: "To forget" },
    { word: "Parler", options: ["To speak", "To listen", "To sing", "To read"], correct: "To speak" },
    { word: "Répondre", options: ["To answer", "To ask", "To doubt", "To ignore"], correct: "To answer" },
    { word: "Savoir", options: ["To know", "To forget", "To search", "To dream"], correct: "To know" },
    { word: "Travailler", options: ["To work", "To rest", "To play", "To study"], correct: "To work" },
    { word: "Utiliser", options: ["To use", "To throw", "To break", "To fix"], correct: "To use" },
    { word: "Vendre", options: ["To sell", "To buy", "To steal", "To give"], correct: "To sell" },
    { word: "Visiter", options: ["To visit", "To live", "To leave", "To enjoy"], correct: "To visit" },
    { word: "Accepter", options: ["To accept", "To refuse", "To doubt", "To avoid"], correct: "To accept" },
    { word: "Réussir", options: ["To succeed", "To fail", "To try", "To forget"], correct: "To succeed" },
    { word: "Bénéficier", options: ["To benefit", "To lose", "To ignore", "To avoid"], correct: "To benefit" },
    { word: "Choisir", options: ["To choose", "To refuse", "To decide", "To forget"], correct: "To choose" },
    { word: "Demander", options: ["To ask", "To answer", "To give", "To share"], correct: "To ask" },
    { word: "Emprunter", options: ["To borrow", "To lend", "To buy", "To sell"], correct: "To borrow" },
    { word: "Essayer", options: ["To try", "To fail", "To think", "To learn"], correct: "To try" },
    { word: "Finir", options: ["To finish", "To start", "To continue", "To leave"], correct: "To finish" },
    { word: "Garder", options: ["To keep", "To throw", "To hide", "To share"], correct: "To keep" },
    { word: "Louer", options: ["To rent", "To buy", "To sell", "To give"], correct: "To rent" },
    { word: "Mener", options: ["To lead", "To follow", "To ignore", "To fight"], correct: "To lead" },
    { word: "Nettoyer", options: ["To clean", "To destroy", "To organize", "To create"], correct: "To clean" },
    { word: "Offrir", options: ["To offer", "To receive", "To refuse", "To wait"], correct: "To offer" },
    { word: "Prêter", options: ["To lend", "To borrow", "To buy", "To steal"], correct: "To lend" },
    { word: "Raconter", options: ["To tell", "To ask", "To decide", "To remember"], correct: "To tell" },
    { word: "Regarder", options: ["To watch", "To ignore", "To hear", "To listen"], correct: "To watch" },
    { word: "Réparer", options: ["To repair", "To break", "To destroy", "To clean"], correct: "To repair" },
    { word: "Rester", options: ["To stay", "To go", "To leave", "To return"], correct: "To stay" },
    { word: "Revenir", options: ["To return", "To leave", "To stop", "To exit"], correct: "To return" },
    { word: "Sauter", options: ["To jump", "To sit", "To walk", "To run"], correct: "To jump" },
    { word: "Savoir", options: ["To know", "To ask", "To wonder", "To forget"], correct: "To know" },
    { word: "Tenir", options: ["To hold", "To throw", "To leave", "To break"], correct: "To hold" },
    { word: "Tomber", options: ["To fall", "To rise", "To stand", "To sit"], correct: "To fall" },
    { word: "Tourner", options: ["To turn", "To stop", "To move", "To shake"], correct: "To turn" },
    { word: "Transmettre", options: ["To transmit", "To block", "To hide", "To protect"], correct: "To transmit" },
    { word: "Vivre", options: ["To live", "To die", "To avoid", "To ask"], correct: "To live" },
    { word: "Voler", options: ["To steal", "To fly", "To run", "To jump"], correct: "To steal" },
    { word: "Accompagner", options: ["To accompany", "To reject", "To avoid", "To abandon"], correct: "To accompany" },
    { word: "Apprécier", options: ["To appreciate", "To ignore", "To complain", "To demand"], correct: "To appreciate" },
    { word: "Bâtir", options: ["To build", "To destroy", "To ignore", "To create"], correct: "To build" },
    { word: "Briller", options: ["To shine", "To fall", "To swim", "To talk"], correct: "To shine" },
    { word: "Cacher", options: ["To hide", "To show", "To find", "To seek"], correct: "To hide" },
    { word: "Célébrer", options: ["To celebrate", "To forget", "To refuse", "To ignore"], correct: "To celebrate" },
    { word: "Changer", options: ["To change", "To stay", "To ignore", "To forget"], correct: "To change" },
    { word: "Combiner", options: ["To combine", "To separate", "To ignore", "To doubt"], correct: "To combine" },
    { word: "Confirmer", options: ["To confirm", "To reject", "To deny", "To doubt"], correct: "To confirm" },
    { word: "Contrôler", options: ["To control", "To ignore", "To relax", "To prevent"], correct: "To control" },
    { word: "Cultiver", options: ["To cultivate", "To abandon", "To plant", "To destroy"], correct: "To cultivate" },
    { word: "Démolir", options: ["To demolish", "To build", "To decorate", "To repair"], correct: "To demolish" },
    { word: "Détendre", options: ["To relax", "To stress", "To ignore", "To build"], correct: "To relax" },
    { word: "Diriger", options: ["To direct", "To follow", "To stop", "To help"], correct: "To direct" },
    { word: "Distinguer", options: ["To distinguish", "To confuse", "To merge", "To divide"], correct: "To distinguish" },
    { word: "Écouter", options: ["To listen", "To speak", "To hear", "To look"], correct: "To listen" },
    { word: "Expliquer", options: ["To explain", "To confuse", "To listen", "To doubt"], correct: "To explain" },
    { word: "Fuir", options: ["To flee", "To hide", "To run", "To find"], correct: "To flee" },
    { word: "Louer", options: ["To rent", "To own", "To sell", "To destroy"], correct: "To rent" },
    { word: "Mériter", options: ["To deserve", "To ignore", "To doubt", "To reject"], correct: "To deserve" },
    { word: "Partager", options: ["To share", "To keep", "To enjoy", "To destroy"], correct: "To share" },
    { word: "Perdre", options: ["To lose", "To find", "To win", "To remember"], correct: "To lose" },
    { word: "Prendre", options: ["To take", "To give", "To reject", "To remember"], correct: "To take" },
    { word: "Refuser", options: ["To refuse", "To accept", "To think", "To forget"], correct: "To refuse" },
    { word: "Régler", options: ["To adjust", "To ignore", "To break", "To demand"], correct: "To adjust" },
    { word: "Remercier", options: ["To thank", "To insult", "To ignore", "To reject"], correct: "To thank" }
    ],
    B2: [
        { word: "Accomplir", options: ["To accomplish", "To fail", "To deny", "To ignore"], correct: "To accomplish" },
    { word: "Adopter", options: ["To adopt", "To reject", "To abandon", "To criticize"], correct: "To adopt" },
    { word: "Améliorer", options: ["To improve", "To worsen", "To ignore", "To weaken"], correct: "To improve" },
    { word: "Annoncer", options: ["To announce", "To deny", "To reject", "To confuse"], correct: "To announce" },
    { word: "Apprécier", options: ["To appreciate", "To ignore", "To reject", "To undervalue"], correct: "To appreciate" },
    { word: "Atteindre", options: ["To reach", "To ignore", "To refuse", "To avoid"], correct: "To reach" },
    { word: "Avancer", options: ["To advance", "To retreat", "To stop", "To ignore"], correct: "To advance" },
    { word: "Chercher", options: ["To search", "To find", "To reject", "To ignore"], correct: "To search" },
    { word: "Combattre", options: ["To fight", "To defend", "To ignore", "To run"], correct: "To fight" },
    { word: "Commencer", options: ["To start", "To finish", "To delay", "To reject"], correct: "To start" },
    { word: "Compter", options: ["To count", "To ignore", "To forget", "To subtract"], correct: "To count" },
    { word: "Conclure", options: ["To conclude", "To start", "To confuse", "To delay"], correct: "To conclude" },
    { word: "Confirmer", options: ["To confirm", "To deny", "To ignore", "To reject"], correct: "To confirm" },
    { word: "Considérer", options: ["To consider", "To ignore", "To reject", "To simplify"], correct: "To consider" },
    { word: "Contrôler", options: ["To control", "To lose", "To deny", "To disregard"], correct: "To control" },
    { word: "Convaincre", options: ["To convince", "To deny", "To confuse", "To ignore"], correct: "To convince" },
    { word: "Créer", options: ["To create", "To destroy", "To ignore", "To challenge"], correct: "To create" },
    { word: "Décider", options: ["To decide", "To ignore", "To doubt", "To refuse"], correct: "To decide" },
    { word: "Déclarer", options: ["To declare", "To deny", "To confuse", "To hide"], correct: "To declare" },
    { word: "Défendre", options: ["To defend", "To attack", "To avoid", "To surrender"], correct: "To defend" },
    { word: "Démontrer", options: ["To demonstrate", "To deny", "To confuse", "To ignore"], correct: "To demonstrate" },
    { word: "Déranger", options: ["To disturb", "To calm", "To ignore", "To defend"], correct: "To disturb" },
    { word: "Développer", options: ["To develop", "To simplify", "To stop", "To abandon"], correct: "To develop" },
    { word: "Discuter", options: ["To discuss", "To ignore", "To simplify", "To refuse"], correct: "To discuss" },
    { word: "Écouter", options: ["To listen", "To speak", "To ignore", "To confuse"], correct: "To listen" },
    { word: "Éliminer", options: ["To eliminate", "To accept", "To consider", "To defend"], correct: "To eliminate" },
    { word: "Évaluer", options: ["To evaluate", "To ignore", "To accept", "To doubt"], correct: "To evaluate" },
    { word: "Expliquer", options: ["To explain", "To confuse", "To reject", "To ignore"], correct: "To explain" },
    { word: "Fabriquer", options: ["To manufacture", "To sell", "To purchase", "To destroy"], correct: "To manufacture" },
    { word: "Favoriser", options: ["To favor", "To reject", "To ignore", "To confuse"], correct: "To favor" },
    { word: "Finir", options: ["To finish", "To start", "To confuse", "To reject"], correct: "To finish" },
    { word: "Fournir", options: ["To provide", "To ignore", "To restrict", "To avoid"], correct: "To provide" },
    { word: "Gérer", options: ["To manage", "To neglect", "To ignore", "To stop"], correct: "To manage" },
    { word: "Imaginer", options: ["To imagine", "To forget", "To see", "To reject"], correct: "To imagine" },
    { word: "Influencer", options: ["To influence", "To reject", "To confuse", "To ignore"], correct: "To influence" },
    { word: "Informer", options: ["To inform", "To mislead", "To ignore", "To confuse"], correct: "To inform" },
    { word: "Interdire", options: ["To forbid", "To allow", "To question", "To explain"], correct: "To forbid" },
    { word: "Interroger", options: ["To question", "To ignore", "To reject", "To defend"], correct: "To question" },
    { word: "Juger", options: ["To judge", "To ignore", "To accept", "To question"], correct: "To judge" },
    { word: "Lancer", options: ["To launch", "To catch", "To ignore", "To defend"], correct: "To launch" },
    { word: "Maintenir", options: ["To maintain", "To reject", "To ignore", "To question"], correct: "To maintain" },
    { word: "Mesurer", options: ["To measure", "To estimate", "To confuse", "To ignore"], correct: "To measure" },
    { word: "Montrer", options: ["To show", "To hide", "To ignore", "To simplify"], correct: "To show" },
    { word: "Négocier", options: ["To negotiate", "To ignore", "To accept", "To reject"], correct: "To negotiate" },
    { word: "Obtenir", options: ["To obtain", "To lose", "To forget", "To reject"], correct: "To obtain" },
    { word: "Offrir", options: ["To offer", "To reject", "To avoid", "To give"], correct: "To offer" },
    { word: "Organiser", options: ["To organize", "To ignore", "To complicate", "To reject"], correct: "To organize" },
    { word: "Parvenir", options: ["To reach", "To ignore", "To deny", "To refuse"], correct: "To reach" },
    { word: "Permettre", options: ["To allow", "To forbid", "To reject", "To avoid"], correct: "To allow" },
    { word: "Poser", options: ["To ask", "To ignore", "To refuse", "To reject"], correct: "To ask" },
    { word: "Présenter", options: ["To present", "To reject", "To ignore", "To question"], correct: "To present" },
    { word: "Réaliser", options: ["To achieve", "To forget", "To ignore", "To refuse"], correct: "To achieve" },
    { word: "Recommander", options: ["To recommend", "To reject", "To confuse", "To ignore"], correct: "To recommend" },
    { word: "Réduire", options: ["To reduce", "To increase", "To ignore", "To refuse"], correct: "To reduce" },
    { word: "Réfléchir", options: ["To reflect", "To ignore", "To forget", "To refuse"], correct: "To reflect" },
    { word: "Rencontrer", options: ["To meet", "To ignore", "To avoid", "To reject"], correct: "To meet" },
    { word: "Répondre", options: ["To answer", "To question", "To reject", "To refuse"], correct: "To answer" },
    { word: "Résumer", options: ["To summarize", "To complicate", "To forget", "To deny"], correct: "To summarize" },
    { word: "Réussir", options: ["To succeed", "To fail", "To ignore", "To complicate"], correct: "To succeed" },
    { word: "Suggérer", options: ["To suggest", "To deny", "To reject", "To avoid"], correct: "To suggest" },
    { word: "Tirer", options: ["To pull", "To push", "To ignore", "To question"], correct: "To pull" },
    { word: "Traiter", options: ["To treat", "To ignore", "To reject", "To defend"], correct: "To treat" },
    { word: "Utiliser", options: ["To use", "To refuse", "To ignore", "To reject"], correct: "To use" },
    { word: "Vendre", options: ["To sell", "To buy", "To ignore", "To reject"], correct: "To sell" },
    { word: "Vérifier", options: ["To verify", "To ignore", "To reject", "To question"], correct: "To verify" },
    { word: "Visiter", options: ["To visit", "To ignore", "To question", "To avoid"], correct: "To visit" },{ word: "Acquérir", options: ["To acquire", "To lose", "To reject", "To deny"], correct: "To acquire" },
    { word: "Apparaître", options: ["To appear", "To disappear", "To hide", "To defend"], correct: "To appear" },
    { word: "Assurer", options: ["To ensure", "To ignore", "To deny", "To question"], correct: "To ensure" },
    { word: "Atteindre", options: ["To reach", "To avoid", "To ignore", "To challenge"], correct: "To reach" },
    { word: "Augmenter", options: ["To increase", "To reduce", "To ignore", "To simplify"], correct: "To increase" },
    { word: "Bénéficier", options: ["To benefit", "To lose", "To reject", "To ignore"], correct: "To benefit" },
    { word: "Cacher", options: ["To hide", "To reveal", "To question", "To show"], correct: "To hide" },
    { word: "Clarifier", options: ["To clarify", "To confuse", "To question", "To ignore"], correct: "To clarify" },
    { word: "Compter", options: ["To count", "To forget", "To subtract", "To accept"], correct: "To count" },
    { word: "Considérer", options: ["To consider", "To ignore", "To dismiss", "To reject"], correct: "To consider" },
    { word: "Contenir", options: ["To contain", "To reject", "To deny", "To give"], correct: "To contain" },
    { word: "Contribuer", options: ["To contribute", "To refuse", "To deny", "To ignore"], correct: "To contribute" },
    { word: "Coordonner", options: ["To coordinate", "To confuse", "To ignore", "To divide"], correct: "To coordinate" },
    { word: "Croître", options: ["To grow", "To shrink", "To ignore", "To deny"], correct: "To grow" },
    { word: "Déclencher", options: ["To trigger", "To stop", "To reject", "To ignore"], correct: "To trigger" },
    { word: "Définir", options: ["To define", "To question", "To reject", "To change"], correct: "To define" },
    { word: "Délivrer", options: ["To deliver", "To reject", "To ignore", "To contain"], correct: "To deliver" },
    { word: "Démolir", options: ["To demolish", "To build", "To ignore", "To restore"], correct: "To demolish" },
    { word: "Désirer", options: ["To desire", "To ignore", "To deny", "To accept"], correct: "To desire" },
    { word: "Détendre", options: ["To relax", "To tighten", "To ignore", "To refuse"], correct: "To relax" },
    { word: "Distinguer", options: ["To distinguish", "To confuse", "To ignore", "To reject"], correct: "To distinguish" },
    { word: "Écouter", options: ["To listen", "To ignore", "To reject", "To speak"], correct: "To listen" },
    { word: "Emprunter", options: ["To borrow", "To lend", "To reject", "To question"], correct: "To borrow" },
    { word: "Envisager", options: ["To consider", "To ignore", "To refuse", "To confuse"], correct: "To consider" },
    { word: "Équilibrer", options: ["To balance", "To confuse", "To ignore", "To reject"], correct: "To balance" },
    { word: "Exister", options: ["To exist", "To disappear", "To reject", "To ignore"], correct: "To exist" },
    { word: "Expliquer", options: ["To explain", "To confuse", "To reject", "To dismiss"], correct: "To explain" },
    { word: "Fournir", options: ["To provide", "To refuse", "To ignore", "To reject"], correct: "To provide" },
    { word: "Gérer", options: ["To manage", "To complicate", "To ignore", "To simplify"], correct: "To manage" },
    { word: "Impliquer", options: ["To involve", "To reject", "To ignore", "To complicate"], correct: "To involve" },
    { word: "Innover", options: ["To innovate", "To copy", "To ignore", "To reject"], correct: "To innovate" },
    { word: "Interroger", options: ["To question", "To answer", "To ignore", "To reject"], correct: "To question" },
    { word: "Juger", options: ["To judge", "To ignore", "To accept", "To question"], correct: "To judge" },
    { word: "Lancer", options: ["To launch", "To catch", "To reject", "To question"], correct: "To launch" },
    { word: "Mener", options: ["To lead", "To follow", "To question", "To ignore"], correct: "To lead" },
    { word: "Modifier", options: ["To modify", "To reject", "To ignore", "To follow"], correct: "To modify" },
    { word: "Négocier", options: ["To negotiate", "To ignore", "To reject", "To deny"], correct: "To negotiate" },
    { word: "Noter", options: ["To note", "To forget", "To confuse", "To reject"], correct: "To note" },
    { word: "Obtenir", options: ["To obtain", "To reject", "To lose", "To avoid"], correct: "To obtain" },
    { word: "Organiser", options: ["To organize", "To ignore", "To confuse", "To reject"], correct: "To organize" },
    { word: "Ouvrir", options: ["To open", "To close", "To reject", "To ignore"], correct: "To open" },
    { word: "Participer", options: ["To participate", "To ignore", "To reject", "To deny"], correct: "To participate" },
    { word: "Payer", options: ["To pay", "To charge", "To ignore", "To refuse"], correct: "To pay" },
    { word: "Perdre", options: ["To lose", "To win", "To ignore", "To confuse"], correct: "To lose" },
    { word: "Placer", options: ["To place", "To remove", "To reject", "To ignore"], correct: "To place" },
    { word: "Préférer", options: ["To prefer", "To reject", "To avoid", "To ignore"], correct: "To prefer" },
    { word: "Proposer", options: ["To propose", "To ignore", "To reject", "To accept"], correct: "To propose" },
    { word: "Recevoir", options: ["To receive", "To reject", "To refuse", "To ignore"], correct: "To receive" },
    { word: "Réduire", options: ["To reduce", "To increase", "To ignore", "To complicate"], correct: "To reduce" },
    { word: "Refuser", options: ["To refuse", "To accept", "To ignore", "To question"], correct: "To refuse" },
    { word: "Régler", options: ["To regulate", "To ignore", "To deny", "To reject"], correct: "To regulate" },
    { word: "Remplacer", options: ["To replace", "To ignore", "To question", "To reject"], correct: "To replace" },
    { word: "Réparer", options: ["To repair", "To destroy", "To ignore", "To reject"], correct: "To repair" },
    { word: "Réussir", options: ["To succeed", "To fail", "To confuse", "To reject"], correct: "To succeed" },
    { word: "Réaliser", options: ["To achieve", "To reject", "To fail", "To ignore"], correct: "To achieve" },
    { word: "Résoudre", options: ["To solve", "To confuse", "To reject", "To ignore"], correct: "To solve" },
    { word: "Ressentir", options: ["To feel", "To ignore", "To reject", "To deny"], correct: "To feel" },
    { word: "Suggérer", options: ["To suggest", "To reject", "To confuse", "To ignore"], correct: "To suggest" },
    { word: "Subir", options: ["To undergo", "To avoid", "To reject", "To ignore"], correct: "To undergo" },
    { word: "Tirer", options: ["To pull", "To push", "To ignore", "To defend"], correct: "To pull" },
    { word: "Traiter", options: ["To treat", "To reject", "To ignore", "To question"], correct: "To treat" },
    { word: "Utiliser", options: ["To use", "To ignore", "To refuse", "To reject"], correct: "To use" },
    { word: "Vendre", options: ["To sell", "To buy", "To reject", "To ignore"], correct: "To sell" },
    { word: "Vérifier", options: ["To verify", "To ignore", "To reject", "To question"], correct: "To verify" },
    { word: "Visiter", options: ["To visit", "To ignore", "To reject", "To question"], correct: "To visit" }
    ],
    C1: [
        { word: "Dénoncer", options: ["To denounce", "To support", "To praise", "To ignore"], correct: "To denounce" },
    { word: "Exiger", options: ["To demand", "To ask", "To suggest", "To request"], correct: "To demand" },
    { word: "Obliger", options: ["To oblige", "To refuse", "To suggest", "To delay"], correct: "To oblige" },
    { word: "Acquérir", options: ["To acquire", "To lose", "To find", "To share"], correct: "To acquire" },
    { word: "Réaliser", options: ["To realize", "To dream", "To imagine", "To doubt"], correct: "To realize" },
    { word: "Rétablir", options: ["To restore", "To destroy", "To delay", "To reduce"], correct: "To restore" },
    { word: "Soutenir", options: ["To support", "To oppose", "To criticize", "To abandon"], correct: "To support" },
    { word: "Prendre en charge", options: ["To take care of", "To refuse", "To forget", "To delegate"], correct: "To take care of" },
    { word: "Émerger", options: ["To emerge", "To disappear", "To sink", "To collapse"], correct: "To emerge" },
    { word: "Renoncer", options: ["To give up", "To continue", "To complete", "To reconsider"], correct: "To give up" },
    { word: "Contester", options: ["To contest", "To accept", "To ignore", "To support"], correct: "To contest" },
    { word: "Mettre en œuvre", options: ["To implement", "To plan", "To design", "To ignore"], correct: "To implement" },
    { word: "Hésiter", options: ["To hesitate", "To decide", "To confirm", "To clarify"], correct: "To hesitate" },
    { word: "Percevoir", options: ["To perceive", "To reject", "To ignore", "To avoid"], correct: "To perceive" },
    { word: "Soumettre", options: ["To submit", "To decline", "To reject", "To approve"], correct: "To submit" },
    { word: "Appréhender", options: ["To apprehend", "To understand", "To ignore", "To avoid"], correct: "To apprehend" },
    { word: "Réfuter", options: ["To refute", "To accept", "To confirm", "To question"], correct: "To refute" },
    { word: "Entreprendre", options: ["To undertake", "To avoid", "To finish", "To forget"], correct: "To undertake" },
    { word: "Préconiser", options: ["To advocate", "To avoid", "To recommend", "To reject"], correct: "To advocate" },
    { word: "Tenter", options: ["To try", "To succeed", "To fail", "To avoid"], correct: "To try" },
    { word: "Atteindre", options: ["To reach", "To surpass", "To miss", "To ignore"], correct: "To reach" },
    { word: "Compléter", options: ["To complete", "To start", "To abandon", "To delay"], correct: "To complete" },
    { word: "Expliquer", options: ["To explain", "To understand", "To question", "To assume"], correct: "To explain" },
    { word: "Fusionner", options: ["To merge", "To split", "To create", "To remove"], correct: "To merge" },
    { word: "Considérer", options: ["To consider", "To ignore", "To reject", "To create"], correct: "To consider" },
    { word: "Impliquer", options: ["To involve", "To avoid", "To exclude", "To ignore"], correct: "To involve" },
    { word: "Lutter", options: ["To struggle", "To succeed", "To solve", "To avoid"], correct: "To struggle" },
    { word: "Subir", options: ["To endure", "To reject", "To finish", "To perform"], correct: "To endure" },
    { word: "Discerner", options: ["To discern", "To confuse", "To ignore", "To accept"], correct: "To discern" },
    { word: "Privilégier", options: ["To prioritize", "To ignore", "To reject", "To avoid"], correct: "To prioritize" },
    { word: "Convaincre", options: ["To convince", "To doubt", "To confuse", "To avoid"], correct: "To convince" },
    { word: "Souligner", options: ["To underline", "To ignore", "To confuse", "To delay"], correct: "To underline" },
    { word: "Susciter", options: ["To provoke", "To avoid", "To reject", "To clarify"], correct: "To provoke" },
    { word: "Réagir", options: ["To react", "To ignore", "To discuss", "To doubt"], correct: "To react" },
    { word: "Repousser", options: ["To push back", "To pull forward", "To avoid", "To bring forward"], correct: "To push back" },
    { word: "Cibler", options: ["To target", "To ignore", "To oppose", "To question"], correct: "To target" },
    { word: "Analyser", options: ["To analyze", "To ignore", "To believe", "To reject"], correct: "To analyze" },
    { word: "Convoquer", options: ["To summon", "To ignore", "To attend", "To forget"], correct: "To summon" },
    { word: "Médiatiser", options: ["To publicize", "To ignore", "To reject", "To avoid"], correct: "To publicize" },
    { word: "Régler", options: ["To resolve", "To ignore", "To debate", "To create"], correct: "To resolve" },
    { word: "Redouter", options: ["To dread", "To welcome", "To ignore", "To avoid"], correct: "To dread" },
    { word: "Concevoir", options: ["To design", "To forget", "To avoid", "To question"], correct: "To design" },
    { word: "Négocier", options: ["To negotiate", "To debate", "To ignore", "To forget"], correct: "To negotiate" },
    { word: "Convoquer", options: ["To summon", "To ignore", "To arrange", "To attend"], correct: "To summon" },
    { word: "Rompre", options: ["To break", "To repair", "To build", "To ignore"], correct: "To break" },
    { word: "Juger", options: ["To judge", "To assess", "To deny", "To avoid"], correct: "To judge" },
    { word: "Rejeter", options: ["To reject", "To accept", "To assume", "To suggest"], correct: "To reject" },
    { word: "Attester", options: ["To attest", "To ignore", "To abandon", "To forget"], correct: "To attest" },
    { word: "Subir", options: ["To endure", "To avoid", "To surpass", "To suffer"], correct: "To endure" },
    { word: "Retenir", options: ["To retain", "To forget", "To ignore", "To reject"], correct: "To retain" },
    { word: "Différer", options: ["To differ", "To agree", "To avoid", "To accelerate"], correct: "To differ" },
    { word: "Combiner", options: ["To combine", "To separate", "To divide", "To reject"], correct: "To combine" },
    { word: "Justifier", options: ["To justify", "To deny", "To ignore", "To support"], correct: "To justify" },
    { word: "Omettre", options: ["To omit", "To include", "To delay", "To ignore"], correct: "To omit" },
    { word: "Célébrer", options: ["To celebrate", "To ignore", "To abandon", "To refuse"], correct: "To celebrate" },
    { word: "Distinguer", options: ["To distinguish", "To confuse", "To ignore", "To miss"], correct: "To distinguish" },
    { word: "Évaluer", options: ["To evaluate", "To analyze", "To ignore", "To support"], correct: "To evaluate" },
    { word: "Subir", options: ["To undergo", "To avoid", "To reject", "To create"], correct: "To undergo" },
    { word: "Favoriser", options: ["To favor", "To reject", "To ignore", "To abandon"], correct: "To favor" },
    { word: "Cautionner", options: ["To endorse", "To reject", "To criticize", "To doubt"], correct: "To endorse" },
    { word: "Allouer", options: ["To allocate", "To avoid", "To reject", "To oppose"], correct: "To allocate" },
    { word: "Revendiquer", options: ["To claim", "To ignore", "To avoid", "To reject"], correct: "To claim" },
    { word: "Contester", options: ["To challenge", "To confirm", "To ignore", "To propose"], correct: "To challenge" },
    { word: "Souligner", options: ["To emphasize", "To ignore", "To deny", "To abandon"], correct: "To emphasize" },
    { word: "Acquérir", options: ["To acquire", "To give", "To lose", "To share"], correct: "To acquire" },
    { word: "Affirmer", options: ["To affirm", "To deny", "To question", "To argue"], correct: "To affirm" },
    { word: "Anticiper", options: ["To anticipate", "To ignore", "To avoid", "To forget"], correct: "To anticipate" },
    { word: "Appréhender", options: ["To apprehend", "To appreciate", "To ignore", "To reject"], correct: "To apprehend" },
    { word: "Arbitrer", options: ["To arbitrate", "To mediate", "To ignore", "To rule"], correct: "To arbitrate" },
    { word: "Assimiler", options: ["To assimilate", "To reject", "To separate", "To analyze"], correct: "To assimilate" },
    { word: "Atténuer", options: ["To attenuate", "To emphasize", "To strengthen", "To dismiss"], correct: "To attenuate" },
    { word: "Commettre", options: ["To commit", "To avoid", "To stop", "To refuse"], correct: "To commit" },
    { word: "Concilier", options: ["To reconcile", "To fight", "To separate", "To ignore"], correct: "To reconcile" },
    { word: "Confier", options: ["To entrust", "To hide", "To doubt", "To confuse"], correct: "To entrust" },
    { word: "Connaître", options: ["To know", "To meet", "To remember", "To forget"], correct: "To know" },
    { word: "Contraster", options: ["To contrast", "To compare", "To combine", "To confuse"], correct: "To contrast" },
    { word: "Corroborer", options: ["To corroborate", "To deny", "To dispute", "To question"], correct: "To corroborate" },
    { word: "Déduire", options: ["To deduce", "To infer", "To ignore", "To assume"], correct: "To deduce" },
    { word: "Dénoncer", options: ["To denounce", "To support", "To ignore", "To accept"], correct: "To denounce" },
    { word: "Déstabiliser", options: ["To destabilize", "To stabilize", "To resist", "To balance"], correct: "To destabilize" },
    { word: "Distinguer", options: ["To distinguish", "To confuse", "To forget", "To mix"], correct: "To distinguish" },
    { word: "Discerner", options: ["To discern", "To ignore", "To reject", "To clarify"], correct: "To discern" },
    { word: "Diversifier", options: ["To diversify", "To specialize", "To simplify", "To concentrate"], correct: "To diversify" },
    { word: "Évaluer", options: ["To evaluate", "To ignore", "To estimate", "To forget"], correct: "To evaluate" },
    { word: "Exacerber", options: ["To exacerbate", "To calm", "To reduce", "To balance"], correct: "To exacerbate" },
    { word: "Exploiter", options: ["To exploit", "To ignore", "To respect", "To protect"], correct: "To exploit" },
    { word: "Gérer", options: ["To manage", "To confuse", "To forget", "To resist"], correct: "To manage" },
    { word: "Hypothétiser", options: ["To hypothesize", "To confirm", "To question", "To reject"], correct: "To hypothesize" },
    { word: "Illuster", options: ["To illustrate", "To complicate", "To deny", "To simplify"], correct: "To illustrate" },
    { word: "Innover", options: ["To innovate", "To repeat", "To challenge", "To change"], correct: "To innovate" },
    { word: "Intervenir", options: ["To intervene", "To ignore", "To decline", "To accept"], correct: "To intervene" },
    { word: "Manipuler", options: ["To manipulate", "To ignore", "To respect", "To manage"], correct: "To manipulate" },
    { word: "Mémoriser", options: ["To memorize", "To forget", "To imagine", "To disregard"], correct: "To memorize" },
    { word: "Mériter", options: ["To deserve", "To lose", "To abandon", "To forget"], correct: "To deserve" },
    { word: "Modérer", options: ["To moderate", "To accelerate", "To simplify", "To challenge"], correct: "To moderate" },
    { word: "Négocier", options: ["To negotiate", "To accept", "To ignore", "To refuse"], correct: "To negotiate" },
    { word: "Obliger", options: ["To oblige", "To refuse", "To deny", "To question"], correct: "To oblige" },
    { word: "Optimiser", options: ["To optimize", "To complicate", "To ignore", "To reject"], correct: "To optimize" },
    { word: "Proposer", options: ["To propose", "To accept", "To decline", "To reject"], correct: "To propose" },
    { word: "Réaliser", options: ["To realize", "To forget", "To ignore", "To reject"], correct: "To realize" },
    { word: "Récapituler", options: ["To recap", "To forget", "To complicate", "To dispute"], correct: "To recap" },
    { word: "Réformer", options: ["To reform", "To ignore", "To stagnate", "To maintain"], correct: "To reform" },
    { word: "Réfléchir", options: ["To reflect", "To reject", "To ignore", "To explain"], correct: "To reflect" },
    { word: "Représenter", options: ["To represent", "To ignore", "To confuse", "To simplify"], correct: "To represent" },
    { word: "Revendiquer", options: ["To claim", "To deny", "To question", "To reject"], correct: "To claim" },
    { word: "Réaliser", options: ["To achieve", "To lose", "To forget", "To decline"], correct: "To achieve" },
    { word: "Signifier", options: ["To signify", "To ignore", "To reject", "To accept"], correct: "To signify" },
    { word: "Souligner", options: ["To underline", "To ignore", "To explain", "To question"], correct: "To underline" },
    { word: "Spécialiser", options: ["To specialize", "To ignore", "To simplify", "To diversify"], correct: "To specialize" },
    { word: "Suggérer", options: ["To suggest", "To deny", "To reject", "To avoid"], correct: "To suggest" },
    { word: "Tendre", options: ["To tend", "To ignore", "To focus", "To push"], correct: "To tend" },
    { word: "Transmettre", options: ["To transmit", "To block", "To hide", "To avoid"], correct: "To transmit" },
    { word: "Tromper", options: ["To deceive", "To avoid", "To trust", "To accept"], correct: "To deceive" },
    { word: "Valoriser", options: ["To value", "To devalue", "To ignore", "To waste"], correct: "To value" },
    { word: "Vérifier", options: ["To verify", "To reject", "To assume", "To ignore"], correct: "To verify" },
    { word: "Vulgariser", options: ["To popularize", "To complicate", "To ignore", "To reject"], correct: "To popularize" },
    { word: "Zébrer", options: ["To stripe", "To confuse", "To simplify", "To complicate"], correct: "To stripe" },
    { word: "Accélérer", options: ["To accelerate", "To slow", "To stop", "To ignore"], correct: "To accelerate" },
    { word: "Agir", options: ["To act", "To ignore", "To accept", "To question"], correct: "To act" },
    { word: "Animer", options: ["To animate", "To stop", "To calm", "To avoid"], correct: "To animate" },
    { word: "Appréhender", options: ["To apprehend", "To avoid", "To dismiss", "To reject"], correct: "To apprehend" },
    { word: "Arracher", options: ["To tear", "To mend", "To sew", "To preserve"], correct: "To tear" }
    ],
    C2: [
        { word: "Abhorrer", options: ["To detest", "To accept", "To ignore", "To like"], correct: "To detest" },
    { word: "Acquiescer", options: ["To agree", "To argue", "To refuse", "To question"], correct: "To agree" },
    { word: "Affliger", options: ["To afflict", "To heal", "To help", "To reject"], correct: "To afflict" },
    { word: "Aguerrir", options: ["To toughen", "To weaken", "To comfort", "To reject"], correct: "To toughen" },
    { word: "Alambiqué", options: ["Convoluted", "Clear", "Simple", "Direct"], correct: "Convoluted" },
    { word: "Anachronisme", options: ["Anachronism", "Mistake", "Improvement", "Relevance"], correct: "Anachronism" },
    { word: "Apanage", options: ["Privilege", "Burden", "Duty", "Loss"], correct: "Privilege" },
    { word: "Apostat", options: ["Apostate", "Believer", "Prisoner", "Witness"], correct: "Apostate" },
    { word: "Assiduité", options: ["Diligence", "Negligence", "Failure", "Rest"], correct: "Diligence" },
    { word: "Atrophier", options: ["To atrophy", "To strengthen", "To enlarge", "To neglect"], correct: "To atrophy" },
    { word: "Axiome", options: ["Axiom", "Theorem", "Hypothesis", "Fact"], correct: "Axiom" },
    { word: "Béatifier", options: ["To beatify", "To criticize", "To ignore", "To praise"], correct: "To beatify" },
    { word: "Bifurquer", options: ["To bifurcate", "To unite", "To simplify", "To ignore"], correct: "To bifurcate" },
    { word: "Borne", options: ["Landmark", "Obstacle", "Failure", "Disaster"], correct: "Landmark" },
    { word: "Cacophonie", options: ["Cacophony", "Harmony", "Peace", "Quiet"], correct: "Cacophony" },
    { word: "Caparaçonner", options: ["To caparison", "To strip", "To cover", "To confuse"], correct: "To caparison" },
    { word: "Clémence", options: ["Clemency", "Cruelty", "Indifference", "Injustice"], correct: "Clemency" },
    { word: "Convoiter", options: ["To covet", "To ignore", "To reject", "To acquire"], correct: "To covet" },
    { word: "Cursif", options: ["Cursive", "Printed", "Bold", "Italic"], correct: "Cursive" },
    { word: "Débauche", options: ["Debauchery", "Purity", "Virtue", "Justice"], correct: "Debauchery" },
    { word: "Décréter", options: ["To decree", "To ignore", "To question", "To simplify"], correct: "To decree" },
    { word: "Délectable", options: ["Delectable", "Disgusting", "Tasteless", "Ordinary"], correct: "Delectable" },
    { word: "Dénouement", options: ["Denouement", "Confusion", "Disaster", "Failure"], correct: "Denouement" },
    { word: "Dissension", options: ["Dissension", "Agreement", "Harmony", "Unification"], correct: "Dissension" },
    { word: "Ébaubi", options: ["Astonished", "Bored", "Tired", "Amused"], correct: "Astonished" },
    { word: "Édulcorer", options: ["To sweeten", "To sour", "To ignore", "To spice"], correct: "To sweeten" },
    { word: "Éhonté", options: ["Shameless", "Ashamed", "Confused", "Reluctant"], correct: "Shameless" },
    { word: "Enliser", options: ["To bog down", "To simplify", "To ignore", "To elevate"], correct: "To bog down" },
    { word: "Entrelacer", options: ["To intertwine", "To separate", "To destroy", "To simplify"], correct: "To intertwine" },
    { word: "Epistolaire", options: ["Epistolary", "Oral", "Silent", "Written"], correct: "Epistolary" },
    { word: "Exsangue", options: ["Bloodless", "Alive", "Colorful", "Lively"], correct: "Bloodless" },
    { word: "Flegmatique", options: ["Phlegmatic", "Eager", "Excited", "Lively"], correct: "Phlegmatic" },
    { word: "Fluctuation", options: ["Fluctuation", "Stability", "Stagnation", "Security"], correct: "Fluctuation" },
    { word: "Frugal", options: ["Frugal", "Wasteful", "Generous", "Excessive"], correct: "Frugal" },
    { word: "Galanterie", options: ["Gallantry", "Rudeness", "Insubordination", "Weakness"], correct: "Gallantry" },
    { word: "Généalogie", options: ["Genealogy", "History", "Psychology", "Science"], correct: "Genealogy" },
    { word: "Gravité", options: ["Gravity", "Lightness", "Silliness", "Shyness"], correct: "Gravity" },
    { word: "Hapax", options: ["Hapax", "Common", "Frequent", "Occasional"], correct: "Hapax" },
    { word: "Hérétique", options: ["Heretic", "Believer", "Follower", "Saint"], correct: "Heretic" },
    { word: "Hétérogène", options: ["Heterogeneous", "Homogeneous", "Simple", "Unified"], correct: "Heterogeneous" },
    { word: "Hyperbole", options: ["Hyperbole", "Understatement", "Irony", "Truth"], correct: "Hyperbole" },
    { word: "Irrévocable", options: ["Irrevocable", "Temporary", "Reversible", "Optional"], correct: "Irrevocable" },
    { word: "Jérémiade", options: ["Lamentation", "Happiness", "Victory", "Celebration"], correct: "Lamentation" },
    { word: "Laconique", options: ["Concise", "Verbose", "Talkative", "Confused"], correct: "Concise" },
    { word: "Lénifiant", options: ["Soothing", "Aggressive", "Harsh", "Disruptive"], correct: "Soothing" },
    { word: "Machiavélique", options: ["Machiavellian", "Honest", "Noble", "Simple"], correct: "Machiavellian" },
    { word: "Mélancolie", options: ["Melancholy", "Happiness", "Joy", "Contentment"], correct: "Melancholy" },
    { word: "Métamorphoser", options: ["To metamorphose", "To remain", "To fail", "To reduce"], correct: "To metamorphose" },
    { word: "Miséreux", options: ["Miserable", "Wealthy", "Confident", "Generous"], correct: "Miserable" },
    { word: "Nébuleux", options: ["Nebulous", "Clear", "Certain", "Transparent"], correct: "Nebulous" },
    { word: "Nostalgie", options: ["Nostalgia", "Indifference", "Happiness", "Sadness"], correct: "Nostalgia" },
    { word: "Ostensiblement", options: ["Ostensibly", "Secretly", "Carefully", "Vaguely"], correct: "Ostensibly" },
    { word: "Péripatéticien", options: ["Peripatetic", "Fixed", "Stable", "Permanent"], correct: "Peripatetic" },
    { word: "Pusillanime", options: ["Pusillanimous", "Brave", "Confident", "Aggressive"], correct: "Pusillanimous" },
    { word: "Rébarbatif", options: ["Boring", "Interesting", "Exciting", "New"], correct: "Boring" },
    { word: "Recouvrer", options: ["To recover", "To lose", "To deny", "To reject"], correct: "To recover" },
    { word: "Réfuter", options: ["To refute", "To confirm", "To explain", "To defend"], correct: "To refute" },
    { word: "Réminiscence", options: ["Reminiscence", "Forgetfulness", "Surprise", "Novelty"], correct: "Reminiscence" },
    { word: "Resquiller", options: ["To cheat", "To accept", "To deny", "To decline"], correct: "To cheat" },
    { word: "Sublimer", options: ["To sublimate", "To degrade", "To lower", "To worsen"], correct: "To sublimate" },
    { word: "Surévaluation", options: ["Overvaluation", "Undervaluation", "Equal valuation", "Deflation"], correct: "Overvaluation" },
    { word: "Tantale", options: ["Tantalus", "Freedom", "Greed", "Justice"], correct: "Tantalus" },
    { word: "Ubiquité", options: ["Ubiquity", "Solitude", "Isolation", "Distance"], correct: "Ubiquity" },
    { word: "Véhémence", options: ["Vehemence", "Calmness", "Indifference", "Boredom"], correct: "Vehemence" },
    { word: "Vénalité", options: ["Venality", "Virtue", "Integrity", "Faith"], correct: "Venality" },
    { word: "Volubile", options: ["Voluble", "Silent", "Introverted", "Reserved"], correct: "Voluble" },{ word: "Absolutisme", options: ["Absolutism", "Democracy", "Monarchy", "Revolution"], correct: "Absolutism" },
    { word: "Acédie", options: ["Acedia", "Energy", "Happiness", "Indifference"], correct: "Acedia" },
    { word: "Adhésion", options: ["Adherence", "Rejection", "Opposition", "Indifference"], correct: "Adherence" },
    { word: "Adjuvant", options: ["Adjuvant", "Inhibitor", "Obstacle", "Advantage"], correct: "Adjuvant" },
    { word: "Amphigouri", options: ["Ambiguity", "Clarity", "Simplicity", "Precision"], correct: "Ambiguity" },
    { word: "Anacoluthe", options: ["Anacoluthon", "Coherence", "Parallelism", "Elegance"], correct: "Anacoluthon" },
    { word: "Anhedonie", options: ["Anhedonia", "Euphoria", "Happiness", "Joy"], correct: "Anhedonia" },
    { word: "Apocryphe", options: ["Apocryphal", "Authentic", "True", "Correct"], correct: "Apocryphal" },
    { word: "Ardu", options: ["Arduous", "Easy", "Simple", "Effortless"], correct: "Arduous" },
    { word: "Axiologique", options: ["Axiological", "Historical", "Philosophical", "Political"], correct: "Axiological" },
    { word: "Bifurquer", options: ["To bifurcate", "To unite", "To separate", "To simplify"], correct: "To bifurcate" },
    { word: "Bourgeoisie", options: ["Bourgeoisie", "Proletariat", "Nobility", "Clergy"], correct: "Bourgeoisie" },
    { word: "Cacophonie", options: ["Cacophony", "Harmony", "Silence", "Melody"], correct: "Cacophony" },
    { word: "Caustique", options: ["Caustic", "Gentle", "Soothing", "Harmless"], correct: "Caustic" },
    { word: "Chimère", options: ["Chimera", "Reality", "Truth", "Pragmatism"], correct: "Chimera" },
    { word: "Circumnavigation", options: ["Circumnavigation", "Straight path", "Detour", "Opposition"], correct: "Circumnavigation" },
    { word: "Conjoncture", options: ["Conjunction", "Paradox", "Circumstance", "Outcome"], correct: "Circumstance" },
    { word: "Débacle", options: ["Debacle", "Victory", "Resolution", "Unification"], correct: "Debacle" },
    { word: "Déférence", options: ["Deference", "Disrespect", "Rejection", "Opposition"], correct: "Deference" },
    { word: "Délétère", options: ["Deleterious", "Beneficial", "Harmless", "Neutral"], correct: "Deleterious" },
    { word: "Diaphane", options: ["Diaphanous", "Opaque", "Solid", "Opaque"], correct: "Diaphanous" },
    { word: "Dichotomie", options: ["Dichotomy", "Unity", "Agreement", "Consistency"], correct: "Dichotomy" },
    { word: "Effervescence", options: ["Effervescence", "Calmness", "Stillness", "Serenity"], correct: "Effervescence" },
    { word: "Éphémère", options: ["Ephemeral", "Permanent", "Timeless", "Enduring"], correct: "Ephemeral" },
    { word: "Équanimité", options: ["Equanimity", "Imbalance", "Emotional", "Erratic"], correct: "Equanimity" },
    { word: "Exubérance", options: ["Exuberance", "Subdued", "Boring", "Monotony"], correct: "Exuberance" },
    { word: "Factieux", options: ["Factious", "Harmonious", "Unity", "Peaceful"], correct: "Factious" },
    { word: "Fiduciaire", options: ["Fiduciary", "Indifferent", "Neutral", "Disregarding"], correct: "Fiduciary" },
    { word: "Frugalité", options: ["Frugality", "Extravagance", "Profligacy", "Indulgence"], correct: "Frugality" },
    { word: "Généalogie", options: ["Genealogy", "History", "Philosophy", "Geography"], correct: "Genealogy" },
    { word: "Hapax", options: ["Hapax", "Common", "Frequent", "Occasional"], correct: "Hapax" },
    { word: "Hétérogénéité", options: ["Heterogeneity", "Homogeneity", "Consistency", "Unity"], correct: "Heterogeneity" },
    { word: "Hyménée", options: ["Hymen", "Marriage", "Reunion", "Peace"], correct: "Marriage" },
    { word: "Irrévocable", options: ["Irrevocable", "Reversible", "Optional", "Temporary"], correct: "Irrevocable" },
    { word: "Jérémiade", options: ["Lamentation", "Celebration", "Joy", "Happiness"], correct: "Lamentation" },
    { word: "Laconique", options: ["Concise", "Verbose", "Talkative", "Confused"], correct: "Concise" },
    { word: "Machiavélique", options: ["Machiavellian", "Honest", "Principled", "Noble"], correct: "Machiavellian" },
    { word: "Mélancolie", options: ["Melancholy", "Happiness", "Joy", "Euphoria"], correct: "Melancholy" },
    { word: "Nébuleux", options: ["Nebulous", "Clear", "Definite", "Visible"], correct: "Nebulous" },
    { word: "Ostensiblement", options: ["Ostensibly", "Secretly", "Carefully", "Vaguely"], correct: "Ostensibly" },
    { word: "Paroxysme", options: ["Paroxysm", "Calm", "Serenity", "Tranquility"], correct: "Paroxysm" },
    { word: "Péripétie", options: ["Incident", "Continuity", "Sameness", "Predictability"], correct: "Incident" },
    { word: "Phlogistique", options: ["Phlogiston", "Oxygen", "Carbon", "Nitrogen"], correct: "Phlogiston" },
    { word: "Pusillanime", options: ["Pusillanimous", "Brave", "Confident", "Courageous"], correct: "Pusillanimous" },
    { word: "Rappel", options: ["Reminder", "Neglect", "Forgetfulness", "Confusion"], correct: "Reminder" },
    { word: "Rédhibitoire", options: ["Redhibitory", "Minor", "Unimportant", "Negligible"], correct: "Redhibitory" },
    { word: "Sérendipité", options: ["Serendipity", "Calculation", "Determination", "Prediction"], correct: "Serendipity" },
    { word: "Sic", options: ["Thus", "Not", "Inexact", "Incorrect"], correct: "Thus" },
    { word: "Sine qua non", options: ["Essential", "Optional", "Indifferent", "Secondary"], correct: "Essential" },
    { word: "Sobriquet", options: ["Nickname", "Real name", "Surname", "Title"], correct: "Nickname" },
    { word: "Subreptice", options: ["Subreptitious", "Open", "Transparent", "Honest"], correct: "Subreptitious" },
    { word: "Syllogisme", options: ["Syllogism", "Assumption", "Opinion", "Argument"], correct: "Syllogism" },
    { word: "Tautologie", options: ["Tautology", "Fallacy", "Argument", "Illusion"], correct: "Tautology" },
    { word: "Truculent", options: ["Truculent", "Gentle", "Submissive", "Calm"], correct: "Truculent" },
    { word: "Ubiquité", options: ["Ubiquity", "Solitude", "Isolation", "Distance"], correct: "Ubiquity" },
    { word: "Vélocité", options: ["Velocity", "Slowness", "Stagnation", "Stillness"], correct: "Velocity" },
    { word: "Vénalité", options: ["Venality", "Integrity", "Purity", "Faith"], correct: "Venality" },
    { word: "Verbiage", options: ["Verbiage", "Conciseness", "Clarity", "Brevity"], correct: "Verbiage" },
    { word: "Vexatoire", options: ["Vexatious", "Pleasing", "Kind", "Supportive"], correct: "Vexatious" },
    { word: "Volubile", options: ["Voluble", "Silent", "Introverted", "Reserved"], correct: "Voluble" }
    ]
};

// French Word of the Day Data
const frenchWordList = [
    { "word": "Chien", "meaning": "Dog", "plural": "Chiens", "indefinite": "un", "definite": "le" },
    { "word": "Livre", "meaning": "Book", "plural": "Livres", "indefinite": "un", "definite": "le" },
    { "word": "Mer", "meaning": "Sea", "plural": "Mers", "indefinite": "une", "definite": "la" },
    { "word": "Chat", "meaning": "Cat", "plural": "Chats", "indefinite": "un", "definite": "le" },
    { "word": "Fleur", "meaning": "Flower", "plural": "Fleurs", "indefinite": "une", "definite": "la" },
    { "word": "Voiture", "meaning": "Car", "plural": "Voitures", "indefinite": "une", "definite": "la" },
    { "word": "Maison", "meaning": "House", "plural": "Maisons", "indefinite": "une", "definite": "la" },
    { "word": "Arbre", "meaning": "Tree", "plural": "Arbres", "indefinite": "un", "definite": "l'" },
    { "word": "Chaise", "meaning": "Chair", "plural": "Chaises", "indefinite": "une", "definite": "la" },
    { "word": "Table", "meaning": "Table", "plural": "Tables", "indefinite": "une", "definite": "la" },
    { "word": "Pomme", "meaning": "Apple", "plural": "Pommes", "indefinite": "une", "definite": "la" },
    { "word": "École", "meaning": "School", "plural": "Écoles", "indefinite": "une", "definite": "l'" },
    { "word": "Bureau", "meaning": "Office", "plural": "Bureaux", "indefinite": "un", "definite": "le" },
    { "word": "Fenêtre", "meaning": "Window", "plural": "Fenêtres", "indefinite": "une", "definite": "la" },
    { "word": "Chapeau", "meaning": "Hat", "plural": "Chapeaux", "indefinite": "un", "definite": "le" },
    { "word": "Robe", "meaning": "Dress", "plural": "Robes", "indefinite": "une", "definite": "la" },
    { "word": "Vêtement", "meaning": "Clothing", "plural": "Vêtements", "indefinite": "un", "definite": "le" },
    { "word": "Pain", "meaning": "Bread", "plural": "Pains", "indefinite": "un", "definite": "le" },
    { "word": "Fromage", "meaning": "Cheese", "plural": "Fromages", "indefinite": "un", "definite": "le" },
    { "word": "Poisson", "meaning": "Fish", "plural": "Poissons", "indefinite": "un", "definite": "le" },
    { "word": "Lait", "meaning": "Milk", "plural": "Laits", "indefinite": "un", "definite": "le" },
    { "word": "Eau", "meaning": "Water", "plural": "Eaux", "indefinite": "de l'", "definite": "l'" },
    { "word": "Ciel", "meaning": "Sky", "plural": "Ciels", "indefinite": "un", "definite": "le" },
    { "word": "Étoile", "meaning": "Star", "plural": "Étoiles", "indefinite": "une", "definite": "l'" },
    { "word": "Montagne", "meaning": "Mountain", "plural": "Montagnes", "indefinite": "une", "definite": "la" },
    { "word": "Rivière", "meaning": "River", "plural": "Rivières", "indefinite": "une", "definite": "la" },
    { "word": "Plage", "meaning": "Beach", "plural": "Plages", "indefinite": "une", "definite": "la" },
    { "word": "Ville", "meaning": "City", "plural": "Villes", "indefinite": "une", "definite": "la" },
    { "word": "Pays", "meaning": "Country", "plural": "Pays", "indefinite": "un", "definite": "le" },
    { "word": "Rue", "meaning": "Street", "plural": "Rues", "indefinite": "une", "definite": "la" },
    { "word": "Route", "meaning": "Road", "plural": "Routes", "indefinite": "une", "definite": "la" },
    { "word": "Parc", "meaning": "Park", "plural": "Parcs", "indefinite": "un", "definite": "le" },
    { "word": "Jardin", "meaning": "Garden", "plural": "Jardins", "indefinite": "un", "definite": "le" },
    { "word": "Armoire", "meaning": "Wardrobe", "plural": "Armoires", "indefinite": "une", "definite": "l'" },
    { "word": "Tapis", "meaning": "Carpet", "plural": "Tapis", "indefinite": "un", "definite": "le" },
    { "word": "Télévision", "meaning": "Television", "plural": "Télévisions", "indefinite": "une", "definite": "la" },
    { "word": "Ordinateur", "meaning": "Computer", "plural": "Ordinateurs", "indefinite": "un", "definite": "l'" },
    { "word": "Téléphone", "meaning": "Phone", "plural": "Téléphones", "indefinite": "un", "definite": "le" },
    { "word": "Lampe", "meaning": "Lamp", "plural": "Lampes", "indefinite": "une", "definite": "la" },
    { "word": "Sac", "meaning": "Bag", "plural": "Sacs", "indefinite": "un", "definite": "le" },
    { "word": "Clé", "meaning": "Key", "plural": "Clés", "indefinite": "une", "definite": "la" },
    { "word": "Carte", "meaning": "Card", "plural": "Cartes", "indefinite": "une", "definite": "la" },
    { "word": "Monnaie", "meaning": "Money", "plural": "Monnaies", "indefinite": "une", "definite": "la" },
    { "word": "Chiffre", "meaning": "Number", "plural": "Chiffres", "indefinite": "un", "definite": "le" },
    { "word": "Heure", "meaning": "Hour", "plural": "Heures", "indefinite": "une", "definite": "l'" },
    { "word": "Minute", "meaning": "Minute", "plural": "Minutes", "indefinite": "une", "definite": "la" },
    { "word": "Seconde", "meaning": "Second", "plural": "Secondes", "indefinite": "une", "definite": "la" },
    { "word": "Jour", "meaning": "Day", "plural": "Jours", "indefinite": "un", "definite": "le" },
    { "word": "Semaine", "meaning": "Week", "plural": "Semaines", "indefinite": "une", "definite": "la" },
    { "word": "Mois", "meaning": "Month", "plural": "Mois", "indefinite": "un", "definite": "le" },
    { "word": "Année", "meaning": "Year", "plural": "Années", "indefinite": "une", "definite": "l'" },
    { "word": "Été", "meaning": "Summer", "plural": "Étés", "indefinite": "un", "definite": "l'" },
    { "word": "Hiver", "meaning": "Winter", "plural": "Hivers", "indefinite": "un", "definite": "l'" },
    { "word": "Printemps", "meaning": "Spring", "plural": "Printemps", "indefinite": "un", "definite": "le" },
    { "word": "Automne", "meaning": "Autumn", "plural": "Automnes", "indefinite": "un", "definite": "l'" },
    { "word": "Mercredi", "meaning": "Wednesday", "plural": "Mercredis", "indefinite": "un", "definite": "le" },
    { "word": "Jeudi", "meaning": "Thursday", "plural": "Jeudis", "indefinite": "un", "definite": "le" },
    { "word": "Vendredi", "meaning": "Friday", "plural": "Vendredis", "indefinite": "un", "definite": "le" },
    { "word": "Samedi", "meaning": "Saturday", "plural": "Samedis", "indefinite": "un", "definite": "le" },
    { "word": "Dimanche", "meaning": "Sunday", "plural": "Dimanches", "indefinite": "un", "definite": "le" },
    { "word": "Lundi", "meaning": "Monday", "plural": "Lundis", "indefinite": "un", "definite": "le" },
    { "word": "Soleil", "meaning": "Sun", "plural": "Soleils", "indefinite": "un", "definite": "le" },
    { "word": "Lune", "meaning": "Moon", "plural": "Lunes", "indefinite": "une", "definite": "la" },
    { "word": "Ciel", "meaning": "Sky", "plural": "Ciels", "indefinite": "un", "definite": "le" },
    { "word": "Nuage", "meaning": "Cloud", "plural": "Nuages", "indefinite": "un", "definite": "le" },
    { "word": "Pluie", "meaning": "Rain", "plural": "Pluies", "indefinite": "une", "definite": "la" },
    { "word": "Neige", "meaning": "Snow", "plural": "Neiges", "indefinite": "une", "definite": "la" },
    { "word": "Vent", "meaning": "Wind", "plural": "Vents", "indefinite": "un", "definite": "le" },
    { "word": "Température", "meaning": "Temperature", "plural": "Températures", "indefinite": "une", "definite": "la" },
    { "word": "Climat", "meaning": "Climate", "plural": "Climats", "indefinite": "un", "definite": "le" },
    { "word": "Plante", "meaning": "Plant", "plural": "Plantes", "indefinite": "une", "definite": "la" },
    { "word": "Arbre", "meaning": "Tree", "plural": "Arbres", "indefinite": "un", "definite": "le" },
    { "word": "Forêt", "meaning": "Forest", "plural": "Forêts", "indefinite": "une", "definite": "la" },
    { "word": "Île", "meaning": "Island", "plural": "Îles", "indefinite": "une", "definite": "l'" },
    { "word": "Chocolat", "meaning": "Chocolate", "plural": "Chocolats", "indefinite": "un", "definite": "le" },
    { "word": "Fruit", "meaning": "Fruit", "plural": "Fruits", "indefinite": "un", "definite": "le" },
    { "word": "Vélo", "meaning": "Bicycle", "plural": "Vélos", "indefinite": "un", "definite": "le" },
    { "word": "Télescope", "meaning": "Telescope", "plural": "Télescopes", "indefinite": "un", "definite": "le" },
    { "word": "Piano", "meaning": "Piano", "plural": "Pianos", "indefinite": "un", "definite": "le" },
    { "word": "Guitare", "meaning": "Guitar", "plural": "Guitares", "indefinite": "une", "definite": "la" },
    { "word": "Violon", "meaning": "Violin", "plural": "Violons", "indefinite": "un", "definite": "le" },
    { "word": "Sculpture", "meaning": "Sculpture", "plural": "Sculptures", "indefinite": "une", "definite": "la" },
    { "word": "Peinture", "meaning": "Painting", "plural": "Peintures", "indefinite": "une", "definite": "la" },
    { "word": "Chanson", "meaning": "Song", "plural": "Chansons", "indefinite": "une", "definite": "la" },
    { "word": "Film", "meaning": "Film", "plural": "Films", "indefinite": "un", "definite": "le" },
    { "word": "Théâtre", "meaning": "Theater", "plural": "Théâtres", "indefinite": "un", "definite": "le" },
    { "word": "Danse", "meaning": "Dance", "plural": "Danses", "indefinite": "une", "definite": "la" },
    { "word": "Poème", "meaning": "Poem", "plural": "Poèmes", "indefinite": "un", "definite": "le" },
    { "word": "Roman", "meaning": "Novel", "plural": "Romans", "indefinite": "un", "definite": "le" },
    { "word": "Écrivain", "meaning": "Writer", "plural": "Écrivains", "indefinite": "un", "definite": "l'" },
    { "word": "Journal", "meaning": "Newspaper", "plural": "Journaux", "indefinite": "un", "definite": "le" },
    { "word": "Magazine", "meaning": "Magazine", "plural": "Magazines", "indefinite": "un", "definite": "le" },
    { "word": "Téléphone", "meaning": "Phone", "plural": "Téléphones", "indefinite": "un", "definite": "le" },
    { "word": "Appareil", "meaning": "Device", "plural": "Appareils", "indefinite": "un", "definite": "l'" },
    { "word": "Écran", "meaning": "Screen", "plural": "Écrans", "indefinite": "un", "definite": "l'" },
    { "word": "Clé", "meaning": "Key", "plural": "Clés", "indefinite": "une", "definite": "la" },
    { "word": "Cartable", "meaning": "Schoolbag", "plural": "Cartables", "indefinite": "un", "definite": "le" },
    { "word": "Bouteille", "meaning": "Bottle", "plural": "Bouteilles", "indefinite": "une", "definite": "la" },
    { "word": "Verre", "meaning": "Glass", "plural": "Verres", "indefinite": "un", "definite": "le" },
    { "word": "Cuillère", "meaning": "Spoon", "plural": "Cuillères", "indefinite": "une", "definite": "la" },
    { "word": "Fourchette", "meaning": "Fork", "plural": "Fourchettes", "indefinite": "une", "definite": "la" },
    { "word": "Couteau", "meaning": "Knife", "plural": "Couteaux", "indefinite": "un", "definite": "le" },
    { "word": "Assiette", "meaning": "Plate", "plural": "Assiettes", "indefinite": "une", "definite": "la" },
    { "word": "Serviette", "meaning": "Napkin", "plural": "Serviettes", "indefinite": "une", "definite": "la" },
    { "word": "Fenêtre", "meaning": "Window", "plural": "Fenêtres", "indefinite": "une", "definite": "la" },
    { "word": "Porte", "meaning": "Door", "plural": "Portes", "indefinite": "une", "definite": "la" },
    { "word": "Clé", "meaning": "Key", "plural": "Clés", "indefinite": "une", "definite": "la" },
    { "word": "Miroir", "meaning": "Mirror", "plural": "Miroirs", "indefinite": "un", "definite": "le" },
    { "word": "Toilette", "meaning": "Toilet", "plural": "Toilettes", "indefinite": "une", "definite": "la" },
    { "word": "Salle", "meaning": "Room", "plural": "Salles", "indefinite": "une", "definite": "la" },
    { "word": "Cuisine", "meaning": "Kitchen", "plural": "Cuisines", "indefinite": "une", "definite": "la" },
    { "word": "Salon", "meaning": "Living Room", "plural": "Salons", "indefinite": "un", "definite": "le" },
    { "word": "Chambre", "meaning": "Bedroom", "plural": "Chambres", "indefinite": "une", "definite": "la" },
    { "word": "Couloir", "meaning": "Corridor", "plural": "Couloirs", "indefinite": "un", "definite": "le" },
    { "word": "Garage", "meaning": "Garage", "plural": "Garages", "indefinite": "un", "definite": "le" },
    { "word": "Jardin", "meaning": "Garden", "plural": "Jardins", "indefinite": "un", "definite": "le" },
    { "word": "Bureau", "meaning": "Desk", "plural": "Bureaux", "indefinite": "un", "definite": "le" },
    { "word": "Étagère", "meaning": "Shelf", "plural": "Étagères", "indefinite": "une", "definite": "la" },
    { "word": "Lampe", "meaning": "Lamp", "plural": "Lampes", "indefinite": "une", "definite": "la" },
    { "word": "Chaise", "meaning": "Chair", "plural": "Chaises", "indefinite": "une", "definite": "la" },
    { "word": "Canapé", "meaning": "Couch", "plural": "Canapés", "indefinite": "un", "definite": "le" },
    { "word": "Télévision", "meaning": "Television", "plural": "Télévisions", "indefinite": "une", "definite": "la" },
    { "word": "Radio", "meaning": "Radio", "plural": "Radios", "indefinite": "une", "definite": "la" },
    { "word": "Ordinateur", "meaning": "Computer", "plural": "Ordinateurs", "indefinite": "un", "definite": "l'" },
    { "word": "Bureau", "meaning": "Office", "plural": "Bureaux", "indefinite": "un", "definite": "le" },
    { "word": "Drapeau", "meaning": "Flag", "plural": "Drapeaux", "indefinite": "un", "definite": "le" },
    { "word": "Mappemonde", "meaning": "Globe", "plural": "Mappemondes", "indefinite": "une", "definite": "la" },
    { "word": "Planète", "meaning": "Planet", "plural": "Planètes", "indefinite": "une", "definite": "la" },
    { "word": "Étoile", "meaning": "Star", "plural": "Étoiles", "indefinite": "une", "definite": "l'" },
    { "word": "Soleil", "meaning": "Sun", "plural": "Soleils", "indefinite": "un", "definite": "le" },
    { "word": "Lune", "meaning": "Moon", "plural": "Lunes", "indefinite": "une", "definite": "la" },
    { "word": "Nuage", "meaning": "Cloud", "plural": "Nuages", "indefinite": "un", "definite": "le" },
    { "word": "Pluie", "meaning": "Rain", "plural": "Pluies", "indefinite": "une", "definite": "la" },
    { "word": "Neige", "meaning": "Snow", "plural": "Neiges", "indefinite": "une", "definite": "la" },
    { "word": "Vent", "meaning": "Wind", "plural": "Vents", "indefinite": "un", "definite": "le" },
    { "word": "Température", "meaning": "Temperature", "plural": "Températures", "indefinite": "une", "definite": "la" },
    { "word": "Climat", "meaning": "Climate", "plural": "Climats", "indefinite": "un", "definite": "le" },
    { "word": "Plante", "meaning": "Plant", "plural": "Plantes", "indefinite": "une", "definite": "la" },
    { "word": "Forêt", "meaning": "Forest", "plural": "Forêts", "indefinite": "une", "definite": "la" }
];

module.exports = { frenchQuizData, frenchWordList };