// German Quiz Data
const germanQuizData = {
    A1: [
        { word: "Haus", options: ["Car", "Dog", "Tree", "House"], correct: "House" },
    { word: "Katze", options: ["Bird", "Dog", "Fish", "Cat"], correct: "Cat" },
    { word: "Auto", options: ["Bus", "Car", "Bike", "Train"], correct: "Car" },
    { word: "Tisch", options: ["Chair", "Door", "Window", "Table"], correct: "Table" },
    { word: "Hund", options: ["Fish", "Dog", "Bird", "Cat"], correct: "Dog" },
    { word: "Buch", options: ["Pen", "Bag", "Paper", "Book"], correct: "Book" },
    { word: "Baum", options: ["Bush", "Tree", "Flower", "Grass"], correct: "Tree" },
    { word: "Stuhl", options: ["Lamp", "Couch", "Table", "Chair"], correct: "Chair" },
    { word: "Fenster", options: ["Wall", "Roof", "Window", "Door"], correct: "Window" },
    { word: "Mensch", options: ["Animal", "Person", "Thing", "Plant"], correct: "Person" },
    { word: "Vogel", options: ["Bird", "Dog", "Cat", "Fish"], correct: "Bird" },
    { word: "Freund", options: ["Friend", "Enemy", "Teacher", "Student"], correct: "Friend" },
    { word: "Apfel", options: ["Apple", "Banana", "Grapes", "Orange"], correct: "Apple" },
    { word: "Stadt", options: ["City", "Country", "Village", "Town"], correct: "City" },
    { word: "Wasser", options: ["Water", "Juice", "Milk", "Tea"], correct: "Water" },
    { word: "Brot", options: ["Bread", "Cheese", "Butter", "Egg"], correct: "Bread" },
    { word: "Hund", options: ["Cat", "Dog", "Bird", "Fish"], correct: "Dog" },
    { word: "Blume", options: ["Flower", "Tree", "Bush", "Grass"], correct: "Flower" },
    { word: "Kind", options: ["Child", "Adult", "Teenager", "Baby"], correct: "Child" },
    { word: "Hemd", options: ["Shirt", "Pants", "Jacket", "Dress"], correct: "Shirt" },
    { word: "Bleistift", options: ["Pen", "Pencil", "Eraser", "Marker"], correct: "Pencil" },
    { word: "Schule", options: ["School", "University", "College", "Library"], correct: "School" },
    { word: "Tasche", options: ["Bag", "Shirt", "Jacket", "Hat"], correct: "Bag" },
    { word: "Garten", options: ["Garden", "House", "Street", "Park"], correct: "Garden" },
    { word: "Frau", options: ["Man", "Woman", "Child", "Boy"], correct: "Woman" },
    { word: "Mutter", options: ["Father", "Mother", "Brother", "Sister"], correct: "Mother" },
    { word: "Vater", options: ["Father", "Mother", "Brother", "Sister"], correct: "Father" },
    { word: "Sonne", options: ["Moon", "Star", "Sun", "Cloud"], correct: "Sun" },
    { word: "Licht", options: ["Light", "Dark", "Fire", "Lamp"], correct: "Light" },
    { word: "Tee", options: ["Tea", "Coffee", "Juice", "Water"], correct: "Tea" },
    { word: "Woche", options: ["Week", "Month", "Day", "Year"], correct: "Week" },
    { word: "Jahr", options: ["Month", "Week", "Day", "Year"], correct: "Year" },
    { word: "Hund", options: ["Dog", "Cat", "Bird", "Fish"], correct: "Dog" },
    { word: "Regen", options: ["Rain", "Snow", "Wind", "Cloud"], correct: "Rain" },
    { word: "Sommer", options: ["Winter", "Fall", "Spring", "Summer"], correct: "Summer" },
    { word: "Herbst", options: ["Fall", "Summer", "Spring", "Winter"], correct: "Fall" },
    { word: "Winter", options: ["Winter", "Spring", "Fall", "Summer"], correct: "Winter" },
    { word: "Frühling", options: ["Spring", "Winter", "Fall", "Summer"], correct: "Spring" },
    { word: "Berge", options: ["Mountains", "Seas", "Lakes", "Rivers"], correct: "Mountains" },
    { word: "Meer", options: ["Ocean", "Sea", "Lake", "River"], correct: "Sea" },
    { word: "Fluss", options: ["River", "Lake", "Ocean", "Sea"], correct: "River" },
    { word: "Straße", options: ["Street", "Park", "Road", "Alley"], correct: "Street" },
    { word: "Auto", options: ["Car", "Truck", "Bus", "Train"], correct: "Car" },
    { word: "Fahrrad", options: ["Bike", "Bus", "Car", "Train"], correct: "Bike" },
    { word: "Zug", options: ["Train", "Car", "Bike", "Bus"], correct: "Train" },
    { word: "Bus", options: ["Bus", "Car", "Bike", "Train"], correct: "Bus" },
    { word: "Flughafen", options: ["Airport", "Station", "Port", "Harbor"], correct: "Airport" },
    { word: "Hafen", options: ["Harbor", "Port", "Station", "Airport"], correct: "Harbor" },
    { word: "Bahnhof", options: ["Train station", "Bus station", "Airport", "Port"], correct: "Train station" },
    { word: "Geld", options: ["Money", "Coin", "Card", "Bill"], correct: "Money" },
    { word: "Taschenlampe", options: ["Flashlight", "Lamp", "Candle", "Torch"], correct: "Flashlight" },
    { word: "Schlüssel", options: ["Key", "Lock", "Door", "Window"], correct: "Key" },
    { word: "Telefon", options: ["Phone", "Computer", "Tablet", "Watch"], correct: "Phone" },
    { word: "Computer", options: ["Computer", "Phone", "Tablet", "Watch"], correct: "Computer" },
    { word: "Uhr", options: ["Clock", "Watch", "Phone", "Computer"], correct: "Watch" },
    { word: "Zeit", options: ["Time", "Date", "Week", "Month"], correct: "Time" },
    { word: "Montag", options: ["Monday", "Sunday", "Tuesday", "Wednesday"], correct: "Monday" },
    { word: "Dienstag", options: ["Tuesday", "Monday", "Wednesday", "Thursday"], correct: "Tuesday" },
    { word: "Mittwoch", options: ["Wednesday", "Tuesday", "Thursday", "Friday"], correct: "Wednesday" },
    { word: "Donnerstag", options: ["Thursday", "Friday", "Saturday", "Monday"], correct: "Thursday" },
    { word: "Freitag", options: ["Friday", "Saturday", "Sunday", "Thursday"], correct: "Friday" },
    { word: "Samstag", options: ["Saturday", "Sunday", "Friday", "Monday"], correct: "Saturday" },
    { word: "Sonntag", options: ["Sunday", "Saturday", "Friday", "Thursday"], correct: "Sunday" },
    { word: "Reise", options: ["Trip", "Journey", "Travel", "Flight"], correct: "Trip" },
    { word: "Flughafen", options: ["Airport", "Station", "Port", "Harbor"], correct: "Airport" },
    { word: "Hotel", options: ["Hotel", "Restaurant", "Cafe", "Bar"], correct: "Hotel" },
    { word: "Restaurant", options: ["Restaurant", "Cafe", "Bar", "Hotel"], correct: "Restaurant" },
    { word: "Cafe", options: ["Cafe", "Bar", "Hotel", "Restaurant"], correct: "Cafe" },
    { word: "Bar", options: ["Bar", "Cafe", "Hotel", "Restaurant"], correct: "Bar" },
    { word: "Essen", options: ["Food", "Drink", "Meal", "Snack"], correct: "Food" },
    { word: "Getränk", options: ["Drink", "Food", "Meal", "Snack"], correct: "Drink" },
    { word: "Kaffee", options: ["Coffee", "Tea", "Juice", "Water"], correct: "Coffee" },
    { word: "Tee", options: ["Tea", "Coffee", "Juice", "Water"], correct: "Tea" },
    { word: "Saft", options: ["Juice", "Water", "Coffee", "Tea"], correct: "Juice" },
    { word: "Wasser", options: ["Water", "Juice", "Milk", "Tea"], correct: "Water" },
    { word: "Blume", options: ["Tree", "Flower", "Bush", "Grass"], correct: "Flower" },
    { word: "Hemd", options: ["Shirt", "Pants", "Jacket", "Dress"], correct: "Shirt" },
    { word: "Bleistift", options: ["Pen", "Pencil", "Eraser", "Marker"], correct: "Pencil" },
    { word: "Schule", options: ["School", "University", "Library", "College"], correct: "School" },
    { word: "Tasche", options: ["Bag", "Jacket", "Shirt", "Hat"], correct: "Bag" },
    { word: "Garten", options: ["Park", "Garden", "Street", "House"], correct: "Garden" },
    { word: "Frau", options: ["Boy", "Woman", "Child", "Man"], correct: "Woman" },
    { word: "Mutter", options: ["Mother", "Father", "Brother", "Sister"], correct: "Mother" },
    { word: "Vater", options: ["Father", "Brother", "Sister", "Mother"], correct: "Father" },
    { word: "Sonne", options: ["Star", "Sun", "Moon", "Cloud"], correct: "Sun" },
    { word: "Licht", options: ["Lamp", "Light", "Dark", "Fire"], correct: "Light" },
    { word: "Tee", options: ["Tea", "Coffee", "Water", "Juice"], correct: "Tea" },
    { word: "Woche", options: ["Month", "Day", "Week", "Year"], correct: "Week" },
    { word: "Jahr", options: ["Month", "Year", "Day", "Week"], correct: "Year" },
    { word: "Regen", options: ["Rain", "Snow", "Wind", "Cloud"], correct: "Rain" },
    { word: "Sommer", options: ["Winter", "Summer", "Spring", "Fall"], correct: "Summer" },
    { word: "Herbst", options: ["Fall", "Winter", "Spring", "Summer"], correct: "Fall" },
    { word: "Winter", options: ["Winter", "Spring", "Fall", "Summer"], correct: "Winter" },
    { word: "Frühling", options: ["Spring", "Winter", "Fall", "Summer"], correct: "Spring" },
    { word: "Berge", options: ["Rivers", "Mountains", "Lakes", "Seas"], correct: "Mountains" },
    { word: "Meer", options: ["Sea", "Lake", "Ocean", "River"], correct: "Sea" },
    { word: "Fluss", options: ["Ocean", "Sea", "River", "Lake"], correct: "River" },
    { word: "Straße", options: ["Street", "Road", "Park", "Alley"], correct: "Street" },
    { word: "Zug", options: ["Car", "Bus", "Bike", "Train"], correct: "Train" },
    { word: "Bus", options: ["Car", "Train", "Bus", "Bike"], correct: "Bus" },
    { word: "Flughafen", options: ["Airport", "Harbor", "Port", "Station"], correct: "Airport" },
    { word: "Hafen", options: ["Station", "Airport", "Port", "Harbor"], correct: "Harbor" },
    { word: "Bahnhof", options: ["Train station", "Bus station", "Airport", "Port"], correct: "Train station" },
    { word: "Geld", options: ["Bill", "Card", "Money", "Coin"], correct: "Money" },
    { word: "Taschenlampe", options: ["Flashlight", "Candle", "Lamp", "Torch"], correct: "Flashlight" },
    { word: "Schlüssel", options: ["Lock", "Door", "Key", "Window"], correct: "Key" },
    { word: "Telefon", options: ["Phone", "Tablet", "Computer", "Watch"], correct: "Phone" },
    { word: "Computer", options: ["Phone", "Tablet", "Watch", "Computer"], correct: "Computer" },
    { word: "Uhr", options: ["Watch", "Clock", "Phone", "Computer"], correct: "Watch" },
    { word: "Zeit", options: ["Date", "Week", "Time", "Month"], correct: "Time" },
    { word: "Montag", options: ["Monday", "Tuesday", "Wednesday", "Thursday"], correct: "Monday" },
    { word: "Dienstag", options: ["Tuesday", "Wednesday", "Thursday", "Friday"], correct: "Tuesday" },
    { word: "Mittwoch", options: ["Wednesday", "Thursday", "Friday", "Tuesday"], correct: "Wednesday" },
    { word: "Donnerstag", options: ["Thursday", "Friday", "Saturday", "Monday"], correct: "Thursday" },
    { word: "Freitag", options: ["Friday", "Saturday", "Sunday", "Thursday"], correct: "Friday" },
    { word: "Samstag", options: ["Saturday", "Sunday", "Monday", "Friday"], correct: "Saturday" },
    { word: "Sonntag", options: ["Sunday", "Saturday", "Friday", "Thursday"], correct: "Sunday" },
    { word: "Reise", options: ["Journey", "Trip", "Travel", "Flight"], correct: "Trip" },
    { word: "Hotel", options: ["Cafe", "Restaurant", "Hotel", "Bar"], correct: "Hotel" },
    { word: "Restaurant", options: ["Hotel", "Cafe", "Restaurant", "Bar"], correct: "Restaurant" },
    { word: "Cafe", options: ["Bar", "Cafe", "Hotel", "Restaurant"], correct: "Cafe" },
    { word: "Bar", options: ["Restaurant", "Cafe", "Bar", "Hotel"], correct: "Bar" },
    { word: "Essen", options: ["Food", "Drink", "Meal", "Snack"], correct: "Food" },
    { word: "Getränk", options: ["Drink", "Food", "Meal", "Snack"], correct: "Drink" },
    { word: "Kaffee", options: ["Tea", "Coffee", "Juice", "Water"], correct: "Coffee" },
    { word: "Saft", options: ["Water", "Tea", "Juice", "Coffee"], correct: "Juice" },
    { word: "Wasser", options: ["Tea", "Coffee", "Water", "Milk"], correct: "Water" },
    { word: "Löffel", options: ["Spoon", "Fork", "Knife", "Plate"], correct: "Spoon" },
    { word: "Gabel", options: ["Fork", "Spoon", "Knife", "Plate"], correct: "Fork" },
    { word: "Messer", options: ["Knife", "Fork", "Spoon", "Plate"], correct: "Knife" },
    { word: "Teller", options: ["Plate", "Cup", "Glass", "Fork"], correct: "Plate" },
    { word: "Schokolade", options: ["Candy", "Chocolate", "Cake", "Fruit"], correct: "Chocolate" },
    { word: "Kuchen", options: ["Cake", "Pie", "Candy", "Cookie"], correct: "Cake" },
    { word: "Obst", options: ["Vegetables", "Fruit", "Meat", "Grain"], correct: "Fruit" },
    { word: "Gemüse", options: ["Meat", "Fruit", "Vegetables", "Grain"], correct: "Vegetables" },
    { word: "Fleisch", options: ["Grain", "Vegetables", "Fruit", "Meat"], correct: "Meat" },
    { word: "Reis", options: ["Grain", "Vegetables", "Meat", "Fruit"], correct: "Grain" },
    { word: "Käse", options: ["Cheese", "Milk", "Butter", "Yogurt"], correct: "Cheese" },
    { word: "Milch", options: ["Milk", "Cheese", "Yogurt", "Butter"], correct: "Milk" },
    { word: "Butter", options: ["Yogurt", "Milk", "Butter", "Cheese"], correct: "Butter" },
    { word: "Joghurt", options: ["Cheese", "Yogurt", "Milk", "Butter"], correct: "Yogurt" },
    { word: "Zucker", options: ["Salt", "Sugar", "Pepper", "Vinegar"], correct: "Sugar" },
    { word: "Salz", options: ["Sugar", "Vinegar", "Salt", "Pepper"], correct: "Salt" },
    { word: "Pfeffer", options: ["Salt", "Sugar", "Pepper", "Vinegar"], correct: "Pepper" },
    { word: "Essig", options: ["Vinegar", "Salt", "Sugar", "Pepper"], correct: "Vinegar" },
    { word: "Abend", options: ["Morning", "Night", "Afternoon", "Evening"], correct: "Evening" },
    { word: "Morgen", options: ["Morning", "Night", "Afternoon", "Evening"], correct: "Morning" },
    { word: "Nacht", options: ["Night", "Morning", "Afternoon", "Evening"], correct: "Night" },
    { word: "Nachmittag", options: ["Morning", "Afternoon", "Night", "Evening"], correct: "Afternoon" },
    { word: "Frühstück", options: ["Breakfast", "Dinner", "Lunch", "Snack"], correct: "Breakfast" },
    { word: "Mittagessen", options: ["Dinner", "Lunch", "Snack", "Breakfast"], correct: "Lunch" },
    { word: "Abendessen", options: ["Dinner", "Snack", "Lunch", "Breakfast"], correct: "Dinner" },
    { word: "Snack", options: ["Dinner", "Snack", "Lunch", "Breakfast"], correct: "Snack" }
    ],
    A2: [
        { word: "Freizeit", options: ["Leisure", "Work", "School", "Homework"], correct: "Leisure" },
    { word: "Arzt", options: ["Doctor", "Nurse", "Patient", "Teacher"], correct: "Doctor" },
    { word: "Krankenhaus", options: ["Hospital", "Clinic", "Pharmacy", "Doctor's office"], correct: "Hospital" },
    { word: "Zukunft", options: ["Past", "Future", "Present", "History"], correct: "Future" },
    { word: "Geschenk", options: ["Gift", "Toy", "Surprise", "Present"], correct: "Gift" },
    { word: "Gesundheit", options: ["Wealth", "Health", "Happiness", "Peace"], correct: "Health" },
    { word: "Büro", options: ["Office", "Home", "School", "Store"], correct: "Office" },
    { word: "Familie", options: ["Family", "Friends", "Neighbors", "Cousins"], correct: "Family" },
    { word: "Auto", options: ["Car", "Bike", "Bus", "Train"], correct: "Car" },
    { word: "Fahrrad", options: ["Bus", "Train", "Bike", "Car"], correct: "Bike" },
    { word: "Stadt", options: ["Town", "City", "Village", "Country"], correct: "City" },
    { word: "Dorf", options: ["Town", "City", "Village", "Country"], correct: "Village" },
    { word: "Essen", options: ["Food", "Drink", "Snack", "Meal"], correct: "Food" },
    { word: "Trinken", options: ["Eating", "Drinking", "Sleeping", "Running"], correct: "Drinking" },
    { word: "Zug", options: ["Bus", "Car", "Train", "Plane"], correct: "Train" },
    { word: "Flughafen", options: ["Harbor", "Airport", "Train station", "Bus stop"], correct: "Airport" },
    { word: "Reise", options: ["Journey", "Trip", "Vacation", "Work"], correct: "Trip" },
    { word: "Urlaub", options: ["Vacation", "Work", "Weekend", "Meeting"], correct: "Vacation" },
    { word: "Tiere", options: ["Animals", "Birds", "Fish", "Pets"], correct: "Animals" },
    { word: "Vogel", options: ["Bird", "Fish", "Cat", "Dog"], correct: "Bird" },
    { word: "Hund", options: ["Cat", "Dog", "Bird", "Fish"], correct: "Dog" },
    { word: "Katze", options: ["Dog", "Cat", "Bird", "Fish"], correct: "Cat" },
    { word: "Fisch", options: ["Bird", "Dog", "Fish", "Cat"], correct: "Fish" },
    { word: "Haus", options: ["House", "Car", "Apartment", "Building"], correct: "House" },
    { word: "Wohnung", options: ["House", "Flat", "Room", "Building"], correct: "Flat" },
    { word: "Zimmer", options: ["Kitchen", "Room", "Bathroom", "Living room"], correct: "Room" },
    { word: "Küche", options: ["Living room", "Kitchen", "Bedroom", "Bathroom"], correct: "Kitchen" },
    { word: "Badezimmer", options: ["Bedroom", "Living room", "Bathroom", "Kitchen"], correct: "Bathroom" },
    { word: "Balkon", options: ["Garden", "Balcony", "Kitchen", "Living room"], correct: "Balcony" },
    { word: "Garten", options: ["Park", "Garden", "Street", "Building"], correct: "Garden" },
    { word: "Straße", options: ["Street", "Building", "Park", "Road"], correct: "Street" },
    { word: "Brücke", options: ["Bridge", "Tunnel", "Road", "Street"], correct: "Bridge" },
    { word: "Weg", options: ["Road", "Path", "Tunnel", "Bridge"], correct: "Path" },
    { word: "Verkehr", options: ["Movement", "Traffic", "Road", "Cars"], correct: "Traffic" },
    { word: "Ampel", options: ["Traffic light", "Road sign", "Crosswalk", "Park"], correct: "Traffic light" },
    { word: "Fahrkarte", options: ["Ticket", "Pass", "Bus", "Card"], correct: "Ticket" },
    { word: "Rechnung", options: ["Invoice", "Receipt", "Receipt", "Bill"], correct: "Invoice" },
    { word: "Preis", options: ["Cost", "Price", "Value", "Amount"], correct: "Price" },
    { word: "Geld", options: ["Money", "Coin", "Credit", "Cash"], correct: "Money" },
    { word: "Bank", options: ["Office", "Bank", "Store", "Cafe"], correct: "Bank" },
    { word: "Supermarkt", options: ["Store", "Supermarket", "Mall", "Market"], correct: "Supermarket" },
    { word: "Laden", options: ["Shop", "Store", "Market", "Supermarket"], correct: "Shop" },
    { word: "Friseur", options: ["Barber", "Doctor", "Teacher", "Hairdresser"], correct: "Hairdresser" },
    { word: "Bäckerei", options: ["Supermarket", "Bakery", "Market", "Shop"], correct: "Bakery" },
    { word: "Apotheke", options: ["Pharmacy", "Supermarket", "Store", "Restaurant"], correct: "Pharmacy" },
    { word: "Restaurant", options: ["Cafe", "Bar", "Restaurant", "Bakery"], correct: "Restaurant" },
    { word: "Kaffee", options: ["Tea", "Coffee", "Juice", "Milk"], correct: "Coffee" },
    { word: "Tee", options: ["Milk", "Coffee", "Tea", "Water"], correct: "Tea" },
    { word: "Wasser", options: ["Juice", "Tea", "Water", "Milk"], correct: "Water" },
    { word: "Saft", options: ["Milk", "Juice", "Water", "Tea"], correct: "Juice" },
    { word: "Frühstück", options: ["Dinner", "Lunch", "Breakfast", "Snack"], correct: "Breakfast" },
    { word: "Mittagessen", options: ["Dinner", "Snack", "Breakfast", "Lunch"], correct: "Lunch" },
    { word: "Abendessen", options: ["Dinner", "Lunch", "Snack", "Breakfast"], correct: "Dinner" },
    { word: "Snack", options: ["Lunch", "Dinner", "Snack", "Breakfast"], correct: "Snack" },
    { word: "Küche", options: ["Living room", "Bathroom", "Kitchen", "Bedroom"], correct: "Kitchen" },
    { word: "Essen", options: ["Food", "Drink", "Snack", "Meal"], correct: "Food" },
    { word: "Buch", options: ["Pen", "Book", "Paper", "Notebook"], correct: "Book" },
    { word: "Stift", options: ["Pen", "Pencil", "Eraser", "Marker"], correct: "Pen" },
    { word: "Papier", options: ["Pen", "Paper", "Notebook", "Book"], correct: "Paper" },
    { word: "Tasche", options: ["Bag", "Shoes", "Shirt", "Hat"], correct: "Bag" },
    { word: "Schlüssel", options: ["Lock", "Window", "Key", "Door"], correct: "Key" },
    { word: "Schrank", options: ["Shelf", "Closet", "Table", "Chair"], correct: "Closet" },
    { word: "Fenster", options: ["Window", "Door", "Roof", "Wall"], correct: "Window" },
    { word: "Tür", options: ["Wall", "Roof", "Door", "Window"], correct: "Door" },
    { word: "Boden", options: ["Floor", "Wall", "Ceiling", "Roof"], correct: "Floor" },
    { word: "Wand", options: ["Ceiling", "Roof", "Wall", "Floor"], correct: "Wall" },
    { word: "Decke", options: ["Ceiling", "Wall", "Roof", "Floor"], correct: "Ceiling" },
    { word: "Woche", options: ["Month", "Week", "Year", "Day"], correct: "Week" },
    { word: "Tag", options: ["Week", "Month", "Day", "Year"], correct: "Day" },
    { word: "Monat", options: ["Year", "Day", "Week", "Month"], correct: "Month" },
    { word: "Jahr", options: ["Month", "Day", "Year", "Week"], correct: "Year" },
    { word: "Freund", options: ["Teacher", "Friend", "Family", "Relative"], correct: "Friend" },
    { word: "Nachbar", options: ["Neighbor", "Friend", "Family", "Relative"], correct: "Neighbor" },
    { word: "Lehrer", options: ["Student", "Teacher", "Friend", "Neighbor"], correct: "Teacher" },
    { word: "Schüler", options: ["Teacher", "Student", "Friend", "Neighbor"], correct: "Student" },
    { word: "Arbeit", options: ["Work", "Study", "Rest", "Play"], correct: "Work" },
    { word: "Pause", options: ["Break", "Class", "Work", "Lunch"], correct: "Break" },
    { word: "Handy", options: ["Phone", "Tablet", "Computer", "Laptop"], correct: "Phone" },
    { word: "Laptop", options: ["Phone", "Laptop", "Tablet", "Computer"], correct: "Laptop" },
    { word: "Tablet", options: ["Phone", "Tablet", "Laptop", "Computer"], correct: "Tablet" },
    { word: "Bäckerei", options: ["Shop", "Restaurant", "Bakery", "Supermarket"], correct: "Bakery" },
    { word: "Bibliothek", options: ["Cafe", "Library", "Park", "Shop"], correct: "Library" },
    { word: "Essen", options: ["Food", "Rest", "Drink", "Sleep"], correct: "Food" },
    { word: "Trinken", options: ["Walk", "Eat", "Drink", "Sleep"], correct: "Drink" },
    { word: "Frühstück", options: ["Snack", "Dinner", "Lunch", "Breakfast"], correct: "Breakfast" },
    { word: "Mittagessen", options: ["Snack", "Dinner", "Lunch", "Breakfast"], correct: "Lunch" },
    { word: "Abendessen", options: ["Snack", "Lunch", "Breakfast", "Dinner"], correct: "Dinner" },
    { word: "Tisch", options: ["Sofa", "Table", "Shelf", "Chair"], correct: "Table" },
    { word: "Stuhl", options: ["Couch", "Chair", "Sofa", "Table"], correct: "Chair" },
    { word: "Fenster", options: ["Door", "Floor", "Window", "Ceiling"], correct: "Window" },
    { word: "Tür", options: ["Window", "Door", "Ceiling", "Floor"], correct: "Door" },
    { word: "Boden", options: ["Wall", "Ceiling", "Floor", "Roof"], correct: "Floor" },
    { word: "Decke", options: ["Wall", "Ceiling", "Floor", "Roof"], correct: "Ceiling" },
    { word: "Himmel", options: ["Moon", "Cloud", "Earth", "Sky"], correct: "Sky" },
    { word: "Erde", options: ["Sky", "Moon", "Earth", "Cloud"], correct: "Earth" },
    { word: "Wasser", options: ["Water", "Earth", "Fire", "Air"], correct: "Water" },
    { word: "Feuer", options: ["Earth", "Water", "Fire", "Air"], correct: "Fire" },
    { word: "Luft", options: ["Air", "Earth", "Fire", "Water"], correct: "Air" },
    { word: "Blume", options: ["Bush", "Tree", "Grass", "Flower"], correct: "Flower" },
    { word: "Baum", options: ["Flower", "Bush", "Tree", "Grass"], correct: "Tree" },
    { word: "Gras", options: ["Bush", "Grass", "Tree", "Flower"], correct: "Grass" },
    { word: "Bus", options: ["Train", "Plane", "Bus", "Car"], correct: "Bus" },
    { word: "Fahrrad", options: ["Train", "Bike", "Car", "Bus"], correct: "Bike" },
    { word: "Taxi", options: ["Train", "Taxi", "Car", "Bus"], correct: "Taxi" },
    { word: "Flughafen", options: ["Train station", "Harbor", "Bus stop", "Airport"], correct: "Airport" },
    { word: "Bahnhof", options: ["Train station", "Bus stop", "Harbor", "Airport"], correct: "Train station" },
    { word: "Schiff", options: ["Car", "Bus", "Boat", "Train"], correct: "Boat" },
    { word: "Hotel", options: ["Shop", "Park", "Hotel", "Museum"], correct: "Hotel" },
    { word: "Restaurant", options: ["Hotel", "Museum", "Restaurant", "Park"], correct: "Restaurant" },
    { word: "Kino", options: ["Cinema", "Museum", "Restaurant", "Theater"], correct: "Cinema" },
    { word: "Theater", options: ["Museum", "Theater", "Cinema", "Restaurant"], correct: "Theater" },
    { word: "Park", options: ["Museum", "Restaurant", "Theater", "Park"], correct: "Park" },
    { word: "Laden", options: ["Park", "Shop", "Hotel", "Museum"], correct: "Shop" },
    { word: "Straße", options: ["Street", "Bus", "Train", "Car"], correct: "Street" },
    { word: "Brücke", options: ["Tunnel", "Street", "Bridge", "House"], correct: "Bridge" },
    { word: "Weg", options: ["Path", "Street", "Bridge", "Road"], correct: "Path" },
    { word: "Verkehr", options: ["Road", "Traffic", "Cars", "Street"], correct: "Traffic" },
    { word: "Ampel", options: ["Street", "Crosswalk", "Sign", "Traffic light"], correct: "Traffic light" },
    { word: "Schule", options: ["University", "School", "Library", "College"], correct: "School" },
    { word: "Lehrer", options: ["Student", "Teacher", "Parent", "Principal"], correct: "Teacher" },
    { word: "Schüler", options: ["Parent", "Teacher", "Student", "Friend"], correct: "Student" },
    { word: "Tafel", options: ["Desk", "Board", "Table", "Chair"], correct: "Board" }
    ],
    B1: [
        { word: "Abenteuer", options: ["Adventure", "Vacation", "Journey", "Holiday"], correct: "Adventure" },
    { word: "Verabredung", options: ["Appointment", "Meeting", "Call", "Dinner"], correct: "Appointment" },
    { word: "Erfahrung", options: ["Knowledge", "Experience", "Learning", "Skill"], correct: "Experience" },
    { word: "Welt", options: ["Earth", "World", "Moon", "Sky"], correct: "World" },
    { word: "Gesellschaft", options: ["Society", "Culture", "Community", "Nation"], correct: "Society" },
    { word: "Zukunft", options: ["Past", "Present", "Future", "Moment"], correct: "Future" },
    { word: "Vergangenheit", options: ["Future", "Past", "Present", "History"], correct: "Past" },
    { word: "Gegenteil", options: ["Opposite", "Similar", "Same", "Different"], correct: "Opposite" },
    { word: "Natur", options: ["Nature", "Environment", "Planet", "World"], correct: "Nature" },
    { word: "Stimmung", options: ["Mood", "Tone", "Feel", "Spirit"], correct: "Mood" },
    { word: "Gefühl", options: ["Feeling", "Thought", "Idea", "Mood"], correct: "Feeling" },
    { word: "Problem", options: ["Solution", "Challenge", "Problem", "Opportunity"], correct: "Problem" },
    { word: "Lösung", options: ["Problem", "Answer", "Solution", "Question"], correct: "Solution" },
    { word: "Wirtschaft", options: ["Economy", "Trade", "Money", "Bank"], correct: "Economy" },
    { word: "Arbeitnehmer", options: ["Employee", "Employer", "Worker", "Owner"], correct: "Employee" },
    { word: "Arbeitsplatz", options: ["Office", "Workplace", "Store", "Factory"], correct: "Workplace" },
    { word: "Fähigkeit", options: ["Skill", "Talent", "Experience", "Ability"], correct: "Skill" },
    { word: "Woche", options: ["Day", "Month", "Week", "Year"], correct: "Week" },
    { word: "Jahr", options: ["Day", "Week", "Month", "Year"], correct: "Year" },
    { word: "Monat", options: ["Day", "Week", "Month", "Year"], correct: "Month" },
    { word: "Freundschaft", options: ["Relationship", "Friendship", "Companionship", "Love"], correct: "Friendship" },
    { word: "Bekanntschaft", options: ["Friend", "Acquaintance", "Companion", "Relative"], correct: "Acquaintance" },
    { word: "Kundendienst", options: ["Customer service", "Support", "Sales", "Store"], correct: "Customer service" },
    { word: "Gespräch", options: ["Discussion", "Conversation", "Talk", "Meeting"], correct: "Conversation" },
    { word: "Einladung", options: ["Invitation", "Request", "Meeting", "Call"], correct: "Invitation" },
    { word: "Ereignis", options: ["Event", "Occurrence", "Meeting", "Action"], correct: "Event" },
    { word: "Fehler", options: ["Mistake", "Problem", "Solution", "Success"], correct: "Mistake" },
    { word: "Herausforderung", options: ["Challenge", "Problem", "Solution", "Task"], correct: "Challenge" },
    { word: "Erfolg", options: ["Achievement", "Failure", "Success", "Task"], correct: "Success" },
    { word: "Hoffnung", options: ["Fear", "Hope", "Wish", "Desire"], correct: "Hope" },
    { word: "Glaube", options: ["Belief", "Faith", "Religion", "Hope"], correct: "Faith" },
    { word: "Wissen", options: ["Knowledge", "Thought", "Feeling", "Idea"], correct: "Knowledge" },
    { word: "Lernen", options: ["Learning", "Teaching", "Studying", "Training"], correct: "Learning" },
    { word: "Schwierigkeit", options: ["Ease", "Difficulty", "Challenge", "Problem"], correct: "Difficulty" },
    { word: "Prozess", options: ["Process", "Task", "Journey", "Action"], correct: "Process" },
    { word: "Erklärung", options: ["Explanation", "Story", "Definition", "Speech"], correct: "Explanation" },
    { word: "Ansicht", options: ["View", "Perspective", "Opinion", "Belief"], correct: "Opinion" },
    { word: "Aussage", options: ["Statement", "Message", "Answer", "Idea"], correct: "Statement" },
    { word: "Bedeutung", options: ["Meaning", "Answer", "Idea", "Statement"], correct: "Meaning" },
    { word: "Zustand", options: ["State", "Condition", "Place", "Moment"], correct: "Condition" },
    { word: "Technologie", options: ["Science", "Technology", "Innovation", "Invention"], correct: "Technology" },
    { word: "Entwicklung", options: ["Growth", "Development", "Process", "Change"], correct: "Development" },
    { word: "Fortschritt", options: ["Progress", "Development", "Growth", "Success"], correct: "Progress" },
    { word: "Wahl", options: ["Choice", "Option", "Decision", "Selection"], correct: "Choice" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Opinion", "Statement"], correct: "Decision" },
    { word: "Verantwortung", options: ["Responsibility", "Duty", "Obligation", "Task"], correct: "Responsibility" },
    { word: "Möglichkeit", options: ["Opportunity", "Possibility", "Chance", "Option"], correct: "Opportunity" },
    { word: "Energie", options: ["Power", "Energy", "Force", "Strength"], correct: "Energy" },
    { word: "Unterschied", options: ["Similarity", "Difference", "Contrast", "Match"], correct: "Difference" },
    { word: "Geschenk", options: ["Present", "Gift", "Toy", "Card"], correct: "Gift" },
    { word: "Einkaufen", options: ["Shopping", "Eating", "Walking", "Running"], correct: "Shopping" },
    { word: "Verhalten", options: ["Behavior", "Action", "Movement", "Response"], correct: "Behavior" },
    { word: "Unfall", options: ["Accident", "Event", "Problem", "Journey"], correct: "Accident" },
    { word: "Erholung", options: ["Rest", "Exercise", "Work", "Leisure"], correct: "Rest" },
    { word: "Geld", options: ["Money", "Paper", "Card", "Value"], correct: "Money" },
    { word: "Kreditkarte", options: ["Debit card", "Cash", "Credit card", "Gift card"], correct: "Credit card" },
    { word: "Rechnung", options: ["Receipt", "Bill", "Order", "Invoice"], correct: "Bill" },
    { word: "Vertrag", options: ["Agreement", "Contract", "Promise", "Deal"], correct: "Contract" },
    { word: "Adresse", options: ["Location", "Street", "Address", "Place"], correct: "Address" },
    { word: "Stadt", options: ["Town", "Village", "City", "Region"], correct: "City" },
    { word: "Land", options: ["Country", "Region", "City", "State"], correct: "Country" },
    { word: "Flughafen", options: ["Bus station", "Airport", "Train station", "Harbor"], correct: "Airport" },
    { word: "Parken", options: ["Walking", "Running", "Parking", "Cycling"], correct: "Parking" },
    { word: "Verkehrsmittel", options: ["Transport", "Road", "Vehicle", "Journey"], correct: "Transport" },
    { word: "Bus", options: ["Car", "Bike", "Train", "Bus"], correct: "Bus" },
    { word: "Zug", options: ["Train", "Car", "Taxi", "Bus"], correct: "Train" },
    { word: "Fahrrad", options: ["Bus", "Bike", "Car", "Train"], correct: "Bike" },
    { word: "Flugzeug", options: ["Plane", "Boat", "Bus", "Train"], correct: "Plane" },
    { word: "Reise", options: ["Journey", "Travel", "Trip", "Adventure"], correct: "Travel" },
    { word: "Urlaub", options: ["Vacation", "Business trip", "Trip", "Holiday"], correct: "Vacation" },
    { word: "Freizeit", options: ["Work", "Leisure", "Rest", "Study"], correct: "Leisure" },
    { word: "Sport", options: ["Exercise", "Sport", "Running", "Gym"], correct: "Sport" },
    { word: "Gesundheit", options: ["Health", "Body", "Energy", "Fitness"], correct: "Health" },
    { word: "Arzt", options: ["Doctor", "Nurse", "Pharmacist", "Patient"], correct: "Doctor" },
    { word: "Krankenhaus", options: ["Hospital", "Clinic", "Pharmacy", "Ambulance"], correct: "Hospital" },
    { word: "Medizin", options: ["Medicine", "Health", "Treatment", "Prescription"], correct: "Medicine" },
    { word: "Schmerzen", options: ["Pain", "Treatment", "Symptom", "Illness"], correct: "Pain" },
    { word: "Symptom", options: ["Sign", "Condition", "Symptom", "Illness"], correct: "Symptom" },
    { word: "Erkältung", options: ["Cold", "Cough", "Flu", "Headache"], correct: "Cold" },
    { word: "Husten", options: ["Cough", "Cold", "Pain", "Fever"], correct: "Cough" },
    { word: "Fieber", options: ["Fever", "Pain", "Cold", "Cough"], correct: "Fever" },
    { word: "Tabelle", options: ["Chart", "Table", "Picture", "Graph"], correct: "Table" },
    { word: "Buch", options: ["Magazine", "Book", "Novel", "Newspaper"], correct: "Book" },
    { word: "Zeitschrift", options: ["Magazine", "Book", "Article", "Newspaper"], correct: "Magazine" },
    { word: "Zeitung", options: ["Book", "Journal", "Magazine", "Newspaper"], correct: "Newspaper" },
    { word: "Computer", options: ["Smartphone", "Tablet", "Laptop", "Computer"], correct: "Computer" },
    { word: "Handy", options: ["Tablet", "Smartphone", "Laptop", "Computer"], correct: "Smartphone" },
    { word: "Laptop", options: ["Tablet", "Computer", "Laptop", "Smartphone"], correct: "Laptop" },
    { word: "Internet", options: ["Network", "System", "Internet", "Connection"], correct: "Internet" },
    { word: "Website", options: ["Page", "Website", "Blog", "Forum"], correct: "Website" },
    { word: "E-Mail", options: ["Message", "Call", "Text", "Email"], correct: "Email" },
    { word: "Telefon", options: ["Phone", "Laptop", "Tablet", "Computer"], correct: "Phone" },
    { word: "Text", options: ["Text", "Message", "Article", "Letter"], correct: "Text" },
    { word: "Nachricht", options: ["News", "Message", "Text", "Call"], correct: "Message" },
    { word: "Foto", options: ["Picture", "Image", "Photo", "Painting"], correct: "Photo" },
    { word: "Video", options: ["Film", "Picture", "Video", "Clip"], correct: "Video" },
    { word: "Filme", options: ["Music", "Movies", "Video", "News"], correct: "Movies" },
    { word: "Musik", options: ["Movies", "Music", "Video", "Sound"], correct: "Music" },
    { word: "Lied", options: ["Song", "Dance", "Music", "Voice"], correct: "Song" },
    { word: "Tanz", options: ["Song", "Dance", "Performance", "Rhythm"], correct: "Dance" },
    { word: "Theater", options: ["Cinema", "Theater", "Concert", "Performance"], correct: "Theater" },
    { word: "Konzerte", options: ["Concert", "Performance", "Show", "Event"], correct: "Concert" },
    { word: "Messe", options: ["Fair", "Exhibition", "Trade", "Event"], correct: "Fair" }
    ],
    B2: [
        { word: "Verantwortung", options: ["Responsibility", "Duty", "Task", "Obligation"], correct: "Responsibility" },
    { word: "Abwechslung", options: ["Variety", "Change", "Difference", "Opportunity"], correct: "Variety" },
    { word: "Aussicht", options: ["View", "Option", "Prospect", "Outlook"], correct: "View" },
    { word: "Fähigkeit", options: ["Ability", "Capability", "Skill", "Talent"], correct: "Ability" },
    { word: "Herausforderung", options: ["Challenge", "Opportunity", "Obstacle", "Problem"], correct: "Challenge" },
    { word: "Zustimmung", options: ["Consent", "Agreement", "Disagreement", "Refusal"], correct: "Consent" },
    { word: "Fortschritt", options: ["Progress", "Development", "Change", "Movement"], correct: "Progress" },
    { word: "Wachstum", options: ["Growth", "Development", "Progress", "Expansion"], correct: "Growth" },
    { word: "Vertrauen", options: ["Trust", "Faith", "Reliability", "Confidence"], correct: "Trust" },
    { word: "Selbstbewusstsein", options: ["Self-awareness", "Confidence", "Pride", "Self-esteem"], correct: "Confidence" },
    { word: "Unterschied", options: ["Difference", "Variation", "Similarity", "Contrast"], correct: "Difference" },
    { word: "Ziel", options: ["Goal", "Aim", "Objective", "Target"], correct: "Goal" },
    { word: "Bedingung", options: ["Condition", "Requirement", "Provision", "Circumstance"], correct: "Condition" },
    { word: "Verhandlung", options: ["Negotiation", "Discussion", "Debate", "Agreement"], correct: "Negotiation" },
    { word: "Abschluss", options: ["Conclusion", "Completion", "Finish", "Result"], correct: "Conclusion" },
    { word: "Wirkung", options: ["Effect", "Impact", "Result", "Outcome"], correct: "Effect" },
    { word: "Erscheinung", options: ["Appearance", "Phenomenon", "Occurrence", "Sight"], correct: "Appearance" },
    { word: "Zufriedenheit", options: ["Contentment", "Satisfaction", "Happiness", "Fulfillment"], correct: "Satisfaction" },
    { word: "Einfluss", options: ["Influence", "Effect", "Impact", "Control"], correct: "Influence" },
    { word: "Gefühl", options: ["Feeling", "Emotion", "Sense", "Thought"], correct: "Feeling" },
    { word: "Bedeutung", options: ["Meaning", "Importance", "Significance", "Sense"], correct: "Meaning" },
    { word: "Wert", options: ["Value", "Worth", "Cost", "Price"], correct: "Value" },
    { word: "Veränderung", options: ["Change", "Alteration", "Transformation", "Shift"], correct: "Change" },
    { word: "Entwicklung", options: ["Development", "Evolution", "Progress", "Change"], correct: "Development" },
    { word: "Anpassung", options: ["Adjustment", "Adaptation", "Modification", "Change"], correct: "Adjustment" },
    { word: "Gleichgewicht", options: ["Balance", "Equality", "Stability", "Proportion"], correct: "Balance" },
    { word: "Reaktion", options: ["Reaction", "Response", "Reply", "Action"], correct: "Reaction" },
    { word: "Anerkennung", options: ["Recognition", "Appreciation", "Acknowledgment", "Respect"], correct: "Recognition" },
    { word: "Bestätigung", options: ["Confirmation", "Approval", "Affirmation", "Verification"], correct: "Confirmation" },
    { word: "Erfolg", options: ["Success", "Achievement", "Victory", "Win"], correct: "Success" },
    { word: "Misserfolg", options: ["Failure", "Defeat", "Loss", "Mistake"], correct: "Failure" },
    { word: "Verhältnis", options: ["Relationship", "Ratio", "Proportion", "Link"], correct: "Relationship" },
    { word: "Zweck", options: ["Purpose", "Objective", "Goal", "Use"], correct: "Purpose" },
    { word: "Möglichkeit", options: ["Possibility", "Opportunity", "Chance", "Option"], correct: "Possibility" },
    { word: "Einschränkung", options: ["Restriction", "Limitation", "Constrain", "Limitation"], correct: "Restriction" },
    { word: "Neugier", options: ["Curiosity", "Interest", "Wonder", "Desire"], correct: "Curiosity" },
    { word: "Besonderheit", options: ["Specialty", "Particularity", "Uniqueness", "Feature"], correct: "Specialty" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Option", "Judgment"], correct: "Decision" },
    { word: "Wahrheit", options: ["Truth", "Fact", "Reality", "Accuracy"], correct: "Truth" },
    { word: "Lüge", options: ["Lie", "Truth", "Fact", "Statement"], correct: "Lie" },
    { word: "Zielgruppe", options: ["Audience", "Target group", "Market", "Group"], correct: "Target group" },
    { word: "Umgang", options: ["Treatment", "Handling", "Interaction", "Communication"], correct: "Interaction" },
    { word: "Störung", options: ["Disruption", "Disturbance", "Interruption", "Problem"], correct: "Disruption" },
    { word: "Bedeutung", options: ["Meaning", "Importance", "Value", "Significance"], correct: "Meaning" },
    { word: "Betrieb", options: ["Operation", "Business", "Factory", "Company"], correct: "Business" },
    { word: "Wirtschaft", options: ["Economy", "Business", "Industry", "Trade"], correct: "Economy" },
    { word: "Verhalten", options: ["Behavior", "Conduct", "Action", "Reaction"], correct: "Behavior" },
    { word: "Aufgabe", options: ["Task", "Assignment", "Mission", "Duty"], correct: "Task" },
    { word: "Abteilung", options: ["Department", "Section", "Division", "Unit"], correct: "Department" },
    { word: "Forschung", options: ["Research", "Study", "Experiment", "Analysis"], correct: "Research" },
    { word: "Verwendung", options: ["Usage", "Use", "Application", "Function"], correct: "Use" },
    { word: "Erklärung", options: ["Explanation", "Definition", "Clarification", "Statement"], correct: "Explanation" },
    { word: "Untersuchung", options: ["Investigation", "Examination", "Analysis", "Survey"], correct: "Investigation" },
    { word: "Voraussetzung", options: ["Requirement", "Condition", "Prerequisite", "Need"], correct: "Requirement" },
    { word: "Vereinbarung", options: ["Agreement", "Contract", "Deal", "Understanding"], correct: "Agreement" },
    { word: "Kondition", options: ["Condition", "State", "State of mind", "Situation"], correct: "Condition" },
    { word: "Begriff", options: ["Term", "Concept", "Idea", "Word"], correct: "Term" },
    { word: "Aussage", options: ["Statement", "Claim", "Argument", "Fact"], correct: "Statement" },
    { word: "Verwendung", options: ["Usage", "Application", "Use", "Function"], correct: "Usage" },
    { word: "Erlaubnis", options: ["Permission", "License", "Approval", "Consent"], correct: "Permission" },
    { word: "Überzeugung", options: ["Conviction", "Belief", "Opinion", "View"], correct: "Conviction" },
    { word: "Mangel", options: ["Deficit", "Lack", "Shortage", "Absence"], correct: "Lack" },
    { word: "Vorbereitung", options: ["Preparation", "Plan", "Arrangement", "Readiness"], correct: "Preparation" },
    { word: "Beteiligung", options: ["Participation", "Involvement", "Contribution", "Engagement"], correct: "Participation" },
    { word: "Aussicht", options: ["View", "Outlook", "Perspective", "Prospect"], correct: "View" },
    { word: "Verhalten", options: ["Behavior", "Conduct", "Performance", "Action"], correct: "Behavior" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Need"], correct: "Prerequisite" },
    { word: "Geschenk", options: ["Gift", "Present", "Offer", "Reward"], correct: "Gift" },
    { word: "Erklärung", options: ["Explanation", "Clarification", "Statement", "Reason"], correct: "Explanation" },
    { word: "Gegenteil", options: ["Opposite", "Contradiction", "Counterpart", "Reverse"], correct: "Opposite" },
    { word: "Ergebnis", options: ["Result", "Outcome", "Conclusion", "Effect"], correct: "Result" },
    { word: "Zustimmung", options: ["Consent", "Approval", "Agreement", "Acknowledgment"], correct: "Consent" },
    { word: "Kritik", options: ["Criticism", "Review", "Feedback", "Analysis"], correct: "Criticism" },
    { word: "Vermögen", options: ["Wealth", "Asset", "Fortune", "Property"], correct: "Wealth" },
    { word: "Erfolg", options: ["Success", "Achievement", "Victory", "Win"], correct: "Success" },
    { word: "Verhältnis", options: ["Relationship", "Proportion", "Ratio", "Connection"], correct: "Relationship" },
    { word: "Betrieb", options: ["Company", "Business", "Operation", "Firm"], correct: "Business" },
    { word: "Zweck", options: ["Purpose", "Aim", "Objective", "Goal"], correct: "Purpose" },
    { word: "Unterschied", options: ["Difference", "Distinction", "Variation", "Divergence"], correct: "Difference" },
    { word: "Verhandlung", options: ["Negotiation", "Deal", "Discussion", "Bargaining"], correct: "Negotiation" },
    { word: "Beteiligung", options: ["Involvement", "Participation", "Contribution", "Share"], correct: "Involvement" },
    { word: "Überraschung", options: ["Surprise", "Astonishment", "Wonder", "Shock"], correct: "Surprise" },
    { word: "Sicherheit", options: ["Safety", "Security", "Protection", "Assurance"], correct: "Safety" },
    { word: "Lösung", options: ["Solution", "Answer", "Resolution", "Fix"], correct: "Solution" },
    { word: "Kompromiss", options: ["Compromise", "Agreement", "Deal", "Settlement"], correct: "Compromise" },
    { word: "Beitrag", options: ["Contribution", "Input", "Share", "Offer"], correct: "Contribution" },
    { word: "Erwartung", options: ["Expectation", "Anticipation", "Hope", "Assumption"], correct: "Expectation" },
    { word: "Schwierigkeit", options: ["Difficulty", "Challenge", "Obstacle", "Problem"], correct: "Difficulty" },
    { word: "Voraussetzung", options: ["Condition", "Prerequisite", "Requirement", "Necessity"], correct: "Condition" },
    { word: "Verhalten", options: ["Behavior", "Conduct", "Performance", "Reaction"], correct: "Behavior" },
    { word: "Leben", options: ["Life", "Existence", "Living", "Being"], correct: "Life" },
    { word: "Chance", options: ["Chance", "Opportunity", "Possibility", "Shot"], correct: "Chance" },
    { word: "Erfahrung", options: ["Experience", "Knowledge", "Skill", "Understanding"], correct: "Experience" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Judgment", "Verdict"], correct: "Decision" },
    { word: "Angabe", options: ["Statement", "Indication", "Detail", "Information"], correct: "Statement" },
    { word: "Gleichgewicht", options: ["Balance", "Stability", "Equality", "Equilibrium"], correct: "Balance" },
    { word: "Konkurrenz", options: ["Competition", "Rivalry", "Opposition", "Contest"], correct: "Competition" },
    { word: "Anforderung", options: ["Requirement", "Demand", "Condition", "Request"], correct: "Requirement" },
    { word: "Verlust", options: ["Loss", "Defeat", "Drop", "Failure"], correct: "Loss" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Happiness", "Fulfillment"], correct: "Satisfaction" },
    { word: "Ergebnis", options: ["Outcome", "Result", "Conclusion", "Effect"], correct: "Outcome" },
    { word: "Abstimmung", options: ["Vote", "Poll", "Agreement", "Survey"], correct: "Vote" },
    { word: "Ansicht", options: ["View", "Opinion", "Perspective", "Attitude"], correct: "View" },
    { word: "Vertrauen", options: ["Trust", "Reliance", "Faith", "Confidence"], correct: "Trust" },
    { word: "Unabhängigkeit", options: ["Independence", "Freedom", "Autonomy", "Sovereignty"], correct: "Independence" },
    { word: "Anerkennung", options: ["Recognition", "Acknowledgment", "Appreciation", "Validation"], correct: "Recognition" },
    { word: "Überzeugung", options: ["Belief", "Conviction", "View", "Idea"], correct: "Belief" },
    { word: "Verbindung", options: ["Connection", "Link", "Relation", "Bond"], correct: "Connection" },
    { word: "Ablauf", options: ["Process", "Procedure", "Flow", "Course"], correct: "Process" },
    { word: "Kombination", options: ["Combination", "Blend", "Mixture", "Union"], correct: "Combination" }
    ],
    C1: [
        { word: "Herausforderung", options: ["Challenge", "Obligation", "Task", "Mission"], correct: "Challenge" },
    { word: "Verantwortung", options: ["Responsibility", "Duty", "Task", "Obligation"], correct: "Responsibility" },
    { word: "Zusammenhang", options: ["Context", "Connection", "Relation", "Link"], correct: "Context" },
    { word: "Komplexität", options: ["Complexity", "Difficulty", "Challenge", "Intricacy"], correct: "Complexity" },
    { word: "Verständnis", options: ["Understanding", "Insight", "Comprehension", "Knowledge"], correct: "Understanding" },
    { word: "Erkenntnis", options: ["Insight", "Understanding", "Realization", "Knowledge"], correct: "Insight" },
    { word: "Entwicklung", options: ["Development", "Growth", "Evolution", "Progress"], correct: "Development" },
    { word: "Bedeutung", options: ["Meaning", "Importance", "Significance", "Value"], correct: "Meaning" },
    { word: "Wirkung", options: ["Effect", "Impact", "Result", "Outcome"], correct: "Effect" },
    { word: "Fähigkeit", options: ["Ability", "Skill", "Capability", "Competence"], correct: "Ability" },
    { word: "Verhalten", options: ["Behavior", "Conduct", "Action", "Manner"], correct: "Behavior" },
    { word: "Verhandlung", options: ["Negotiation", "Discussion", "Deal", "Agreement"], correct: "Negotiation" },
    { word: "Möglichkeiten", options: ["Possibilities", "Opportunities", "Options", "Chances"], correct: "Possibilities" },
    { word: "Einsicht", options: ["Insight", "Understanding", "Viewpoint", "Perspective"], correct: "Insight" },
    { word: "Zukunft", options: ["Future", "Destiny", "Prospect", "Time ahead"], correct: "Future" },
    { word: "Kompetenz", options: ["Competence", "Ability", "Skill", "Qualification"], correct: "Competence" },
    { word: "Verständlichkeit", options: ["Clarity", "Understandability", "Simplicity", "Accessibility"], correct: "Clarity" },
    { word: "Schwierigkeit", options: ["Difficulty", "Complication", "Problem", "Challenge"], correct: "Difficulty" },
    { word: "Bedingung", options: ["Condition", "Requirement", "Clause", "Term"], correct: "Condition" },
    { word: "Sichtweise", options: ["Point of view", "Opinion", "Outlook", "Perspective"], correct: "Point of view" },
    { word: "Anforderungen", options: ["Requirements", "Demands", "Conditions", "Expectations"], correct: "Requirements" },
    { word: "Erfahrung", options: ["Experience", "Knowledge", "Skill", "Competence"], correct: "Experience" },
    { word: "Hintergrund", options: ["Background", "Context", "Foundation", "Cause"], correct: "Background" },
    { word: "Prozess", options: ["Process", "Procedure", "System", "Method"], correct: "Process" },
    { word: "Zustimmung", options: ["Consent", "Approval", "Agreement", "Confirmation"], correct: "Consent" },
    { word: "Hoffnung", options: ["Hope", "Aspiration", "Expectation", "Desire"], correct: "Hope" },
    { word: "Kritik", options: ["Criticism", "Review", "Evaluation", "Feedback"], correct: "Criticism" },
    { word: "Beteiligung", options: ["Participation", "Involvement", "Contribution", "Share"], correct: "Participation" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Judgment", "Verdict"], correct: "Decision" },
    { word: "Erklärung", options: ["Explanation", "Statement", "Clarification", "Definition"], correct: "Explanation" },
    { word: "Möglichkeit", options: ["Possibility", "Opportunity", "Chance", "Option"], correct: "Possibility" },
    { word: "Bestätigung", options: ["Confirmation", "Validation", "Approval", "Affirmation"], correct: "Confirmation" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Fulfillment", "Pleasure"], correct: "Satisfaction" },
    { word: "Nachhaltigkeit", options: ["Sustainability", "Endurance", "Longevity", "Viability"], correct: "Sustainability" },
    { word: "Ziel", options: ["Goal", "Target", "Aim", "Objective"], correct: "Goal" },
    { word: "Verbindung", options: ["Connection", "Link", "Relation", "Bond"], correct: "Connection" },
    { word: "Kombination", options: ["Combination", "Mix", "Union", "Blend"], correct: "Combination" },
    { word: "Ergebnis", options: ["Result", "Outcome", "Conclusion", "Effect"], correct: "Result" },
    { word: "Fortschritt", options: ["Progress", "Advancement", "Development", "Improvement"], correct: "Progress" },
    { word: "Schlussfolgerung", options: ["Conclusion", "Inference", "Deduction", "Result"], correct: "Conclusion" },
    { word: "Mangel", options: ["Lack", "Deficit", "Shortage", "Absence"], correct: "Lack" },
    { word: "Aussicht", options: ["View", "Prospect", "Outlook", "Perspective"], correct: "View" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Term"], correct: "Prerequisite" },
    { word: "Vertrauen", options: ["Trust", "Confidence", "Reliance", "Belief"], correct: "Trust" },
    { word: "Entwicklung", options: ["Development", "Growth", "Evolution", "Progress"], correct: "Development" },
    { word: "Sicherheit", options: ["Safety", "Security", "Protection", "Certainty"], correct: "Safety" },
    { word: "Einfluss", options: ["Influence", "Impact", "Effect", "Power"], correct: "Influence" },
    { word: "Erfüllung", options: ["Fulfillment", "Satisfaction", "Completion", "Achievement"], correct: "Fulfillment" },
    { word: "Verzögerung", options: ["Delay", "Postponement", "Interruption", "Deferral"], correct: "Delay" },
    { word: "Vorbereitung", options: ["Preparation", "Readiness", "Setup", "Planning"], correct: "Preparation" },
    { word: "Widerstand", options: ["Resistance", "Opposition", "Defiance", "Resilience"], correct: "Resistance" },
    { word: "Abstimmung", options: ["Voting", "Poll", "Agreement", "Approval"], correct: "Voting" },
    { word: "Bewertung", options: ["Evaluation", "Assessment", "Rating", "Review"], correct: "Evaluation" },
    { word: "Verkehr", options: ["Traffic", "Transport", "Movement", "Flow"], correct: "Traffic" },
    { word: "Ausdruck", options: ["Expression", "Gesture", "Symbol", "Phrase"], correct: "Expression" },
    { word: "Schwierigkeit", options: ["Difficulty", "Problem", "Challenge", "Obstacle"], correct: "Difficulty" },
    { word: "Gegenteil", options: ["Opposite", "Contradiction", "Alternative", "Contrast"], correct: "Opposite" },
    { word: "Einschränkung", options: ["Limitation", "Restriction", "Constraint", "Limitation"], correct: "Limitation" },
    { word: "Erfolg", options: ["Success", "Achievement", "Victory", "Accomplishment"], correct: "Success" },
    { word: "Beziehung", options: ["Relationship", "Connection", "Bond", "Partnership"], correct: "Relationship" },
    { word: "Verfahren", options: ["Method", "Process", "Procedure", "Approach"], correct: "Method" },
    { word: "Dauer", options: ["Duration", "Length", "Period", "Timeframe"], correct: "Duration" },
    { word: "Konsistenz", options: ["Consistency", "Coherence", "Stability", "Uniformity"], correct: "Consistency" },
    { word: "Herausforderung", options: ["Challenge", "Task", "Problem", "Obstacle"], correct: "Challenge" },
    { word: "Verhältnis", options: ["Ratio", "Relationship", "Proportion", "Connection"], correct: "Ratio" },
    { word: "Fähigkeit", options: ["Ability", "Capacity", "Skill", "Talent"], correct: "Ability" },
    { word: "Forschung", options: ["Research", "Study", "Investigation", "Analysis"], correct: "Research" },
    { word: "Verletzung", options: ["Injury", "Harm", "Wound", "Damage"], correct: "Injury" },
    { word: "Wirkung", options: ["Effect", "Impact", "Result", "Consequence"], correct: "Effect" },
    { word: "Erklärung", options: ["Explanation", "Clarification", "Interpretation", "Statement"], correct: "Explanation" },
    { word: "Bedeutung", options: ["Meaning", "Significance", "Value", "Importance"], correct: "Meaning" },
    { word: "Überraschung", options: ["Surprise", "Astonishment", "Shock", "Stunning"], correct: "Surprise" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Judgment", "Verdict"], correct: "Decision" },
    { word: "Bedingung", options: ["Condition", "Requirement", "Term", "Clause"], correct: "Condition" },
    { word: "Gesellschaft", options: ["Society", "Community", "Company", "Organization"], correct: "Society" },
    { word: "Möglichkeit", options: ["Possibility", "Option", "Opportunity", "Chance"], correct: "Possibility" },
    { word: "Verantwortung", options: ["Responsibility", "Duty", "Accountability", "Obligation"], correct: "Responsibility" },
    { word: "Verhandlung", options: ["Negotiation", "Discussion", "Bargaining", "Debate"], correct: "Negotiation" },
    { word: "Erwartung", options: ["Expectation", "Anticipation", "Hope", "Desire"], correct: "Expectation" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Pleasure", "Happiness"], correct: "Satisfaction" },
    { word: "Zustimmung", options: ["Consent", "Approval", "Agreement", "Permission"], correct: "Consent" },
    { word: "Verbindung", options: ["Connection", "Relation", "Link", "Association"], correct: "Connection" },
    { word: "Entwicklung", options: ["Development", "Growth", "Advancement", "Evolution"], correct: "Development" },
    { word: "Lösung", options: ["Solution", "Answer", "Fix", "Resolution"], correct: "Solution" },
    { word: "Wissen", options: ["Knowledge", "Understanding", "Awareness", "Insight"], correct: "Knowledge" },
    { word: "Erfahrung", options: ["Experience", "Practice", "Knowledge", "Expertise"], correct: "Experience" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Term"], correct: "Prerequisite" },
    { word: "Enttäuschung", options: ["Disappointment", "Frustration", "Sadness", "Defeat"], correct: "Disappointment" },
    { word: "Abstimmung", options: ["Vote", "Poll", "Approval", "Agreement"], correct: "Vote" },
    { word: "Bedingung", options: ["Condition", "Requirement", "Circumstance", "Provision"], correct: "Condition" },
    { word: "Bestätigung", options: ["Confirmation", "Validation", "Affirmation", "Acknowledgment"], correct: "Confirmation" },
    { word: "Überlegung", options: ["Consideration", "Thought", "Deliberation", "Contemplation"], correct: "Consideration" },
    { word: "Kritik", options: ["Criticism", "Review", "Feedback", "Judgment"], correct: "Criticism" },
    { word: "Mangel", options: ["Lack", "Deficiency", "Shortage", "Absence"], correct: "Lack" },
    { word: "Ziel", options: ["Goal", "Aim", "Objective", "Target"], correct: "Goal" },
    { word: "Zukunft", options: ["Future", "Prospect", "Coming", "Time ahead"], correct: "Future" },
    { word: "Hoffnung", options: ["Hope", "Aspiration", "Dream", "Expectation"], correct: "Hope" },
    { word: "Schlussfolgerung", options: ["Conclusion", "Inference", "Deduction", "Result"], correct: "Conclusion" },
    { word: "Toleranz", options: ["Tolerance", "Patience", "Acceptance", "Endurance"], correct: "Tolerance" },
    { word: "Vertrauen", options: ["Trust", "Reliance", "Confidence", "Assurance"], correct: "Trust" },
    { word: "Verschiedenheit", options: ["Diversity", "Difference", "Variety", "Contradiction"], correct: "Diversity" },
    { word: "Geschenk", options: ["Gift", "Present", "Offer", "Surprise"], correct: "Gift" },
    { word: "Verkehr", options: ["Traffic", "Transportation", "Movement", "Flow"], correct: "Traffic" },
    { word: "Hintergrund", options: ["Background", "Context", "Foundation", "Origin"], correct: "Background" }
    ],
    C2: [
        { word: "Erklärung", options: ["Explanation", "Definition", "Description", "Clarification"], correct: "Explanation" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Obligation"], correct: "Prerequisite" },
    { word: "Komplexität", options: ["Complexity", "Difficulty", "Sophistication", "Intricacy"], correct: "Complexity" },
    { word: "Unterschied", options: ["Difference", "Distinction", "Disparity", "Contrast"], correct: "Difference" },
    { word: "Abstraktion", options: ["Abstraction", "Concept", "Theory", "Idea"], correct: "Abstraction" },
    { word: "Begriff", options: ["Concept", "Term", "Idea", "Word"], correct: "Concept" },
    { word: "Erkenntnis", options: ["Insight", "Realization", "Understanding", "Awareness"], correct: "Insight" },
    { word: "Verwirklichung", options: ["Realization", "Implementation", "Execution", "Fulfillment"], correct: "Realization" },
    { word: "Bedeutung", options: ["Meaning", "Significance", "Value", "Importance"], correct: "Meaning" },
    { word: "Verbindung", options: ["Connection", "Link", "Relation", "Association"], correct: "Connection" },
    { word: "Einsicht", options: ["Insight", "View", "Understanding", "Perspective"], correct: "Insight" },
    { word: "Störung", options: ["Disturbance", "Disruption", "Interruption", "Interference"], correct: "Disturbance" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Happiness", "Pleasure"], correct: "Satisfaction" },
    { word: "Überlegung", options: ["Consideration", "Reflection", "Contemplation", "Thought"], correct: "Consideration" },
    { word: "Verantwortung", options: ["Responsibility", "Accountability", "Duty", "Obligation"], correct: "Responsibility" },
    { word: "Gefühl", options: ["Feeling", "Emotion", "Sensation", "Sentiment"], correct: "Feeling" },
    { word: "Anerkennung", options: ["Recognition", "Acknowledgment", "Appreciation", "Validation"], correct: "Recognition" },
    { word: "Aussage", options: ["Statement", "Declaration", "Assertion", "Claim"], correct: "Statement" },
    { word: "Unabhängigkeit", options: ["Independence", "Autonomy", "Freedom", "Self-sufficiency"], correct: "Independence" },
    { word: "Wechselwirkung", options: ["Interaction", "Reciprocity", "Impact", "Interplay"], correct: "Interaction" },
    { word: "Zweck", options: ["Purpose", "Goal", "Objective", "Aim"], correct: "Purpose" },
    { word: "Verurteilung", options: ["Condemnation", "Judgment", "Conviction", "Censure"], correct: "Condemnation" },
    { word: "Eignung", options: ["Suitability", "Fitness", "Adequacy", "Capability"], correct: "Suitability" },
    { word: "Selbstbestimmung", options: ["Self-determination", "Autonomy", "Independence", "Freedom"], correct: "Self-determination" },
    { word: "Erschöpfung", options: ["Exhaustion", "Fatigue", "Tiredness", "Weariness"], correct: "Exhaustion" },
    { word: "Widerspruch", options: ["Contradiction", "Disagreement", "Opposition", "Conflict"], correct: "Contradiction" },
    { word: "Erklärung", options: ["Explanation", "Clarification", "Statement", "Interpretation"], correct: "Explanation" },
    { word: "Darbietung", options: ["Presentation", "Exhibition", "Display", "Performance"], correct: "Presentation" },
    { word: "Zustimmung", options: ["Consent", "Approval", "Agreement", "Permission"], correct: "Consent" },
    { word: "Beziehung", options: ["Relationship", "Connection", "Bond", "Link"], correct: "Relationship" },
    { word: "Konflikt", options: ["Conflict", "Dispute", "Clash", "Disagreement"], correct: "Conflict" },
    { word: "Abgrenzung", options: ["Demarcation", "Separation", "Division", "Boundary"], correct: "Demarcation" },
    { word: "Ausdruck", options: ["Expression", "Phrase", "Word", "Gesture"], correct: "Expression" },
    { word: "Veränderung", options: ["Change", "Alteration", "Modification", "Transformation"], correct: "Change" },
    { word: "Anpassung", options: ["Adaptation", "Adjustment", "Modification", "Change"], correct: "Adaptation" },
    { word: "Wirkung", options: ["Effect", "Impact", "Result", "Consequence"], correct: "Effect" },
    { word: "Wahrnehmung", options: ["Perception", "Awareness", "Cognition", "Sensation"], correct: "Perception" },
    { word: "Verlust", options: ["Loss", "Deprivation", "Diminishment", "Deficiency"], correct: "Loss" },
    { word: "Erziehung", options: ["Education", "Upbringing", "Teaching", "Training"], correct: "Education" },
    { word: "Inhalt", options: ["Content", "Substance", "Material", "Essence"], correct: "Content" },
    { word: "Mangel", options: ["Lack", "Deficiency", "Shortage", "Absence"], correct: "Lack" },
    { word: "Unterscheidung", options: ["Distinction", "Difference", "Discrimination", "Separation"], correct: "Distinction" },
    { word: "Fortschritt", options: ["Progress", "Advancement", "Development", "Improvement"], correct: "Progress" },
    { word: "Gegenteil", options: ["Opposite", "Contrary", "Inverse", "Reverse"], correct: "Opposite" },
    { word: "Erneuerung", options: ["Renewal", "Rejuvenation", "Restoration", "Revival"], correct: "Renewal" },
    { word: "Bereitschaft", options: ["Willingness", "Readiness", "Preparedness", "Eagerness"], correct: "Willingness" },
    { word: "Gefährdung", options: ["Hazard", "Endangerment", "Risk", "Threat"], correct: "Hazard" },
    { word: "Auswirkung", options: ["Impact", "Effect", "Consequence", "Result"], correct: "Impact" },
    { word: "Verlangen", options: ["Desire", "Craving", "Longing", "Wish"], correct: "Desire" },
    { word: "Vereinigung", options: ["Union", "Association", "Alliance", "Merger"], correct: "Union" },
    { word: "Herausforderung", options: ["Challenge", "Test", "Trial", "Difficulty"], correct: "Challenge" },
    { word: "Verantwortlichkeit", options: ["Accountability", "Responsibility", "Obligation", "Duty"], correct: "Accountability" },
    { word: "Vertraulichkeit", options: ["Confidentiality", "Secrecy", "Privacy", "Intimacy"], correct: "Confidentiality" },
    { word: "Behauptung", options: ["Claim", "Assertion", "Statement", "Declaration"], correct: "Claim" },
    { word: "Verfeinerung", options: ["Refinement", "Enhancement", "Polishing", "Improvement"], correct: "Refinement" },
    { word: "Begrenzung", options: ["Limitation", "Restriction", "Boundary", "Constraint"], correct: "Limitation" },
    { word: "Kombination", options: ["Combination", "Mixture", "Fusion", "Integration"], correct: "Combination" },{ word: "Überzeugung", options: ["Conviction", "Belief", "Opinion", "Trust"], correct: "Conviction" },
    { word: "Unabhängigkeit", options: ["Independence", "Autonomy", "Freedom", "Sovereignty"], correct: "Independence" },
    { word: "Verschiedenheit", options: ["Diversity", "Difference", "Contradiction", "Variation"], correct: "Diversity" },
    { word: "Selbstgenügsamkeit", options: ["Self-sufficiency", "Independence", "Autonomy", "Self-reliance"], correct: "Self-sufficiency" },
    { word: "Unzulänglichkeit", options: ["Inadequacy", "Insufficiency", "Deficiency", "Shortcoming"], correct: "Inadequacy" },
    { word: "Beweisführung", options: ["Argumentation", "Proof", "Justification", "Defense"], correct: "Argumentation" },
    { word: "Herausforderung", options: ["Challenge", "Test", "Difficulty", "Obstacle"], correct: "Challenge" },
    { word: "Vergangenheit", options: ["Past", "History", "Bygone", "Previous"], correct: "Past" },
    { word: "Zusammenhang", options: ["Context", "Connection", "Link", "Correlation"], correct: "Context" },
    { word: "Bedeutungsschwere", options: ["Gravitas", "Significance", "Weight", "Importance"], correct: "Gravitas" },
    { word: "Gegensatz", options: ["Contrast", "Opposition", "Antithesis", "Contradiction"], correct: "Contrast" },
    { word: "Widerspruch", options: ["Contradiction", "Opposition", "Disagreement", "Dispute"], correct: "Contradiction" },
    { word: "Erreichbarkeit", options: ["Accessibility", "Approachability", "Reachability", "Attainability"], correct: "Accessibility" },
    { word: "Entfaltung", options: ["Unfolding", "Development", "Expansion", "Revelation"], correct: "Unfolding" },
    { word: "Abstraktion", options: ["Abstraction", "Conceptualization", "Theorization", "Simplification"], correct: "Abstraction" },
    { word: "Skepsis", options: ["Skepticism", "Doubt", "Cynicism", "Uncertainty"], correct: "Skepticism" },
    { word: "Einschränkung", options: ["Restriction", "Limitation", "Constraint", "Boundary"], correct: "Restriction" },
    { word: "Verwirklichung", options: ["Realization", "Fulfillment", "Actualization", "Execution"], correct: "Realization" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Assumption"], correct: "Prerequisite" },
    { word: "Untersuchung", options: ["Investigation", "Research", "Examination", "Study"], correct: "Investigation" },
    { word: "Vernunft", options: ["Reason", "Logic", "Rationality", "Intellect"], correct: "Reason" },
    { word: "Verantwortung", options: ["Responsibility", "Accountability", "Obligation", "Duty"], correct: "Responsibility" },
    { word: "Beziehung", options: ["Relationship", "Connection", "Bond", "Association"], correct: "Relationship" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Happiness", "Pleasure"], correct: "Satisfaction" },
    { word: "Mangel", options: ["Lack", "Deficiency", "Shortage", "Absence"], correct: "Lack" },
    { word: "Verwendung", options: ["Use", "Application", "Utilization", "Purpose"], correct: "Use" },
    { word: "Anerkennung", options: ["Recognition", "Acknowledgment", "Appreciation", "Validation"], correct: "Recognition" },
    { word: "Abwägung", options: ["Weighing", "Consideration", "Assessment", "Evaluation"], correct: "Weighing" },
    { word: "Erklärung", options: ["Explanation", "Clarification", "Statement", "Interpretation"], correct: "Explanation" },
    { word: "Befürwortung", options: ["Support", "Endorsement", "Approval", "Advocacy"], correct: "Support" },
    { word: "Unterscheidung", options: ["Distinction", "Differentiation", "Separation", "Segregation"], correct: "Distinction" },
    { word: "Vertrauen", options: ["Trust", "Reliance", "Confidence", "Assurance"], correct: "Trust" },
    { word: "Komplexität", options: ["Complexity", "Intricacy", "Sophistication", "Convolution"], correct: "Complexity" },
    { word: "Fehlerhaftigkeit", options: ["Faultiness", "Imperfection", "Defectiveness", "Error-proneness"], correct: "Faultiness" },
    { word: "Zusammenstellung", options: ["Compilation", "Assembly", "Consolidation", "Collection"], correct: "Compilation" },
    { word: "Abhängigkeit", options: ["Dependency", "Reliance", "Addiction", "Subjugation"], correct: "Dependency" },
    { word: "Herkunft", options: ["Origin", "Source", "Background", "Ancestry"], correct: "Origin" },
    { word: "Bestätigung", options: ["Confirmation", "Affirmation", "Validation", "Approval"], correct: "Confirmation" },
    { word: "Überwachung", options: ["Monitoring", "Surveillance", "Oversight", "Supervision"], correct: "Monitoring" },
    { word: "Wissenschaft", options: ["Science", "Study", "Research", "Knowledge"], correct: "Science" },
    { word: "Veränderung", options: ["Change", "Alteration", "Modification", "Transformation"], correct: "Change" },
    { word: "Unkenntnis", options: ["Ignorance", "Lack of knowledge", "Unawareness", "Illiteracy"], correct: "Ignorance" },
    { word: "Unvorhersehbarkeit", options: ["Unpredictability", "Uncertainty", "Instability", "Volatility"], correct: "Unpredictability" },
    { word: "Verschwörung", options: ["Conspiracy", "Plot", "Scheme", "Intrigue"], correct: "Conspiracy" }
    ]
};

// German Word of the Day Data
const germanWordList = [
      { word: 'die Stadt', meaning: 'City', plural: 'die Städte', indefinite: 'eine Stadt', definite: 'die Stadt' },
  { word: 'der Apfel', meaning: 'An Apple', plural: 'die Äpfel', indefinite: 'ein Apfel', definite: 'der Apfel' },
  { word: 'das Buch', meaning: 'A Book', plural: 'die Bücher', indefinite: 'ein Buch', definite: 'das Buch' },
  { word: 'die Blume', meaning: 'Flower', plural: 'die Blumen', indefinite: 'eine Blume', definite: 'die Blume' },
  { word: 'der Hund', meaning: 'Dog', plural: 'die Hunde', indefinite: 'ein Hund', definite: 'der Hund' },
  { word: 'die Katze', meaning: 'Cat', plural: 'die Katzen', indefinite: 'eine Katze', definite: 'die Katze' },
  { word: 'das Haus', meaning: 'House', plural: 'die Häuser', indefinite: 'ein Haus', definite: 'das Haus' },
  { word: 'die Schule', meaning: 'School', plural: 'die Schulen', indefinite: 'eine Schule', definite: 'die Schule' },
  { word: 'der Tisch', meaning: 'Table', plural: 'die Tische', indefinite: 'ein Tisch', definite: 'der Tisch' },
  { word: 'die Lampe', meaning: 'Lamp', plural: 'die Lampen', indefinite: 'eine Lampe', definite: 'die Lampe' },
  { word: 'das Auto', meaning: 'Car', plural: 'die Autos', indefinite: 'ein Auto', definite: 'das Auto' },
  { word: 'die Tasche', meaning: 'Bag', plural: 'die Taschen', indefinite: 'eine Tasche', definite: 'die Tasche' },
  { word: 'der Stuhl', meaning: 'Chair', plural: 'die Stühle', indefinite: 'ein Stuhl', definite: 'der Stuhl' },
  { word: 'das Fenster', meaning: 'Window', plural: 'die Fenster', indefinite: 'ein Fenster', definite: 'das Fenster' },
  { word: 'die Wand', meaning: 'Wall', plural: 'die Wände', indefinite: 'eine Wand', definite: 'die Wand' },
  { word: 'die Tür', meaning: 'Door', plural: 'die Türen', indefinite: 'eine Tür', definite: 'die Tür' },
  { word: 'der Lehrer', meaning: 'Teacher (Male)', plural: 'die Lehrer', indefinite: 'ein Lehrer', definite: 'der Lehrer' },
  { word: 'die Lehrerin', meaning: 'Teacher (Female)', plural: 'die Lehrerinnen', indefinite: 'eine Lehrerin', definite: 'die Lehrerin' },
  { word: 'die Zeit', meaning: 'Time', plural: 'die Zeiten', indefinite: 'eine Zeit', definite: 'die Zeit' },
  { word: 'das Wasser', meaning: 'Water', plural: 'die Wasser', indefinite: 'ein Wasser', definite: 'das Wasser' },
  { word: 'der Tag', meaning: 'Day', plural: 'die Tage', indefinite: 'ein Tag', definite: 'der Tag' },
  { word: 'die Nacht', meaning: 'Night', plural: 'die Nächte', indefinite: 'eine Nacht', definite: 'die Nacht' },
  { word: 'der Monat', meaning: 'Month', plural: 'die Monate', indefinite: 'ein Monat', definite: 'der Monat' },
  { word: 'das Jahr', meaning: 'Year', plural: 'die Jahre', indefinite: 'ein Jahr', definite: 'das Jahr' },
  { word: 'der Freund', meaning: 'Friend (Male)', plural: 'die Freunde', indefinite: 'ein Freund', definite: 'der Freund' },
  { word: 'die Freundin', meaning: 'Friend (Female)', plural: 'die Freundinnen', indefinite: 'eine Freundin', definite: 'die Freundin' },
  { word: 'der Apfelbaum', meaning: 'Apple Tree', plural: 'die Apfelbäume', indefinite: 'ein Apfelbaum', definite: 'der Apfelbaum' },
  { word: 'das Schwein', meaning: 'Pig', plural: 'die Schweine', indefinite: 'ein Schwein', definite: 'das Schwein' },
  { word: 'der Vogel', meaning: 'Bird', plural: 'die Vögel', indefinite: 'ein Vogel', definite: 'der Vogel' },
  { word: 'die Maus', meaning: 'Mouse', plural: 'die Mäuse', indefinite: 'eine Maus', definite: 'die Maus' },
  { word: 'das Pferd', meaning: 'Horse', plural: 'die Pferde', indefinite: 'ein Pferd', definite: 'das Pferd' },
  { word: 'die Gabel', meaning: 'Fork', plural: 'die Gabeln', indefinite: 'eine Gabel', definite: 'die Gabel' },
  { word: 'das Messer', meaning: 'Knife', plural: 'die Messer', indefinite: 'ein Messer', definite: 'das Messer' },
  { word: 'der Löffel', meaning: 'Spoon', plural: 'die Löffel', indefinite: 'ein Löffel', definite: 'der Löffel' },
  { word: 'das Glas', meaning: 'Glass', plural: 'die Gläser', indefinite: 'ein Glas', definite: 'das Glas' },
  { word: 'die Tasse', meaning: 'Cup', plural: 'die Tassen', indefinite: 'eine Tasse', definite: 'die Tasse' },
  { word: 'der Teller', meaning: 'Plate', plural: 'die Teller', indefinite: 'ein Teller', definite: 'der Teller' },
  { word: 'die Gießkanne', meaning: 'Watering Can', plural: 'die Gießkannen', indefinite: 'eine Gießkanne', definite: 'die Gießkanne' },
  { word: 'das Kissen', meaning: 'Pillow', plural: 'die Kissen', indefinite: 'ein Kissen', definite: 'das Kissen' },
  { word: 'der Teppich', meaning: 'Carpet', plural: 'die Teppiche', indefinite: 'ein Teppich', definite: 'der Teppich' },
  { word: 'der Bildschirm', meaning: 'Screen', plural: 'die Bildschirme', indefinite: 'ein Bildschirm', definite: 'der Bildschirm' },
  { word: 'die Batterie', meaning: 'Battery', plural: 'die Batterien', indefinite: 'eine Batterie', definite: 'die Batterie' },  { word: 'das Telefon', meaning: 'Phone', plural: 'die Telefone', indefinite: 'ein Telefon', definite: 'das Telefon' },
  { word: 'die Maus', meaning: 'Mouse', plural: 'die Mäuse', indefinite: 'eine Maus', definite: 'die Maus' },
  { word: 'der Computer', meaning: 'Computer', plural: 'die Computer', indefinite: 'ein Computer', definite: 'der Computer' },
  { word: 'das Papier', meaning: 'Paper', plural: 'die Papiere', indefinite: 'ein Papier', definite: 'das Papier' },
  { word: 'der Stift', meaning: 'Pen', plural: 'die Stifte', indefinite: 'ein Stift', definite: 'der Stift' },
  { word: 'das Heft', meaning: 'Notebook', plural: 'die Hefte', indefinite: 'ein Heft', definite: 'das Heft' },
  { word: 'der Bleistift', meaning: 'Pencil', plural: 'die Bleistifte', indefinite: 'ein Bleistift', definite: 'der Bleistift' },
  { word: 'die Uhr', meaning: 'Clock', plural: 'die Uhren', indefinite: 'eine Uhr', definite: 'die Uhr' },
  { word: 'der Schreibtisch', meaning: 'Desk', plural: 'die Schreibtische', indefinite: 'ein Schreibtisch', definite: 'der Schreibtisch' },
  { word: 'die Decke', meaning: 'Ceiling', plural: 'die Decken', indefinite: 'eine Decke', definite: 'die Decke' },
  { word: 'der Boden', meaning: 'Floor', plural: 'die Böden', indefinite: 'ein Boden', definite: 'der Boden' },
  { word: 'der Raum', meaning: 'Room', plural: 'die Räume', indefinite: 'ein Raum', definite: 'der Raum' },
  { word: 'die Ecke', meaning: 'Corner', plural: 'die Ecken', indefinite: 'eine Ecke', definite: 'die Ecke' },
  { word: 'der Platz', meaning: 'Place', plural: 'die Plätze', indefinite: 'ein Platz', definite: 'der Platz' },
  { word: 'das Geschäft', meaning: 'Store', plural: 'die Geschäfte', indefinite: 'ein Geschäft', definite: 'das Geschäft' },
  { word: 'der Park', meaning: 'Park', plural: 'die Parks', indefinite: 'ein Park', definite: 'der Park' },
  { word: 'die Bibliothek', meaning: 'Library', plural: 'die Bibliotheken', indefinite: 'eine Bibliothek', definite: 'die Bibliothek' },
  { word: 'der Fluss', meaning: 'River', plural: 'die Flüsse', indefinite: 'ein Fluss', definite: 'der Fluss' },
  { word: 'der See', meaning: 'Lake', plural: 'die Seen', indefinite: 'ein See', definite: 'der See' },
  { word: 'das Meer', meaning: 'Sea', plural: 'die Meere', indefinite: 'ein Meer', definite: 'das Meer' },
  { word: 'der Himmel', meaning: 'Sky', plural: 'die Himmel', indefinite: 'ein Himmel', definite: 'der Himmel' },
  { word: 'die Wolke', meaning: 'Cloud', plural: 'die Wolken', indefinite: 'eine Wolke', definite: 'die Wolke' },
  { word: 'der Regen', meaning: 'Rain', plural: 'die Regen', indefinite: 'ein Regen', definite: 'der Regen' },
  { word: 'die Sonne', meaning: 'Sun', plural: 'die Sonnen', indefinite: 'eine Sonne', definite: 'die Sonne' },
  { word: 'der Wind', meaning: 'Wind', plural: 'die Winde', indefinite: 'ein Wind', definite: 'der Wind' },
  { word: 'das Feuer', meaning: 'Fire', plural: 'die Feuer', indefinite: 'ein Feuer', definite: 'das Feuer' },
  { word: 'der Schnee', meaning: 'Snow', plural: 'die Schneen', indefinite: 'ein Schnee', definite: 'der Schnee' },
  { word: 'die Erde', meaning: 'Earth', plural: 'die Erden', indefinite: 'eine Erde', definite: 'die Erde' },
  { word: 'der Berg', meaning: 'Mountain', plural: 'die Berge', indefinite: 'ein Berg', definite: 'der Berg' },
  { word: 'die Insel', meaning: 'Island', plural: 'die Inseln', indefinite: 'eine Insel', definite: 'die Insel' },
  { word: 'das Tal', meaning: 'Valley', plural: 'die Täler', indefinite: 'ein Tal', definite: 'das Tal' },
  { word: 'die Wüste', meaning: 'Desert', plural: 'die Wüsten', indefinite: 'eine Wüste', definite: 'die Wüste' },
  { word: 'der Wald', meaning: 'Forest', plural: 'die Wälder', indefinite: 'ein Wald', definite: 'der Wald' },
  { word: 'das Gebirge', meaning: 'Mountain Range', plural: 'die Gebirge', indefinite: 'ein Gebirge', definite: 'das Gebirge' },
  { word: 'der Ozean', meaning: 'Ocean', plural: 'die Ozeane', indefinite: 'ein Ozean', definite: 'der Ozean' },
  { word: 'die Mütze', meaning: 'Hat', plural: 'die Mützen', indefinite: 'eine Mütze', definite: 'die Mütze' },
  { word: 'der Schuh', meaning: 'Shoe', plural: 'die Schuhe', indefinite: 'ein Schuh', definite: 'der Schuh' },
  { word: 'das Hemd', meaning: 'Shirt', plural: 'die Hemden', indefinite: 'ein Hemd', definite: 'das Hemd' },
  { word: 'die Jacke', meaning: 'Jacket', plural: 'die Jacken', indefinite: 'eine Jacke', definite: 'die Jacke' },
  { word: 'der Mantel', meaning: 'Coat', plural: 'die Mäntel', indefinite: 'ein Mantel', definite: 'der Mantel' },
  { word: 'das Kleid', meaning: 'Dress', plural: 'die Kleider', indefinite: 'ein Kleid', definite: 'das Kleid' },
  { word: 'die Hose', meaning: 'Pants', plural: 'die Hosen', indefinite: 'eine Hose', definite: 'die Hose' },
  { word: 'der Rock', meaning: 'Skirt', plural: 'die Röcke', indefinite: 'ein Rock', definite: 'der Rock' },
  { word: 'das T-Shirt', meaning: 'T-shirt', plural: 'die T-Shirts', indefinite: 'ein T-Shirt', definite: 'das T-Shirt' },
  { word: 'die Brille', meaning: 'Glasses', plural: 'die Brillen', indefinite: 'eine Brille', definite: 'die Brille' },
  { word: 'der Hut', meaning: 'Hat', plural: 'die Hüte', indefinite: 'ein Hut', definite: 'der Hut' },
  { word: 'das Kleidungsstück', meaning: 'Clothing', plural: 'die Kleidungsstücke', indefinite: 'ein Kleidungsstück', definite: 'das Kleidungsstück' },
  { word: 'die Socken', meaning: 'Socks', plural: 'die Socken', indefinite: 'Socken', definite: 'die Socken' },
  { word: 'der Handschuh', meaning: 'Glove', plural: 'die Handschuhe', indefinite: 'ein Handschuh', definite: 'der Handschuh' },
  { word: 'die Tasche', meaning: 'Bag', plural: 'die Taschen', indefinite: 'eine Tasche', definite: 'die Tasche' },
  { word: 'das Portemonnaie', meaning: 'Wallet', plural: 'die Portemonnaies', indefinite: 'ein Portemonnaie', definite: 'das Portemonnaie' },
  { word: 'der Rucksack', meaning: 'Backpack', plural: 'die Rucksäcke', indefinite: 'ein Rucksack', definite: 'der Rucksack' },
  { word: 'die Kette', meaning: 'Necklace', plural: 'die Ketten', indefinite: 'eine Kette', definite: 'die Kette' },
  { word: 'der Ring', meaning: 'Ring', plural: 'die Ringe', indefinite: 'ein Ring', definite: 'der Ring' },
  { word: 'das Armband', meaning: 'Bracelet', plural: 'die Armbänder', indefinite: 'ein Armband', definite: 'das Armband' },
  { word: 'die Uhr', meaning: 'Watch', plural: 'die Uhren', indefinite: 'eine Uhr', definite: 'die Uhr' },
  { word: 'der Schlüssel', meaning: 'Key', plural: 'die Schlüssel', indefinite: 'ein Schlüssel', definite: 'der Schlüssel' },
  { word: 'das Schloss', meaning: 'Lock', plural: 'die Schlösser', indefinite: 'ein Schloss', definite: 'das Schloss' },
  { word: 'der Brief', meaning: 'Letter', plural: 'die Briefe', indefinite: 'ein Brief', definite: 'der Brief' },
  { word: 'die Post', meaning: 'Post', plural: 'die Post', indefinite: 'Post', definite: 'die Post' },
  { word: 'das Paket', meaning: 'Package', plural: 'die Pakete', indefinite: 'ein Paket', definite: 'das Paket' },
  { word: 'der Briefumschlag', meaning:'Envelope', plural: 'die Briefumschläge', indefinite: 'ein Briefumschlag', definite: 'der Briefumschlag' },
  { word: 'die Karte', meaning: 'Card', plural: 'die Karten', indefinite: 'eine Karte', definite: 'die Karte' },
  { word: 'der Stempel', meaning: 'Stamp', plural: 'die Stempel', indefinite: 'ein Stempel', definite: 'der Stempel' },
  { word: 'das Telefon', meaning: 'Phone', plural: 'die Telefone', indefinite: 'ein Telefon', definite: 'das Telefon' },
  { word: 'die Nachricht', meaning: 'Message', plural: 'die Nachrichten', indefinite: 'eine Nachricht', definite: 'die Nachricht' },
  { word: 'der Anruf', meaning: 'Call', plural: 'die Anrufe', indefinite: 'ein Anruf', definite: 'der Anruf' },
  { word: 'das Fax', meaning: 'Fax', plural: 'die Faxe', indefinite: 'ein Fax', definite: 'das Fax' },
  { word: 'die E-Mail', meaning: 'Email', plural: 'die E-Mails', indefinite: 'eine E-Mail', definite: 'die E-Mail' },
  { word: 'der Computer', meaning: 'Computer', plural: 'die Computer', indefinite: 'ein Computer', definite: 'der Computer' },
  { word: 'das Internet', meaning: 'Internet', plural: 'die Internets', indefinite: 'ein Internet', definite: 'das Internet' },
  { word: 'die Website', meaning: 'Website', plural: 'die Websites', indefinite: 'eine Website', definite: 'die Website' },
  { word: 'der Bildschirm', meaning: 'Screen', plural: 'die Bildschirme', indefinite: 'ein Bildschirm', definite: 'der Bildschirm' },
  { word: 'das Kabel', meaning: 'Cable', plural: 'die Kabel', indefinite: 'ein Kabel', definite: 'das Kabel' },
  { word: 'die Maus', meaning: 'Mouse', plural: 'die Mäuse', indefinite: 'eine Maus', definite: 'die Maus' },
  { word: 'der Lautsprecher', meaning: 'Speaker', plural: 'die Lautsprecher', indefinite: 'ein Lautsprecher', definite: 'der Lautsprecher' },
  { word: 'das Mikrofon', meaning: 'Microphone', plural: 'die Mikrofone', indefinite: 'ein Mikrofon', definite: 'das Mikrofon' },
  { word: 'die Kamera', meaning: 'Camera', plural: 'die Kameras', indefinite: 'eine Kamera', definite: 'die Kamera' },
  { word: 'der Drucker', meaning: 'Printer', plural: 'die Drucker', indefinite: 'ein Drucker', definite: 'der Drucker' },
  { word: 'das Faxgerät', meaning: 'Fax Machine', plural: 'die Faxgeräte', indefinite: 'ein Faxgerät', definite: 'das Faxgerät' },
  { word: 'die Tastatur', meaning: 'Keyboard', plural: 'die Tastaturen', indefinite: 'eine Tastatur', definite: 'die Tastatur' },
  { word: 'der Speicher', meaning: 'Memory', plural: 'die Speicher', indefinite: 'ein Speicher', definite: 'der Speicher' },
  { word: 'das Ladegerät', meaning: 'Charger', plural: 'die Ladegeräte', indefinite: 'ein Ladegerät', definite: 'das Ladegerät' },
  { word: 'die Software', meaning: 'Software', plural: 'die Software', indefinite: 'Software', definite: 'die Software' },
  { word: 'der USB-Stick', meaning: 'USB Stick', plural: 'die USB-Sticks', indefinite: 'ein USB-Stick', definite: 'der USB-Stick' },
  { word: 'das USB-Kabel', meaning: 'USB Cable', plural: 'die USB-Kabel', indefinite: 'ein USB-Kabel', definite: 'das USB-Kabel' },
  { word: 'die Festplatte', meaning: 'Hard Drive', plural: 'die Festplatten', indefinite: 'eine Festplatte', definite: 'die Festplatte' },
  { word: 'der Laptop', meaning: 'Laptop', plural: 'die Laptops', indefinite: 'ein Laptop', definite: 'der Laptop' },
  { word: 'das Tablet', meaning: 'Tablet', plural: 'die Tablets', indefinite: 'ein Tablet', definite: 'das Tablet' },
  { word: 'die Mausmatte', meaning: 'Mousepad', plural: 'die Mausmatten', indefinite: 'eine Mausmatte', definite: 'die Mausmatte' },
  { word: 'der Stecker', meaning: 'Plug', plural: 'die Stecker', indefinite: 'ein Stecker', definite: 'der Stecker' },
  { word: 'das Kabel', meaning: 'Cable', plural: 'die Kabel', indefinite: 'ein Kabel', definite: 'das Kabel' },
  { word: 'die Straße', meaning: 'Street', plural: 'die Straßen', indefinite: 'eine Straße', definite: 'die Straße' },
  { word: 'der Park', meaning: 'Park', plural: 'die Parks', indefinite: 'ein Park', definite: 'der Park' },
  { word: 'das Gebäude', meaning: 'Building', plural: 'die Gebäude', indefinite: 'ein Gebäude', definite: 'das Gebäude' },
  { word: 'die Stadt', meaning: 'City', plural: 'die Städte', indefinite: 'eine Stadt', definite: 'die Stadt' },
  { word: 'der Platz', meaning: 'Square', plural: 'die Plätze', indefinite: 'ein Platz', definite: 'der Platz' },
  { word: 'das Dorf', meaning: 'Village', plural: 'die Dörfer', indefinite: 'ein Dorf', definite: 'das Dorf' },
  { word: 'die Brücke', meaning: 'Bridge', plural: 'die Brücken', indefinite: 'eine Brücke', definite: 'die Brücke' },
  { word: 'der Fluss', meaning: 'River', plural: 'die Flüsse', indefinite: 'ein Fluss', definite: 'der Fluss' },
  { word: 'das Meer', meaning: 'Sea', plural: 'die Meere', indefinite: 'ein Meer', definite: 'das Meer' },
  { word: 'die Insel', meaning: 'Island', plural: 'die Inseln', indefinite: 'eine Insel', definite: 'die Insel' },
  { word: 'der Wald', meaning: 'Forest', plural: 'die Wälder', indefinite: 'ein Wald', definite: 'der Wald' },
  { word: 'das Land', meaning: 'Country', plural: 'die Länder', indefinite: 'ein Land', definite: 'das Land' },
  { word: 'die Wüste', meaning: 'Desert', plural: 'die Wüsten', indefinite: 'eine Wüste', definite: 'die Wüste' },
  { word: 'der Berg', meaning: 'Mountain', plural: 'die Berge', indefinite: 'ein Berg', definite: 'der Berg' },
  { word: 'das Tal', meaning: 'Valley', plural: 'die Täler', indefinite: 'ein Tal', definite: 'das Tal' },
  { word: 'die Küste', meaning: 'Coast', plural: 'die Küsten', indefinite: 'eine Küste', definite: 'die Küste' },
  { word: 'der See', meaning: 'Lake', plural: 'die Seen', indefinite: 'ein See', definite: 'der See' },
  { word: 'das Ufer', meaning: 'Shore', plural: 'die Ufer', indefinite: 'ein Ufer', definite: 'das Ufer' },
  { word: 'die Straße', meaning: 'Road', plural: 'die Straßen', indefinite: 'eine Straße', definite: 'die Straße' },
  { word: 'der Weg', meaning: 'Path', plural: 'die Wege', indefinite: 'ein Weg', definite: 'der Weg' },
  { word: 'das Auto', meaning: 'Car', plural: 'die Autos', indefinite: 'ein Auto', definite: 'das Auto' },
  { word: 'die Bahn', meaning: 'Train', plural: 'die Bahnen', indefinite: 'eine Bahn', definite: 'die Bahn' },
  { word: 'der Bus', meaning: 'Bus', plural: 'die Busse', indefinite: 'ein Bus', definite: 'der Bus' },
  { word: 'das Flugzeug', meaning: 'Airplane', plural: 'die Flugzeuge', indefinite: 'ein Flugzeug', definite: 'das Flugzeug' },
  { word: 'der Schiff', meaning: 'Ship', plural: 'die Schiffe', indefinite: 'ein Schiff', definite: 'der Schiff' },
  { word: 'die Fahrräder', meaning: 'Bicycles', plural: 'die Fahrräder', indefinite: 'Fahrräder', definite: 'die Fahrräder' },
  { word: 'der Flughafen', meaning: 'Airport', plural: 'die Flughäfen', indefinite: 'ein Flughafen', definite: 'der Flughafen' },
  { word: 'das Ticket', meaning: 'Ticket', plural: 'die Tickets', indefinite: 'ein Ticket', definite: 'das Ticket' },
  { word: 'die Karte', meaning: 'Map', plural: 'die Karten', indefinite: 'eine Karte', definite: 'die Karte' },
  { word: 'der Plan', meaning: 'Plan', plural: 'die Pläne', indefinite: 'ein Plan', definite: 'der Plan' },
  { word: 'die Richtung', meaning: 'Direction', plural: 'die Richtungen', indefinite: 'eine Richtung', definite: 'die Richtung' },
  { word: 'der Süden', meaning: 'South', plural: 'die Süden', indefinite: 'Süden', definite: 'der Süden' },
  { word: 'das Norden', meaning: 'North', plural: 'die Norden', indefinite: 'Norden', definite: 'das Norden' },
  { word: 'der Westen', meaning: 'West', plural: 'die Westen', indefinite: 'Westen', definite: 'der Westen' },
  { word: 'das Osten', meaning: 'East', plural: 'die Osten', indefinite: 'Osten', definite: 'das Osten' },
  { word: 'die Geschwindigkeit', meaning: 'Speed', plural: 'die Geschwindigkeiten', indefinite: 'eine Geschwindigkeit', definite: 'die Geschwindigkeit' },
  { word: 'der Stau', meaning: 'Traffic Jam', plural: 'die Staus', indefinite: 'ein Stau', definite: 'der Stau' },
  { word: 'die Brücke', meaning: 'Bridge', plural: 'die Brücken', indefinite: 'eine Brücke', definite: 'die Brücke' },
  { word: 'der Tunnel', meaning: 'Tunnel', plural: 'die Tunnel', indefinite: 'ein Tunnel', definite: 'der Tunnel' },
  { word: 'das Verkehrsschild', meaning: 'Traffic Sign', plural: 'die Verkehrsschilder', indefinite: 'ein Verkehrsschild', definite: 'das Verkehrsschild' },
  { word: 'die Straße', meaning: 'Street', plural: 'die Straßen', indefinite: 'eine Straße', definite: 'die Straße' },
  { word: 'der Verkehr', meaning: 'Traffic', plural: 'die Verkehre', indefinite: 'Verkehr', definite: 'der Verkehr' },
  { word: 'das Parken', meaning: 'Parking', plural: 'die Parken', indefinite: 'Parken', definite: 'das Parken' },
  { word: 'der Parkplatz', meaning: 'Parking Lot', plural: 'die Parkplätze', indefinite: 'ein Parkplatz', definite: 'der Parkplatz' },
  { word: 'das Taxi', meaning: 'Taxi', plural: 'die Taxis', indefinite: 'ein Taxi', definite: 'das Taxi' },
  { word: 'die Linie', meaning: 'Line', plural: 'die Linien', indefinite: 'eine Linie', definite: 'die Linie' },
  { word: 'der Wegweiser', meaning: 'Signpost', plural: 'die Wegweiser', indefinite: 'ein Wegweiser', definite: 'der Wegweiser' },
  { word: 'die Kreuzung', meaning: 'Intersection', plural: 'die Kreuzungen', indefinite: 'eine Kreuzung', definite: 'die Kreuzung' },
  { word: 'der Bürgersteig', meaning: 'Sidewalk', plural: 'die Bürgersteige', indefinite: 'ein Bürgersteig', definite: 'der Bürgersteig' },
  { word: 'das Autohaus', meaning: 'Car Dealership', plural: 'die Autohäuser', indefinite: 'ein Autohaus', definite: 'das Autohaus' },
  { word: 'die Werkstatt', meaning: 'Workshop', plural: 'die Werkstätten', indefinite: 'eine Werkstatt', definite: 'die Werkstatt' },
  { word: 'der Motor', meaning: 'Engine', plural: 'die Motoren', indefinite: 'ein Motor', definite: 'der Motor' },
  { word: 'das Getriebe', meaning: 'Transmission', plural: 'die Getriebe', indefinite: 'ein Getriebe', definite: 'das Getriebe' },
  { word: 'der Reifen', meaning: 'Tire', plural: 'die Reifen', indefinite: 'ein Reifen', definite: 'der Reifen' },
  { word: 'das Autozubehör', meaning: 'Car Accessories', plural: 'die Autozubehör', indefinite: 'Autozubehör', definite: 'das Autozubehör' },
  { word: 'die Karosserie', meaning: 'Car Body', plural: 'die Karosserien', indefinite: 'eine Karosserie', definite: 'die Karosserie' }
];

module.exports = { germanQuizData, germanWordList };