// Quiz Data for German
const germanQuizData = {
  A1: [
  { word: 'Apfel', meaning: 'Apple', options: ['A: Apple', 'B: House', 'C: Dog', 'D: Cat'], correct: '🇦' },
  { word: 'Haus', meaning: 'House', options: ['A: Apple', 'B: House', 'C: Dog', 'D: Cat'], correct: '🇧' },
  { word: 'Tisch', meaning: 'Table', options: ['A: Table', 'B: Chair', 'C: Door', 'D: Window'], correct: '🇦' },
  { word: 'Stuhl', meaning: 'Chair', options: ['A: Table', 'B: Chair', 'C: Bed', 'D: Lamp'], correct: '🇧' },
  { word: 'Brot', meaning: 'Bread', options: ['A: Bread', 'B: Butter', 'C: Cake', 'D: Milk'], correct: '🇦' },
  { word: 'Wasser', meaning: 'Water', options: ['A: Water', 'B: Juice', 'C: Coffee', 'D: Tea'], correct: '🇦' },
  { word: 'Auto', meaning: 'Car', options: ['A: Train', 'B: Bus', 'C: Car', 'D: Plane'], correct: '🇨' },
  { word: 'Blume', meaning: 'Flower', options: ['A: Tree', 'B: Grass', 'C: Flower', 'D: Leaf'], correct: '🇨' },
  { word: 'Hund', meaning: 'Dog', options: ['A: Cat', 'B: Bird', 'C: Dog', 'D: Fish'], correct: '🇨' },
  { word: 'Katze', meaning: 'Cat', options: ['A: Rabbit', 'B: Cat', 'C: Dog', 'D: Bird'], correct: '🇧' },
  { word: 'Fisch', meaning: 'Fish', options: ['A: Fish', 'B: Chicken', 'C: Meat', 'D: Egg'], correct: '🇦' },
  { word: 'Buch', meaning: 'Book', options: ['A: Book', 'B: Pen', 'C: Notebook', 'D: Paper'], correct: '🇦' },
  { word: 'Tür', meaning: 'Door', options: ['A: Window', 'B: Door', 'C: Wall', 'D: Floor'], correct: '🇧' },
  { word: 'Fenster', meaning: 'Window', options: ['A: Roof', 'B: Window', 'C: Wall', 'D: Door'], correct: '🇧' },
  { word: 'Lampe', meaning: 'Lamp', options: ['A: Light', 'B: Lamp', 'C: Fan', 'D: Clock'], correct: '🇧' },
  { word: 'Tasche', meaning: 'Bag', options: ['A: Bag', 'B: Hat', 'C: Shoes', 'D: Jacket'], correct: '🇦' },
  { word: 'Schule', meaning: 'School', options: ['A: School', 'B: Office', 'C: Library', 'D: Home'], correct: '🇦' },
  { word: 'Lehrer', meaning: 'Teacher', options: ['A: Student', 'B: Principal', 'C: Teacher', 'D: Class'], correct: '🇨' },
  { word: 'Bleistift', meaning: 'Pencil', options: ['A: Pen', 'B: Marker', 'C: Pencil', 'D: Eraser'], correct: '🇨' },
  { word: 'Rad', meaning: 'Bicycle', options: ['A: Car', 'B: Bicycle', 'C: Train', 'D: Plane'], correct: '🇧' },
  { word: 'Baum', meaning: 'Tree', options: ['A: Tree', 'B: Forest', 'C: Flower', 'D: Grass'], correct: '🇦' },
  { word: 'Hut', meaning: 'Hat', options: ['A: Shoes', 'B: Jacket', 'C: Hat', 'D: Shirt'], correct: '🇨' },
  { word: 'Zeitung', meaning: 'Newspaper', options: ['A: Magazine', 'B: Newspaper', 'C: Book', 'D: Notebook'], correct: '🇧' },
  { word: 'Stadt', meaning: 'City', options: ['A: Village', 'B: City', 'C: Town', 'D: Country'], correct: '🇧' },
  { word: 'Torte', meaning: 'Cake', options: ['A: Bread', 'B: Cake', 'C: Cookie', 'D: Pie'], correct: '🇧' },
  { word: 'Vogel', meaning: 'Bird', options: ['A: Bird', 'B: Fish', 'C: Cat', 'D: Dog'], correct: '🇦' },
  { word: 'Tischdecke', meaning: 'Tablecloth', options: ['A: Tablecloth', 'B: Curtain', 'C: Blanket', 'D: Carpet'], correct: '🇦' },
  { word: 'Kind', meaning: 'Child', options: ['A: Baby', 'B: Child', 'C: Parent', 'D: Adult'], correct: '🇧' },
  { word: 'Bett', meaning: 'Bed', options: ['A: Chair', 'B: Sofa', 'C: Bed', 'D: Desk'], correct: '🇨' },
  { word: 'Tasse', meaning: 'Cup', options: ['A: Plate', 'B: Bowl', 'C: Cup', 'D: Glass'], correct: '🇨' },
  { word: 'Schrank', meaning: 'Wardrobe', options: ['A: Shelf', 'B: Wardrobe', 'C: Drawer', 'D: Mirror'], correct: '🇧' },
  { word: 'Maus', meaning: 'Mouse', options: ['A: Rat', 'B: Mouse', 'C: Cat', 'D: Bird'], correct: '🇧' },
  { word: 'Wand', meaning: 'Wall', options: ['A: Roof', 'B: Wall', 'C: Door', 'D: Window'], correct: '🇧' },
  { word: 'Kuh', meaning: 'Cow', options: ['A: Horse', 'B: Cow', 'C: Goat', 'D: Sheep'], correct: '🇧' },
  { word: 'Blatt', meaning: 'Leaf', options: ['A: Leaf', 'B: Flower', 'C: Grass', 'D: Tree'], correct: '🇦' },
  { word: 'Hemd', meaning: 'Shirt', options: ['A: Pants', 'B: Jacket', 'C: Shirt', 'D: Hat'], correct: '🇨' },
  { word: 'Jacke', meaning: 'Jacket', options: ['A: Coat', 'B: Jacket', 'C: Sweater', 'D: Scarf'], correct: '🇧' },
  { word: 'Schuh', meaning: 'Shoe', options: ['A: Sandal', 'B: Boot', 'C: Shoe', 'D: Sock'], correct: '🇨' },
  { word: 'Zug', meaning: 'Train', options: ['A: Car', 'B: Plane', 'C: Train', 'D: Bus'], correct: '🇨' },
  { word: 'Stift', meaning: 'Pen', options: ['A: Pencil', 'B: Pen', 'C: Marker', 'D: Eraser'], correct: '🇧' },
  { word: 'Sonne', meaning: 'Sun', options: ['A: Moon', 'B: Sun', 'C: Star', 'D: Sky'], correct: '🇧' },
  { word: 'Wolke', meaning: 'Cloud', options: ['A: Sky', 'B: Rain', 'C: Cloud', 'D: Fog'], correct: '🇨' },
  { word: 'Fahrzeug', meaning: 'Vehicle', options: ['A: Airplane', 'B: Car', 'C: Vehicle', 'D: Train'], correct: '🇨' },
  { word: 'Regen', meaning: 'Rain', options: ['A: Sun', 'B: Rain', 'C: Snow', 'D: Fog'], correct: '🇧' },
  { word: 'Schnee', meaning: 'Snow', options: ['A: Snow', 'B: Rain', 'C: Storm', 'D: Cloud'], correct: '🇦' },
  { word: 'Eis', meaning: 'Ice', options: ['A: Snow', 'B: Ice', 'C: Water', 'D: Rain'], correct: '🇧' },
  { word: 'Berg', meaning: 'Mountain', options: ['A: Hill', 'B: Mountain', 'C: Sea', 'D: Plain'], correct: '🇧' },
  { word: 'Tal', meaning: 'Valley', options: ['A: Hill', 'B: Valley', 'C: Mountain', 'D: Lake'], correct: '🇧' },
  { word: 'Fluss', meaning: 'River', options: ['A: Ocean', 'B: River', 'C: Lake', 'D: Sea'], correct: '🇧' },
  { word: 'Meer', meaning: 'Sea', options: ['A: Ocean', 'B: Lake', 'C: River', 'D: Sea'], correct: '🇩' },
  { word: 'Insel', meaning: 'Island', options: ['A: Mountain', 'B: Island', 'C: Lake', 'D: River'], correct: '🇧' },
  { word: 'Wald', meaning: 'Forest', options: ['A: Desert', 'B: Forest', 'C: Lake', 'D: Mountain'], correct: '🇧' },
  { word: 'See', meaning: 'Lake', options: ['A: Sea', 'B: River', 'C: Mountain', 'D: Lake'], correct: '🇩' },
  { word: 'Land', meaning: 'Country', options: ['A: Town', 'B: Country', 'C: Village', 'D: City'], correct: '🇧' }
  ], 
  A2: [
   { word: 'Abend', meaning: 'Evening', options: ['A: Morning', 'B: Evening', 'C: Night', 'D: Afternoon'], correct: '🇧' },
  { word: 'Arzt', meaning: 'Doctor', options: ['A: Teacher', 'B: Doctor', 'C: Nurse', 'D: Patient'], correct: '🇧' },
  { word: 'Ausland', meaning: 'Abroad', options: ['A: Country', 'B: Abroad', 'C: City', 'D: Town'], correct: '🇧' },
  { word: 'Bank', meaning: 'Bank', options: ['A: Bank', 'B: Money', 'C: Store', 'D: Office'], correct: '🇦' },
  { word: 'Büro', meaning: 'Office', options: ['A: Shop', 'B: School', 'C: Office', 'D: Library'], correct: '🇨' },
  { word: 'Essen', meaning: 'Food', options: ['A: Food', 'B: Drink', 'C: Fruit', 'D: Vegetable'], correct: '🇦' },
  { word: 'Familie', meaning: 'Family', options: ['A: Family', 'B: Friends', 'C: Parents', 'D: Children'], correct: '🇦' },
  { word: 'Ferien', meaning: 'Holiday', options: ['A: Weekend', 'B: Break', 'C: Holiday', 'D: School'], correct: '🇨' },
  { word: 'Flughafen', meaning: 'Airport', options: ['A: Hotel', 'B: Train station', 'C: Airport', 'D: Bus stop'], correct: '🇨' },
  { word: 'Freund', meaning: 'Friend', options: ['A: Parent', 'B: Teacher', 'C: Friend', 'D: Neighbor'], correct: '🇨' },
  { word: 'Geschenk', meaning: 'Gift', options: ['A: Present', 'B: Letter', 'C: Food', 'D: Card'], correct: '🇦' },
  { word: 'Gesundheit', meaning: 'Health', options: ['A: Illness', 'B: Health', 'C: Disease', 'D: Fever'], correct: '🇧' },
  { word: 'Glück', meaning: 'Happiness', options: ['A: Sadness', 'B: Joy', 'C: Luck', 'D: Happiness'], correct: '🇩' },
  { word: 'Hoffnung', meaning: 'Hope', options: ['A: Despair', 'B: Hope', 'C: Anger', 'D: Fear'], correct: '🇧' },
  { word: 'Hotel', meaning: 'Hotel', options: ['A: Restaurant', 'B: Hotel', 'C: Cafe', 'D: Store'], correct: '🇧' },
  { word: 'Insel', meaning: 'Island', options: ['A: River', 'B: Ocean', 'C: Mountain', 'D: Island'], correct: '🇩' },
  { word: 'Jahr', meaning: 'Year', options: ['A: Week', 'B: Month', 'C: Day', 'D: Year'], correct: '🇩' },
  { word: 'Kaffee', meaning: 'Coffee', options: ['A: Tea', 'B: Coffee', 'C: Water', 'D: Juice'], correct: '🇧' },
  { word: 'Kamera', meaning: 'Camera', options: ['A: Phone', 'B: Camera', 'C: Laptop', 'D: Tablet'], correct: '🇧' },
  { word: 'Kleider', meaning: 'Clothes', options: ['A: Shoes', 'B: Clothes', 'C: Hat', 'D: Jacket'], correct: '🇧' },
  { word: 'Licht', meaning: 'Light', options: ['A: Darkness', 'B: Light', 'C: Shadow', 'D: Fire'], correct: '🇧' },
  { word: 'Mensch', meaning: 'Person', options: ['A: Animal', 'B: Person', 'C: Child', 'D: Woman'], correct: '🇧' },
  { word: 'Möglich', meaning: 'Possible', options: ['A: Impossible', 'B: Unlikely', 'C: Possible', 'D: Available'], correct: '🇨' },
  { word: 'Natur', meaning: 'Nature', options: ['A: Weather', 'B: Nature', 'C: Environment', 'D: Forest'], correct: '🇧' },
  { word: 'Obst', meaning: 'Fruit', options: ['A: Vegetable', 'B: Food', 'C: Fruit', 'D: Dairy'], correct: '🇨' },
  { word: 'Post', meaning: 'Mail', options: ['A: Phone', 'B: Internet', 'C: Mail', 'D: Email'], correct: '🇨' },
  { word: 'Reise', meaning: 'Trip', options: ['A: Trip', 'B: Journey', 'C: Flight', 'D: Drive'], correct: '🇦' },
  { word: 'Restaurant', meaning: 'Restaurant', options: ['A: Cafe', 'B: Hotel', 'C: Restaurant', 'D: Bar'], correct: '🇨' },
  { word: 'Schule', meaning: 'School', options: ['A: College', 'B: School', 'C: University', 'D: Office'], correct: '🇧' },
  { word: 'Schwimmbad', meaning: 'Swimming pool', options: ['A: Beach', 'B: Swimming pool', 'C: Ocean', 'D: River'], correct: '🇧' },
  { word: 'Stadt', meaning: 'City', options: ['A: Village', 'B: Town', 'C: City', 'D: Country'], correct: '🇨' },
  { word: 'Straße', meaning: 'Street', options: ['A: Park', 'B: Street', 'C: Square', 'D: Building'], correct: '🇧' },
  { word: 'Telefon', meaning: 'Telephone', options: ['A: Phone', 'B: Laptop', 'C: TV', 'D: Radio'], correct: '🇦' },
  { word: 'Tier', meaning: 'Animal', options: ['A: Person', 'B: Animal', 'C: Plant', 'D: Insect'], correct: '🇧' },
  { word: 'Universität', meaning: 'University', options: ['A: School', 'B: College', 'C: University', 'D: Highschool'], correct: '🇨' },
  { word: 'Urlaub', meaning: 'Vacation', options: ['A: School', 'B: Job', 'C: Vacation', 'D: Weekend'], correct: '🇨' },
  { word: 'Vater', meaning: 'Father', options: ['A: Mother', 'B: Father', 'C: Brother', 'D: Sister'], correct: '🇧' },
  { word: 'Woche', meaning: 'Week', options: ['A: Month', 'B: Year', 'C: Week', 'D: Day'], correct: '🇨' },
  { word: 'Zukunft', meaning: 'Future', options: ['A: Past', 'B: Future', 'C: Present', 'D: History'], correct: '🇧' },
  { word: 'Zug', meaning: 'Train', options: ['A: Car', 'B: Plane', 'C: Bus', 'D: Train'], correct: '🇩' },
  { word: 'Ziel', meaning: 'Goal', options: ['A: Goal', 'B: Target', 'C: End', 'D: Dream'], correct: '🇦' },
  { word: 'Zeitung', meaning: 'Newspaper', options: ['A: Magazine', 'B: Newspaper', 'C: Book', 'D: Journal'], correct: '🇧' },
  { word: 'Zentrum', meaning: 'Center', options: ['A: Side', 'B: Center', 'C: Top', 'D: Corner'], correct: '🇧' },
  { word: 'Zahnarzt', meaning: 'Dentist', options: ['A: Doctor', 'B: Dentist', 'C: Nurse', 'D: Teacher'], correct: '🇧' },
  { word: 'Zeichen', meaning: 'Sign', options: ['A: Symbol', 'B: Sign', 'C: Mark', 'D: Letter'], correct: '🇧' },
  { word: 'Zunge', meaning: 'Tongue', options: ['A: Lip', 'B: Tongue', 'C: Teeth', 'D: Cheeks'], correct: '🇧' }
  ],
  B1: [
  { word: 'Abenteuer', meaning: 'Adventure', options: ['A: Routine', 'B: Challenge', 'C: Adventure', 'D: Job'], correct: '🇨' },
  { word: 'Angebot', meaning: 'Offer', options: ['A: Request', 'B: Offer', 'C: Answer', 'D: Idea'], correct: '🇧' },
  { word: 'Ausdruck', meaning: 'Expression', options: ['A: Thought', 'B: Expression', 'C:Message', 'D: Feeling'], correct: '🇧' },
  { word: 'Bedingung', meaning: 'Condition', options: ['A: Rule', 'B: Term', 'C: Condition', 'D: Instruction'], correct: '🇨' },
  { word: 'Beitrag', meaning: 'Contribution', options: ['A: Payment', 'B: Post', 'C: Contribution', 'D: Reply'], correct: '🇨' },
  { word: 'Behörde', meaning: 'Authority', options: ['A: Office', 'B: Department', 'C: Authority', 'D: Worker'], correct: '🇨' },
  { word: 'Bewerbung', meaning: 'Application', options: ['A: Request', 'B: Application', 'C: Offer', 'D: Appointment'], correct: '🇧' },
  { word: 'Beziehung', meaning: 'Relationship', options: ['A: Friendship', 'B: Relationship', 'C: Partnership', 'D: Connection'], correct: '🇧' },
  { word: 'Bildung', meaning: 'Education', options: ['A: Learning', 'B: Knowledge', 'C: Education', 'D: Information'], correct: '🇨' },
  { word: 'Chance', meaning: 'Chance', options: ['A: Opportunity', 'B: Time', 'C: Moment', 'D: Chance'], correct: '🇦' },
  { word: 'Debatte', meaning: 'Debate', options: ['A: Discussion', 'B: Disagreement', 'C: Debate', 'D: Agreement'], correct: '🇨' },
  { word: 'Dienstleistung', meaning: 'Service', options: ['A: Payment', 'B: Product', 'C: Service', 'D: Delivery'], correct: '🇨' },
  { word: 'Einstellung', meaning: 'Attitude', options: ['A: Work', 'B: Attitude', 'C: Job', 'D: Opinion'], correct: '🇧' },
  { word: 'Ereignis', meaning: 'Event', options: ['A: Experience', 'B: Event', 'C: Celebration', 'D: Occasion'], correct: '🇧' },
  { word: 'Erfahrung', meaning: 'Experience', options: ['A: Expertise', 'B: Understanding', 'C: Experience', 'D: Memory'], correct: '🇨' },
  { word: 'Fähigkeit', meaning: 'Ability', options: ['A: Talent', 'B: Ability', 'C: Skill', 'D: Power'], correct: '🇧' },
  { word: 'Fortschritt', meaning: 'Progress', options: ['A: Stagnation', 'B: Setback', 'C: Progress', 'D: Decline'], correct: '🇨' },
  { word: 'Freiheit', meaning: 'Freedom', options: ['A: Power', 'B: Authority', 'C: Freedom', 'D: Independence'], correct: '🇨' },
  { word: 'Geduld', meaning: 'Patience', options: ['A: Anger', 'B: Patience', 'C: Frustration', 'D: Energy'], correct: '🇧' },
  { word: 'Gegenteil', meaning: 'Opposite', options: ['A: Similar', 'B: Equal', 'C: Opposite', 'D: Different'], correct: '🇨' },
  { word: 'Gesellschaft', meaning: 'Society', options: ['A: Community', 'B: Organization', 'C: Group', 'D: Society'], correct: '🇨' },
  { word: 'Glauben', meaning: 'Belief', options: ['A: Opinion', 'B: Truth', 'C: Fact', 'D: Belief'], correct: '🇩' },
  { word: 'Grenze', meaning: 'Border', options: ['A: Center', 'B: Border', 'C: End', 'D: Middle'], correct: '🇧' },
  { word: 'Herausforderung', meaning: 'Challenge', options: ['A: Test', 'B: Task', 'C: Challenge', 'D: Help'], correct: '🇨' },
  { word: 'Hoffnung', meaning: 'Hope', options: ['A: Faith', 'B: Despair', 'C: Hope', 'D: Truth'], correct: '🇨' },
  { word: 'Kompetenz', meaning: 'Competence', options: ['A: Skill', 'B: Experience', 'C: Knowledge', 'D: Competence'], correct: '🇨' },
  { word: 'Kritik', meaning: 'Criticism', options: ['A: Support', 'B: Praise', 'C: Criticism', 'D: Approval'], correct: '🇨' },
  { word: 'Lernziel', meaning: 'Learning objective', options: ['A: Objective', 'B: Goal', 'C: Plan', 'D: Lesson'], correct: '🇦' },
  { word: 'Mangel', meaning: 'Deficiency', options: ['A: Surplus', 'B: Lack', 'C: Deficiency', 'D: Excess'], correct: '🇧' },
  { word: 'Motivation', meaning: 'Motivation', options: ['A: Goal', 'B: Drive', 'C: Motivation', 'D: Force'], correct: '🇨' },
  { word: 'Möglichkeit', meaning: 'Possibility', options: ['A: Opportunity', 'B: Limitation', 'C: Possibility', 'D: Choice'], correct: '🇨' },
  { word: 'Nachricht', meaning: 'Message', options: ['A: Communication', 'B: Message', 'C: Call', 'D: Talk'], correct: '🇧' },
  { word: 'Notwendigkeit', meaning: 'Necessity', options: ['A: Luxury', 'B: Possibility', 'C: Need', 'D: Requirement'], correct: '🇩' },
  { word: 'Politik', meaning: 'Politics', options: ['A: Law', 'B: Governance', 'C: Politics', 'D: Society'], correct: '🇨' },
  { word: 'Qualität', meaning: 'Quality', options: ['A: Standard', 'B: Level', 'C: Quality', 'D: Amount'], correct: '🇨' },
  { word: 'Recht', meaning: 'Law', options: ['A: Law', 'B: Freedom', 'C: Justice', 'D: Rule'], correct: '🇨' },
  { word: 'Reise', meaning: 'Journey', options: ['A: Destination', 'B: Trip', 'C: Flight', 'D: Tour'], correct: '🇧' },
  { word: 'Sicherheit', meaning: 'Security', options: ['A: Risk', 'B: Danger', 'C: Safety', 'D: Protection'], correct: '🇨' },
  { word: 'Verantwortung', meaning: 'Responsibility', options: ['A: Power', 'B: Responsibility', 'C: Control', 'D: Obligation'], correct: '🇧' },
  { word: 'Verhandlung', meaning: 'Negotiation', options: ['A: Discussion', 'B: Contract', 'C: Agreement', 'D: Negotiation'], correct: '🇩' },
  { word: 'Vorschlag', meaning: 'Suggestion', options: ['A: Request', 'B: Suggestion', 'C: Answer', 'D: Decision'], correct: '🇧' },
  { word: 'Wert', meaning: 'Value', options: ['A: Price', 'B: Value', 'C: Cost', 'D: Rate'], correct: '🇧' },
  { word: 'Zustand', meaning: 'Condition', options: ['A: Situation', 'B: Condition', 'C: Stage', 'D: Moment'], correct: '🇨' },
  { word: 'Zukunft', meaning: 'Future', options: ['A: Past', 'B: Present', 'C: Future', 'D: Now'], correct: '🇨' },
  { word: 'Ziel', meaning: 'Goal', options: ['A: Target', 'B: Objective', 'C: Goal', 'D: Aim'], correct: '🇨' },
  { word: 'Zweifel', meaning: 'Doubt', options: ['A: Certainty', 'B: Hesitation', 'C: Question', 'D: Doubt'], correct: '🇨' }
   ],
  B2: [
    { word: 'Abschluss', meaning: 'Conclusion', options: ['A: Start', 'B: Conclusion', 'C: Beginning', 'D: Outcome'], correct: '🇧' },
  { word: 'Anforderung', meaning: 'Requirement', options: ['A: Suggestion', 'B: Demand', 'C: Requirement', 'D: Request'], correct: '🇩' },
  { word: 'Auswirkung', meaning: 'Impact', options: ['A: Influence', 'B: Impact', 'C: Effect', 'D: Result'], correct: '🇧' },
  { word: 'Bedenken', meaning: 'Concern', options: ['A: Doubt', 'B: Question', 'C: Concern', 'D: Fear'], correct: '🇩' },
  { word: 'Beispiel', meaning: 'Example', options: ['A: Idea', 'B: Model', 'C: Example', 'D: Test'], correct: '🇩' },
  { word: 'Beschäftigung', meaning: 'Employment', options: ['A: Job', 'B: Work', 'C: Occupation', 'D: Employment'], correct: '🇩' },
  { word: 'Beteiligung', meaning: 'Participation', options: ['A: Joining', 'B: Participation', 'C: Role', 'D: Effort'], correct: '🇧' },
  { word: 'Bevollmächtigung', meaning: 'Authorization', options: ['A: Permission', 'B: Authorization', 'C: Power', 'D: Order'], correct: '🇧' },
  { word: 'Eindruck', meaning: 'Impression', options: ['A: Impact', 'B: Understanding', 'C: Impression', 'D: Reaction'], correct: '🇩' },
  { word: 'Einfluss', meaning: 'Influence', options: ['A: Control', 'B: Authority', 'C: Influence', 'D: Suggestion'], correct: '🇩' },  { word: 'Ergebnis', meaning: 'Result', options: ['A: Beginning', 'B: Process', 'C: Result', 'D: Preparation'], correct: '🇩' },
  { word: 'Fähigkeit', meaning: 'Ability', options: ['A: Strength', 'B: Knowledge', 'C: Ability', 'D: Talent'], correct: '🇩' },
  { word: 'Fortschritt', meaning: 'Progress', options: ['A: Development', 'B: Progress', 'C: Improvement', 'D: Change'], correct: '🇧' },
  { word: 'Gegensätzlich', meaning: 'Contrary', options: ['A: Similar', 'B: Different', 'C: Opposite', 'D: Related'], correct: '🇨' },
  { word: 'Glaubwürdigkeit', meaning: 'Credibility', options: ['A: Trust', 'B: Reliability', 'C: Authority', 'D: Credibility'], correct: '🇩' },
  { word: 'Größe', meaning: 'Size', options: ['A: Shape', 'B: Width', 'C: Height', 'D: Size'], correct: '🇩' },
  { word: 'Herkunft', meaning: 'Origin', options: ['A: Birth', 'B: Heritage', 'C: Origin', 'D: Destination'], correct: '🇩' },
  { word: 'Individuum', meaning: 'Individual', options: ['A: Group', 'B: Team', 'C: Person', 'D: Individual'], correct: '🇩' },
  { word: 'Kooperation', meaning: 'Cooperation', options: ['A: Interaction', 'B: Help', 'C: Teamwork', 'D: Cooperation'], correct: '🇩' },
  { word: 'Kritik', meaning: 'Criticism', options: ['A: Feedback', 'B: Suggestion', 'C: Review', 'D: Criticism'], correct: '🇩' },
  { word: 'Leistung', meaning: 'Performance', options: ['A: Output', 'B: Effort', 'C: Quality', 'D: Performance'], correct: '🇩' },
  { word: 'Möglichkeit', meaning: 'Possibility', options: ['A: Opportunity', 'B: Reality', 'C: Chance', 'D: Possibility'], correct: '🇩' },
  { word: 'Notwendigkeit', meaning: 'Necessity', options: ['A: Requirement', 'B: Choice', 'C: Condition', 'D: Necessity'], correct: '🇩' },
  { word: 'Qualität', meaning: 'Quality', options: ['A: Quantity', 'B: Amount', 'C: Quality', 'D: Feature'], correct: '🇩' },
  { word: 'Reaktion', meaning: 'Reaction', options: ['A: Response', 'B: Action', 'C: Reaction', 'D: Response'], correct: '🇩' },
  { word: 'Ressource', meaning: 'Resource', options: ['A: Asset', 'B: Benefit', 'C: Resource', 'D: Tool'], correct: '🇩' },
  { word: 'Schwierigkeit', meaning: 'Difficulty', options: ['A: Problem', 'B: Issue', 'C: Difficulty', 'D: Opportunity'], correct: '🇩' },
  { word: 'Sicherheit', meaning: 'Security', options: ['A: Trust', 'B: Safety', 'C: Protection', 'D: Confidence'], correct: '🇩' },
  { word: 'Spannung', meaning: 'Tension', options: ['A: Relaxation', 'B: Stress', 'C: Excitement', 'D: Tension'], correct: '🇩' },
  { word: 'Tatsache', meaning: 'Fact', options: ['A: Truth', 'B: Argument', 'C: Fact', 'D: Story'], correct: '🇩' },
  { word: 'Verantwortung', meaning: 'Responsibility', options: ['A: Control', 'B: Obligation', 'C: Accountability', 'D: Responsibility'], correct: '🇩' },
  { word: 'Vorschlag', meaning: 'Proposal', options: ['A: Idea', 'B: Suggestion', 'C: Offer', 'D: Proposal'], correct: '🇩' },
  { word: 'Zukunft', meaning: 'Future', options: ['A: Now', 'B: Past', 'C: Present', 'D: Future'], correct: '🇩' },
  { word: 'Zusammenhang', meaning: 'Context', options: ['A: Reason', 'B: Conclusion', 'C: Context', 'D: Situation'], correct: '🇩' },
  { word: 'Zufriedenheit', meaning: 'Satisfaction', options: ['A: Joy', 'B: Contentment', 'C: Happiness', 'D: Satisfaction'], correct: '🇩' },
  { word: 'Zweifel', meaning: 'Doubt', options: ['A: Certainty', 'B: Question', 'C: Doubt', 'D: Agreement'], correct: '🇩' },
  { word: 'Zugang', meaning: 'Access', options: ['A: Entrance', 'B: Connection', 'C: Access', 'D: Admission'], correct: '🇩' },
  { word: 'Abneigung', meaning: 'Dislike', options: ['A: Attraction', 'B: Dislike', 'C: Preference', 'D: Respect'], correct: '🇧' },
  { word: 'Aussicht', meaning: 'View', options: ['A: Prospect', 'B: Sight', 'C: Image', 'D: View'], correct: '🇩' },
  { word: 'Einstellung', meaning: 'Position', options: ['A: View', 'B: Approach', 'C:Position', 'D: Opinion'], correct: '🇩' },
  { word: 'Erlaubnis', meaning: 'Permission', options: ['A: Consent', 'B: Permission', 'C: Grant', 'D: Request'], correct: '🇩' },
  { word: 'Herausforderung', meaning: 'Challenge', options: ['A: Task', 'B: Issue', 'C: Difficulty', 'D: Challenge'], correct: '🇩' },
  { word: 'Lösungsweg', meaning: 'Solution', options: ['A: Plan', 'B: Answer', 'C: Strategy', 'D: Solution'], correct: '🇩' },
  { word: 'Nachhaltigkeit', meaning: 'Sustainability', options: ['A: Change', 'B: Conservation', 'C: Continuation', 'D: Sustainability'], correct: '🇩' },
  { word: 'Unterschied', meaning: 'Difference', options: ['A: Similarity', 'B: Difference', 'C: Variation', 'D: Divergence'], correct: '🇩' },
  { word: 'Verhältnis', meaning: 'Relation', options: ['A: Ratio', 'B: Comparison', 'C: Relationship', 'D: Value'], correct: '🇩' },
  { word: 'Verantwortung', meaning: 'Responsibility', options: ['A: Role', 'B: Duty', 'C: Task', 'D: Responsibility'], correct: '🇩' },
  { word: 'Verschwendung', meaning: 'Waste', options: ['A: Loss', 'B: Waste', 'C: Use', 'D: Expense'], correct: '🇩' },
  { word: 'Wachstum', meaning: 'Growth', options: ['A: Change', 'B: Expansion', 'C: Increase', 'D: Growth'], correct: '🇩' },
  { word: 'Zerstörung', meaning: 'Destruction', options: ['A: Build', 'B: Damage', 'C: Destruction', 'D: Repair'], correct: '🇩' },
  { word: 'Zusammenarbeit', meaning: 'Collaboration', options: ['A: Group', 'B: Cooperation', 'C: Teamwork', 'D: Collaboration'], correct: '🇩' },
  { word: 'Zufall', meaning: 'Chance', options: ['A: Coincidence', 'B: Event', 'C: Luck', 'D: Chance'], correct: '🇩' },
  { word: 'Zukunftsperspektive', meaning: 'Future perspective', options: ['A: Vision', 'B: Option', 'C: Outlook', 'D: Perspective'], correct: '🇩' },
  { word: 'Zustand', meaning: 'State', options: ['A: Situation', 'B: Condition', 'C: Position', 'D: State'], correct: '🇩' }
  ],
  C1: [
    { word: 'Abstraktion', meaning: 'Abstraction', options: ['A: Explanation', 'B: Simplification', 'C: Generalization', 'D: Abstraction'], correct: '🇩' },
  { word: 'Angemessenheit', meaning: 'Appropriateness', options: ['A: Fit', 'B: Relevance', 'C: Suitability', 'D: Appropriateness'], correct: '🇩' },
  { word: 'Anpassungsfähigkeit', meaning: 'Adaptability', options: ['A: Flexibility', 'B: Change', 'C: Stability', 'D: Adaptability'], correct: '🇩' },
  { word: 'Aufgeschlossenheit', meaning: 'Open-mindedness', options: ['A: Receptiveness', 'B: Tolerance', 'C: Broadmindedness', 'D: Open-mindedness'], correct: '🇩' },
  { word: 'Ausgewogenheit', meaning: 'Balance', options: ['A: Moderation', 'B: Proportion', 'C: Fairness', 'D: Balance'], correct: '🇩' },
  { word: 'Bedeutungslosigkeit', meaning: 'Insignificance', options: ['A: Unimportance', 'B: Meaninglessness', 'C: Inconsequence', 'D: Insignificance'], correct: '🇩' },
  { word: 'Begeisterung', meaning: 'Enthusiasm', options: ['A: Passion', 'B: Excitement', 'C: Zeal', 'D: Enthusiasm'], correct: '🇩' },
  { word: 'Beständigkeit', meaning: 'Consistency', options: ['A: Regularity', 'B: Stability', 'C: Dependability', 'D: Consistency'], correct: '🇩' },
  { word: 'Differenzierung', meaning: 'Differentiation', options: ['A: Contrast', 'B: Separation', 'C: Diversity', 'D: Differentiation'], correct: '🇩' },
  { word: 'Entschlossenheit', meaning: 'Determination', options: ['A: Willpower', 'B: Resolution', 'C: Steadfastness', 'D: Determination'], correct: '🇩' },
  { word: 'Erklärung', meaning: 'Clarification', options: ['A: Explanation', 'B: Argument', 'C: Justification', 'D: Clarification'], correct: '🇩' },
  { word: 'Erfahrung', meaning: 'Experience', options: ['A: Knowledge', 'B: Practice', 'C: Encounter', 'D: Experience'], correct: '🇩' },
  { word: 'Fähigkeit', meaning: 'Competence', options: ['A: Skill', 'B: Ability', 'C: Capability', 'D: Competence'], correct:'🇩' },
  { word: 'Fortschrittlichkeit', meaning: 'Progressiveness', options: ['A: Innovation', 'B: Openness', 'C: Advancement', 'D: Progressiveness'], correct: '🇩' },
  { word: 'Freundlichkeit', meaning: 'Kindness', options: ['A: Gentleness', 'B: Compassion', 'C: Friendliness', 'D: Kindness'], correct: '🇩' },
  { word: 'Freiheit', meaning: 'Freedom', options: ['A: Liberty', 'B: Independence', 'C: Autonomy', 'D: Freedom'], correct: '🇩' },
  { word: 'Generosität', meaning: 'Generosity', options: ['A: Altruism', 'B: Giving', 'C: Magnanimity', 'D: Generosity'], correct: '🇩' },
  { word: 'Gesellschaft', meaning: 'Society', options: ['A: Group', 'B: Public', 'C: Community', 'D: Society'], correct: '🇩' },
  { word: 'Komplexität', meaning: 'Complexity', options: ['A: Intricacy', 'B: Difficulty', 'C: Complication', 'D: Complexity'], correct: '🇩' },
  { word: 'Konsistenz', meaning: 'Consistency', options: ['A: Regularity', 'B: Cohesion', 'C: Stability', 'D: Consistency'], correct: '🇩' },
  { word: 'Kritikfähigkeit', meaning: 'Criticism', options: ['A: Judgment', 'B: Reflection', 'C: Sensitivity', 'D: Criticism'], correct: '🇩' },
  { word: 'Lebensqualität', meaning: 'Quality of life', options: ['A: Prosperity', 'B: Well-being', 'C: Comfort', 'D: Quality of life'], correct: '🇩' },
  { word: 'Nachhaltigkeit', meaning: 'Sustainability', options: ['A: Eco-friendliness', 'B: Durability', 'C: Responsibility', 'D: Sustainability'], correct: '🇩' },
  { word: 'Optimierung', meaning: 'Optimization', options: ['A: Improvement', 'B: Refinement', 'C: Enhancement', 'D: Optimization'], correct: '🇩' },
  { word: 'Präzision', meaning: 'Precision', options: ['A: Exactness', 'B: Accuracy', 'C: Specificity', 'D: Precision'], correct: '🇩' },
  { word: 'Reflexion', meaning: 'Reflection', options: ['A: Review', 'B: Meditation', 'C: Thought', 'D: Reflection'], correct: '🇩' },
  { word: 'Respekt', meaning: 'Respect', options: ['A: Honor', 'B: Courtesy', 'C: Regard', 'D: Respect'], correct: '🇩' },
  { word: 'Sicherheit', meaning: 'Security', options: ['A: Safety', 'B: Protection', 'C: Assurance', 'D: Security'], correct: '🇩' },
  { word: 'Souveränität', meaning: 'Sovereignty', options: ['A: Authority', 'B: Control', 'C: Supremacy', 'D: Sovereignty'], correct: '🇩' },
  { word: 'Spontaneität', meaning: 'Spontaneity', options: ['A: Impulse', 'B: Freedom', 'C: Instinct', 'D: Spontaneity'], correct: '🇩' },
  { word: 'Toleranz', meaning: 'Tolerance', options: ['A: Patience', 'B: Openness', 'C: Acceptance', 'D: Tolerance'], correct: '🇩' },
  { word: 'Transparenz', meaning: 'Transparency', options: ['A: Clarity', 'B: Openness', 'C: Insight', 'D: Transparency'], correct: '🇩' },
  { word: 'Verantwortung', meaning: 'Responsibility', options: ['A: Obligation', 'B: Accountability', 'C: Duty', 'D: Responsibility'], correct: '🇩' },
  { word: 'Verlässlichkeit', meaning: 'Reliability', options: ['A: Dependability', 'B: Trustworthiness', 'C: Steadiness', 'D: Reliability'], correct: '🇩' },
  { word: 'Vertrauen', meaning: 'Trust', options: ['A: Confidence', 'B: Belief', 'C: Faith', 'D: Trust'], correct: '🇩' },
  { word: 'Verstehen', meaning: 'Comprehension', options: ['A: Recognition', 'B: Insight', 'C: Understanding', 'D: Perception'], correct: '🇩' },
  { word: 'Verzahnung', meaning: 'Interconnection', options: ['A: Integration', 'B: Relationship', 'C: Linkage', 'D: Interconnection'], correct: '🇩' },
  { word: 'Vorbereitung', meaning: 'Preparation', options: ['A: Setup', 'B: Training', 'C: Planning', 'D: Preparation'], correct: '🇩' },  { word: 'Wahrnehmung', meaning: 'Perception', options: ['A: View', 'B: Interpretation', 'C: Insight', 'D: Perception'], correct: '🇩' },
  { word: 'Wertschätzung', meaning: 'Appreciation', options: ['A: Acknowledgment', 'B: Recognition', 'C: Value', 'D: Appreciation'], correct: '🇩' },
  { word: 'Wissenschaftlichkeit', meaning: 'Scientific approach', options: ['A: Research', 'B: Knowledge', 'C: Methodology', 'D: Scientific approach'], correct: '🇩' },
  { word: 'Zuverlässigkeit', meaning: 'Reliability', options: ['A: Certainty', 'B: Trustworthiness', 'C: Consistency', 'D: Reliability'], correct: '🇩' },
  { word: 'Zielstrebigkeit', meaning: 'Determination', options: ['A: Dedication', 'B: Resolve', 'C: Focus', 'D: Determination'], correct: '🇩' },
  { word: 'Zusammenarbeit', meaning: 'Collaboration', options: ['A: Teamwork', 'B: Cooperation', 'C: Collaboration', 'D: Partnership'], correct: '🇩' },
  { word: 'Zweckmäßigkeit', meaning: 'Purposefulness', options: ['A: Effectiveness', 'B: Relevance', 'C: Suitability', 'D: Purposefulness'], correct: '🇩' },
  { word: 'Zustimmung', meaning: 'Approval', options: ['A: Consent', 'B: Agreement', 'C: Affirmation', 'D: Approval'], correct: '🇩' },
  { word: 'Zweifel', meaning: 'Doubt', options: ['A: Certainty', 'B: Uncertainty', 'C: Skepticism', 'D: Doubt'], correct: '🇩' }
  ],
  C2: [
    { word: 'Abgleich', meaning: 'Comparison', options: ['A: Harmony', 'B: Coordination', 'C: Adjustment', 'D: Comparison'], correct: '🇩' },
  { word: 'Abstraktionsvermögen', meaning: 'Ability to abstract', options: ['A: Logical thinking', 'B: Conceptualization', 'C: Deduction', 'D: Ability to abstract'], correct: '🇩' },
  { word: 'Allgemeingültigkeit', meaning: 'Universality', options: ['A: Generalization', 'B: Global applicability', 'C: Universality', 'D: Validity'], correct: '🇩' },
  { word: 'Amortisation', meaning: 'Amortization', options: ['A: Payback', 'B: Return', 'C: Reimbursement', 'D: Amortization'], correct: '🇩' },
  { word: 'Antizipation', meaning: 'Anticipation', options: ['A: Forecast', 'B: Prediction', 'C: Expectation', 'D: Anticipation'], correct: '🇩' },
  { word: 'Argumentationsfähigkeit', meaning: 'Argumentation skill', options: ['A: Persuasiveness', 'B: Rhetoric', 'C: Discussion ability', 'D: Argumentation skill'], correct: '🇩' },
  { word: 'Assoziation', meaning: 'Association', options: ['A: Relation', 'B: Connection', 'C: Link', 'D: Association'], correct: '🇩' },
  { word: 'Authentizität', meaning: 'Authenticity', options: ['A: Genuineness', 'B: Truth', 'C: Originality', 'D: Authenticity'], correct: '🇩' },
  { word: 'Berechenbarkeit', meaning: 'Predictability', options: ['A: Reliability', 'B: Expectability', 'C: Measurability', 'D: Predictability'], correct: '🇩' },
  { word: 'Differenzierung', meaning: 'Differentiation', options: ['A: Distinction', 'B: Segmentation', 'C: Classification', 'D: Differentiation'], correct: '🇩' },
  { word: 'Disziplin', meaning: 'Discipline', options: ['A: Orderliness', 'B: Control', 'C: Commitment', 'D: Discipline'], correct: '🇩' },
  { word: 'Erkennbarkeit', meaning: 'Recognizability', options: ['A: Visibility', 'B: Distinguishability', 'C: Clarity', 'D: Recognizability'], correct: '🇩' },
  { word: 'Ernsthaftigkeit', meaning: 'Seriousness', options: ['A: Gravity', 'B: Solemnity', 'C: Sincerity', 'D: Seriousness'], correct: '🇩' },
  { word: 'Exaktheit', meaning: 'Precision', options: ['A: Exactness', 'B: Rigidity', 'C: Carefulness', 'D: Precision'], correct: '🇩' },
  { word: 'Fähigkeitsanalyse', meaning: 'Skills analysis', options: ['A: Evaluation', 'B: Competency check', 'C: Capacity review', 'D: Skills analysis'], correct: '🇩' },
  { word: 'Flüssigkeit', meaning: 'Fluency', options: ['A: Ease', 'B: Smoothness', 'C: Flow', 'D: Fluency'], correct: '🇩' },
  { word: 'Gegenseitigkeit', meaning: 'Reciprocity', options: ['A: Symmetry', 'B: Exchange', 'C: Mutuality', 'D: Reciprocity'], correct: '🇩' },
  { word: 'Gegensatz', meaning: 'Contradiction', options: ['A: Contrast', 'B: Disagreement', 'C: Discrepancy', 'D: Contradiction'], correct: '🇩' },
  { word: 'Intuition', meaning: 'Intuition', options: ['A: Instinct', 'B: Insight', 'C: Perception', 'D: Intuition'], correct: '🇩' },  { word: 'Konformität', meaning: 'Conformity', options: ['A: Agreement', 'B: Compliance', 'C: Adherence', 'D: Conformity'], correct: '🇩' },
  { word: 'Komplexität', meaning: 'Complexity', options: ['A: Intricacy', 'B: Difficulty', 'C: Entanglement', 'D: Complexity'], correct: '🇩' },
  { word: 'Korrektheit', meaning: 'Correctness', options: ['A: Rightness', 'B: Exactness', 'C: Accuracy', 'D: Correctness'], correct: '🇩' },
  { word: 'Kritikfähigkeit', meaning: 'Criticism capability', options: ['A: Review ability', 'B: Reflection', 'C: Analytical skill', 'D: Criticism capability'], correct: '🇩' },
  { word: 'Kultiviertheit', meaning: 'Cultivation', options: ['A: Refinement', 'B: Development', 'C: Culture', 'D: Cultivation'], correct: '🇩' },
  { word: 'Kompetenz', meaning: 'Competence', options: ['A: Expertise', 'B: Proficiency', 'C: Knowledge', 'D: Competence'], correct: '🇩' },
  { word: 'Loyalität', meaning: 'Loyalty', options: ['A: Allegiance', 'B: Faithfulness', 'C: Devotion', 'D: Loyalty'], correct: '🇩' },
  { word: 'Mangelware', meaning: 'Scarcity', options: ['A: Deficiency', 'B: Shortage', 'C: Deprivation', 'D: Scarcity'], correct: '🇩' },
  { word: 'Mobilität', meaning: 'Mobility', options: ['A: Flexibility', 'B: Motion', 'C: Mobility', 'D: Fluidity'], correct: '🇩' },
  { word: 'Modulation', meaning: 'Modulation', options: ['A: Control', 'B: Adjustment', 'C: Balance', 'D: Modulation'], correct: '🇩' },
  { word: 'Neutralität', meaning: 'Neutrality', options: ['A: Impartiality', 'B: Indifference', 'C: Objectivity', 'D: Neutrality'], correct: '🇩' },
  { word: 'Nachhaltigkeit', meaning: 'Sustainability', options: ['A: Durability', 'B: Eco-friendliness', 'C: Long-lasting', 'D: Sustainability'], correct: '🇩' },
  { word: 'Originalität', meaning: 'Originality', options: ['A: Uniqueness', 'B: Creativity', 'C: Novelty', 'D: Originality'], correct: '🇩' },
  { word: 'Permanenz', meaning: 'Permanence', options: ['A: Continuity', 'B: Stability', 'C: Durability', 'D: Permanence'], correct: '🇩' },
  { word: 'Priorität', meaning: 'Priority', options: ['A: Importance', 'B: Urgency', 'C: Preference', 'D: Priority'], correct: '🇩' },
  { word: 'Rationalität', meaning: 'Rationality', options: ['A: Reason', 'B: Logic', 'C: Sensibility', 'D: Rationality'], correct: '🇩' },
  { word: 'Skepsis', meaning: 'Skepticism', options: ['A: Doubt', 'B: Caution', 'C: Disbelief', 'D: Skepticism'], correct: '🇩' },
  { word: 'Sensibilität', meaning: 'Sensitivity', options: ['A: Awareness', 'B: Compassion', 'C: Sensitivity', 'D: Responsiveness'], correct: '🇩' },
  { word: 'Subtilität', meaning: 'Subtlety', options: ['A: Fineness', 'B: Delicacy', 'C: Refinement', 'D: Subtlety'], correct: '🇩' },
  { word: 'Synergie', meaning: 'Synergy', options: ['A: Cooperation', 'B: Efficiency', 'C: Interaction', 'D: Synergy'], correct: '🇩' },
  { word: 'Toleranz', meaning: 'Tolerance', options: ['A: Acceptance', 'B: Patience', 'C: Openness', 'D: Tolerance'], correct: '🇩' },
  { word: 'Tranzparenz', meaning: 'Transparency', options: ['A: Openness', 'B: Clarity', 'C: Disclosure', 'D: Transparency'], correct: '🇩' },
  { word: 'Universalisierung', meaning: 'Universalization', options: ['A: Globalization', 'B: Unification', 'C: Standardization', 'D: Universalization'], correct: '🇩' },
  { word: 'Verlässlichkeit', meaning: 'Reliability', options: ['A: Dependability', 'B: Trustworthiness', 'C: Consistency', 'D: Reliability'], correct: '🇩' },
  { word: 'Vernunft', meaning: 'Reason', options: ['A: Wisdom', 'B: Understanding', 'C: Logic', 'D: Reason'], correct: '🇩' },
  { word: 'Vertrauen', meaning: 'Trust', options: ['A: Confidence', 'B: Belief', 'C:Assurance', 'D: Trust'], correct: '🇩' },
  { word: 'Wahrnehmung', meaning: 'Perception', options: ['A: Sensibility', 'B: Awareness', 'C: Recognition', 'D: Perception'], correct: '🇩' },
  { word: 'Wissenschaftlichkeit', meaning: 'Scientific methodology', options: ['A: Research', 'B: Study', 'C: Examination', 'D: Scientific methodology'], correct: '🇩' },
  { word: 'Zielstrebigkeit', meaning: 'Determination', options: ['A: Focus', 'B: Persistence', 'C: Dedication', 'D: Goal orientation'], correct: '🇩' },
  { word: 'Emanzipation', meaning: 'Emancipation', options: ['A: Liberation', 'B: Equality', 'C: Autonomy', 'D: Emancipation'], correct: '🇩' },
  { word: 'Heterogenität', meaning: 'Heterogeneity', options: ['A: Diversity', 'B: Variance', 'C: Disparity', 'D: Heterogeneity'], correct: '🇩' },
  { word: 'Pluralismus', meaning: 'Pluralism', options: ['A: Multiplicity', 'B: Diversity', 'C: Variety', 'D: Pluralism'], correct: '🇩' },
  { word: 'Subventionierung', meaning: 'Subsidization', options: ['A: Funding', 'B: Support', 'C: Sponsorship', 'D: Subsidization'], correct: '🇩' },
  { word: 'Determinismus', meaning: 'Determinism', options: ['A: Fatalism', 'B: Causation', 'C: Preordination', 'D: Determinism'], correct: '🇩' },
  { word: 'Kohärenz', meaning: 'Coherence', options: ['A: Connection', 'B: Clarity', 'C: Consistency', 'D: Coherence'], correct: '🇩' },
  { word: 'Prävalenz', meaning: 'Prevalence', options: ['A: Dominance', 'B: Ubiquity', 'C: Frequency', 'D: Prevalence'], correct: '🇩' },
  { word: 'Diskrepanz', meaning: 'Discrepancy', options: ['A: Divergence', 'B: Mismatch', 'C: Inconsistency', 'D: Discrepancy'], correct: '🇩' },
  { word: 'Redundanz', meaning: 'Redundancy', options: ['A: Superfluity', 'B: Repetition', 'C: Overload', 'D: Redundancy'], correct: '🇩' },
  { word: 'Ambivalenz', meaning: 'Ambivalence', options: ['A: Duality', 'B: Contradiction', 'C: Mixed feelings', 'D: Ambivalence'], correct: '🇩' },
  { word: 'Adäquanz', meaning: 'Adequacy', options: ['A: Sufficiency', 'B: Suitability', 'C: Competence', 'D: Adequacy'], correct: '🇩' },
  { word: 'Prospektion', meaning: 'Prospection', options: ['A: Forecasting', 'B: Exploration', 'C: Expectation', 'D: Prospection'], correct: '🇩' },
  { word: 'Konsistenz', meaning: 'Consistency', options: ['A: Uniformity', 'B: Stability', 'C: Solidity', 'D: Consistency'], correct: '🇩' },
  { word: 'Marginalität', meaning: 'Marginality', options: ['A: Insignificance', 'B: Borderline', 'C: Peripheralness', 'D: Marginality'], correct: '🇩' },
  { word: 'Antagonismus', meaning: 'Antagonism', options: ['A: Opposition', 'B: Conflict', 'C: Hostility', 'D: Antagonism'], correct: '🇩' },
  { word: 'Transzendenz', meaning: 'Transcendence', options: ['A: Supremacy', 'B: Surpassing', 'C: Spirituality', 'D: Transcendence'], correct: '🇩' },
  { word: 'Effizienzsteigerung', meaning: 'Efficiency enhancement', options: ['A: Optimization', 'B: Productivity boost', 'C: Effectiveness', 'D: Efficiency enhancement'], correct: '🇩' },
  { word: 'Dekonstruktion', meaning: 'Deconstruction', options: ['A: Breakdown', 'B: Analysis', 'C: Demolition', 'D: Deconstruction'], correct: '🇩' },
  { word: 'Partizipation', meaning: 'Participation', options: ['A: Involvement', 'B: Engagement', 'C: Collaboration', 'D: Participation'], correct: '🇩' },
  { word: 'Divergenz', meaning: 'Divergence', options: ['A: Separation', 'B: Differentiation', 'C: Discrepancy', 'D: Divergence'], correct: '🇩' },
  { word: 'Implikation', meaning: 'Implication', options: ['A: Suggestion', 'B: Consequence', 'C: Inference', 'D: Implication'], correct: '🇩' },
  { word: 'Ambiguität', meaning: 'Ambiguity', options: ['A: Vagueness', 'B: Uncertainty', 'C: Indeterminacy', 'D: Ambiguity'], correct: '🇩' },
  { word: 'Metakognition', meaning: 'Metacognition', options: ['A: Reflection', 'B: Self-awareness', 'C: Understanding', 'D: Metacognition'], correct: '🇩' },
  { word: 'Präzision', meaning: 'Precision', options: ['A: Accuracy', 'B: Exactness', 'C: Rigidity', 'D: Precision'], correct: '🇩' },
  { word: 'Deklaration', meaning: 'Declaration', options: ['A: Statement', 'B: Announcement', 'C: Proclamation', 'D: Declaration'], correct: '🇩' }
  ],
}; 

// Word of the Day data
const wordList = [
  { word: 'die Stadt', meaning: 'City', plural: 'die Städte', indefinite: 'eine Stadt', definite: 'die Stadt' },
  { word: 'der Apfel', meaning: 'An Apple', plural: 'die Äpfel', indefinite: 'ein Apfel', definite: 'der Apfel' },
  { word: 'das Buch', meaning: 'A Book', plural: 'die Bücher', indefinite: 'ein Buch', definite: 'das Buch' },
  { word: 'die Blume', meaning: 'Flower', plural: 'die Blumen', indefinite: 'eine Blume', definite: 'die Blume' },
  { word: 'der Hund', meaning: 'Dog', plural: 'die Hunde', indefinite: 'ein Hund', definite: 'der Hund' },
  { word: 'die Katze', meaning: 'Cat', plural: 'die Katzen', indefinite: 'eine Katze', definite: 'die Katze' },
  { word: 'das Haus', meaning: 'House', plural: 'die Häuser', indefinite: 'ein Haus', definite: 'das Haus' },
  { word: 'die Schule', meaning: 'School', plural: 'die Schulen', indefinite: 'eine Schule', definite: 'die Schule' },
  { word: 'der Tisch', meaning: 'Table', plural: 'die Tische', indefinite: 'ein Tisch', definite: 'der Tisch' },
  { word: 'die Lampe', meaning: 'Lamp', plural: 'die Lampen', indefinite: 'eine Lampe', definite: 'die Lampe' },
  { word: 'das Auto', meaning: 'Car', plural: 'die Autos', indefinite: 'ein Auto', definite: 'das Auto' },
  { word: 'die Tasche', meaning: 'Bag', plural: 'die Taschen', indefinite: 'eine Tasche', definite: 'die Tasche' },
  { word: 'der Stuhl', meaning: 'Chair', plural: 'die Stühle', indefinite: 'ein Stuhl', definite: 'der Stuhl' },
  { word: 'das Fenster', meaning: 'Window', plural: 'die Fenster', indefinite: 'ein Fenster', definite: 'das Fenster' },
  { word: 'die Wand', meaning: 'Wall', plural: 'die Wände', indefinite: 'eine Wand', definite: 'die Wand' },
  { word: 'die Tür', meaning: 'Door', plural: 'die Türen', indefinite: 'eine Tür', definite: 'die Tür' },
  { word: 'der Lehrer', meaning: 'Teacher (Male)', plural: 'die Lehrer', indefinite: 'ein Lehrer', definite: 'der Lehrer' },  { word: 'die Lehrerin', meaning: 'Teacher (Female)', plural: 'die Lehrerinnen', indefinite: 'eine Lehrerin', definite: 'die Lehrerin' },
  { word: 'die Zeit', meaning: 'Time', plural: 'die Zeiten', indefinite: 'eine Zeit', definite: 'die Zeit' },
  { word: 'das Wasser', meaning: 'Water', plural: 'die Wasser', indefinite: 'ein Wasser', definite: 'das Wasser' },
  { word: 'der Tag', meaning: 'Day', plural: 'die Tage', indefinite: 'ein Tag', definite: 'der Tag' },
  { word: 'die Nacht', meaning: 'Night', plural: 'die Nächte', indefinite: 'eine Nacht', definite: 'die Nacht' },
};

// Word of the Day Data for German
const germanWordList = [
  { word: "Hund", meaning: "Dog", plural: "Hunde", indefinite: "ein", definite: "der" },
  { word: "Buch", meaning: "Book", plural: "Bücher", indefinite: "ein", definite: "das" },
  { word: "Meer", meaning: "Sea", plural: "Meere", indefinite: "ein", definite: "das" }
];

module.exports = { germanQuizData, germanWordList };