// Russian Quiz Data
const russianQuizData = {
    A1: [
        { word: "Кошка", options: ["Cat", "Dog", "Bird", "Fish"], correct: "Cat" },
    { word: "Дом", options: ["House", "Tree", "Car", "School"], correct: "House" },
    { word: "Собака", options: ["Dog", "Mouse", "Cow", "Rabbit"], correct: "Dog" },
    { word: "Книга", options: ["Book", "Notebook", "Table", "Chair"], correct: "Book" },
    { word: "Ручка", options: ["Pen", "Pencil", "Marker", "Eraser"], correct: "Pen" },
    { word: "Окно", options: ["Window", "Door", "Wall", "Roof"], correct: "Window" },
    { word: "Стол", options: ["Table", "Lamp", "Chair", "Sofa"], correct: "Table" },
    { word: "Ложка", options: ["Spoon", "Knife", "Fork", "Plate"], correct: "Spoon" },
    { word: "Вода", options: ["Water", "Juice", "Tea", "Milk"], correct: "Water" },
    { word: "Молоко", options: ["Milk", "Coffee", "Soda", "Wine"], correct: "Milk" },
    { word: "Рыба", options: ["Fish", "Meat", "Bread", "Egg"], correct: "Fish" },
    { word: "Яйцо", options: ["Egg", "Cheese", "Butter", "Cream"], correct: "Egg" },
    { word: "Чай", options: ["Tea", "Coffee", "Juice", "Milk"], correct: "Tea" },
    { word: "Хлеб", options: ["Bread", "Cake", "Pie", "Cookie"], correct: "Bread" },
    { word: "Сыр", options: ["Cheese", "Butter", "Cream", "Milk"], correct: "Cheese" },
    { word: "Кровать", options: ["Bed", "Sofa", "Chair", "Table"], correct: "Bed" },
    { word: "Стул", options: ["Chair", "Desk", "Couch", "Bench"], correct: "Chair" },
    { word: "Дверь", options: ["Door", "Window", "Wall", "Roof"], correct: "Door" },
    { word: "Город", options: ["City", "Village", "Street", "Park"], correct: "City" },
    { word: "Море", options: ["Sea", "Lake", "River", "Ocean"], correct: "Sea" },
    { word: "Солнце", options: ["Sun", "Moon", "Star", "Cloud"], correct: "Sun" },
    { word: "Луна", options: ["Moon", "Star", "Planet", "Galaxy"], correct: "Moon" },
    { word: "Облако", options: ["Cloud", "Sky", "Rain", "Snow"], correct: "Cloud" },
    { word: "Звезда", options: ["Star", "Planet", "Moon", "Sun"], correct: "Star" },
    { word: "Машина", options: ["Car", "Bike", "Bus", "Train"], correct: "Car" },
    { word: "Поезд", options: ["Train", "Bus", "Car", "Plane"], correct: "Train" },
    { word: "Самолёт", options: ["Plane", "Helicopter", "Car", "Bike"], correct: "Plane" },
    { word: "Автобус", options: ["Bus", "Car", "Train", "Boat"], correct: "Bus" },
    { word: "Человек", options: ["Person", "Child", "Woman", "Man"], correct: "Person" },
    { word: "Ребёнок", options: ["Child", "Baby", "Adult", "Teenager"], correct: "Child" },
    { word: "Мальчик", options: ["Boy", "Girl", "Man", "Baby"], correct: "Boy" },
    { word: "Девочка", options: ["Girl", "Boy", "Baby", "Woman"], correct: "Girl" },
    { word: "Женщина", options: ["Woman", "Girl", "Man", "Child"], correct: "Woman" },
    { word: "Мужчина", options: ["Man", "Boy", "Girl", "Person"], correct: "Man" },
    { word: "Семья", options: ["Family", "Friends", "Neighbors", "Guests"], correct: "Family" },
    { word: "Друзья", options: ["Friends", "Family", "Strangers", "Guests"], correct: "Friends" },
    { word: "Школа", options: ["School", "Library", "University", "College"], correct: "School" },
    { word: "Учитель", options: ["Teacher", "Student", "Principal", "Coach"], correct: "Teacher" },
    { word: "Студент", options: ["Student", "Teacher", "Child", "Principal"], correct: "Student" },
    { word: "Книга", options: ["Book", "Notebook", "Paper", "Magazine"], correct: "Book" },
    { word: "Тетрадь", options: ["Notebook", "Paper", "Book", "Folder"], correct: "Notebook" },
    { word: "Парк", options: ["Park", "Street", "Forest", "Garden"], correct: "Park" },
    { word: "Улица", options: ["Street", "Park", "Road", "Lane"], correct: "Street" },
    { word: "Магазин", options: ["Store", "Market", "Mall", "Shop"], correct: "Store" },
    { word: "Рынок", options: ["Market", "Store", "Street", "Shop"], correct: "Market" },
    { word: "Время", options: ["Time", "Day", "Hour", "Minute"], correct: "Time" },
    { word: "День", options: ["Day", "Night", "Morning", "Evening"], correct: "Day" },
    { word: "Ночь", options: ["Night", "Day", "Morning", "Afternoon"], correct: "Night" },
    { word: "Минута", options: ["Minute", "Hour", "Second", "Time"], correct: "Minute" },
    { word: "Час", options: ["Hour", "Minute", "Day", "Week"], correct: "Hour" },
    { word: "Неделя", options: ["Week", "Month", "Year", "Day"], correct: "Week" },
    { word: "Месяц", options: ["Month", "Year", "Week", "Day"], correct: "Month" },
    { word: "Год", options: ["Year", "Month", "Decade", "Century"], correct: "Year" },{ word: "Яблоко", options: ["Apple", "Pear", "Banana", "Orange"], correct: "Apple" },
    { word: "Апельсин", options: ["Orange", "Grapefruit", "Lemon", "Peach"], correct: "Orange" },
    { word: "Суп", options: ["Soup", "Salad", "Bread", "Rice"], correct: "Soup" },
    { word: "Сад", options: ["Garden", "Park", "Forest", "Street"], correct: "Garden" },
    { word: "Цветок", options: ["Flower", "Tree", "Grass", "Bush"], correct: "Flower" },
    { word: "Дерево", options: ["Tree", "Plant", "Forest", "Grass"], correct: "Tree" },
    { word: "Трава", options: ["Grass", "Bush", "Flower", "Tree"], correct: "Grass" },
    { word: "Карандаш", options: ["Pencil", "Pen", "Eraser", "Marker"], correct: "Pencil" },
    { word: "Тетрадь", options: ["Notebook", "Book", "Paper", "Folder"], correct: "Notebook" },
    { word: "Класс", options: ["Classroom", "School", "Library", "Gym"], correct: "Classroom" },
    { word: "Звонок", options: ["Bell", "Phone", "Door", "Clock"], correct: "Bell" },
    { word: "Ручка", options: ["Pen", "Pencil", "Marker", "Brush"], correct: "Pen" },
    { word: "Карта", options: ["Map", "Card", "Paper", "Passport"], correct: "Map" },
    { word: "Страна", options: ["Country", "City", "Village", "Town"], correct: "Country" },
    { word: "Город", options: ["City", "Village", "Town", "Street"], correct: "City" },
    { word: "Улица", options: ["Street", "Avenue", "Road", "Path"], correct: "Street" },
    { word: "Река", options: ["River", "Lake", "Sea", "Stream"], correct: "River" },
    { word: "Озеро", options: ["Lake", "River", "Ocean", "Sea"], correct: "Lake" },
    { word: "Море", options: ["Sea", "Lake", "Ocean", "River"], correct: "Sea" },
    { word: "Пляж", options: ["Beach", "Park", "Island", "Coast"], correct: "Beach" },
    { word: "Гора", options: ["Mountain", "Hill", "Valley", "Cliff"], correct: "Mountain" },
    { word: "Лес", options: ["Forest", "Jungle", "Park", "Garden"], correct: "Forest" },
    { word: "Зима", options: ["Winter", "Spring", "Summer", "Autumn"], correct: "Winter" },
    { word: "Весна", options: ["Spring", "Winter", "Summer", "Autumn"], correct: "Spring" },
    { word: "Лето", options: ["Summer", "Winter", "Autumn", "Spring"], correct: "Summer" },
    { word: "Осень", options: ["Autumn", "Spring", "Summer", "Winter"], correct: "Autumn" },
    { word: "Деньги", options: ["Money", "Card", "Wallet", "Cash"], correct: "Money" },
    { word: "Кошелёк", options: ["Wallet", "Bag", "Purse", "Case"], correct: "Wallet" },
    { word: "Сумка", options: ["Bag", "Suitcase", "Box", "Backpack"], correct: "Bag" },
    { word: "Подарок", options: ["Gift", "Card", "Box", "Flower"], correct: "Gift" },
    { word: "Кино", options: ["Cinema", "Movie", "Theater", "Show"], correct: "Cinema" },
    { word: "Фильм", options: ["Movie", "Show", "Series", "Theater"], correct: "Movie" },
    { word: "Театр", options: ["Theater", "Cinema", "Opera", "Concert"], correct: "Theater" },
    { word: "Музыка", options: ["Music", "Song", "Sound", "Instrument"], correct: "Music" },
    { word: "Инструмент", options: ["Instrument", "Tool", "Device", "Machine"], correct: "Instrument" },
    { word: "Машина", options: ["Car", "Bike", "Bus", "Train"], correct: "Car" },
    { word: "Автобус", options: ["Bus", "Train", "Car", "Bike"], correct: "Bus" },
    { word: "Поезд", options: ["Train", "Bus", "Car", "Bike"], correct: "Train" },
    { word: "Самолёт", options: ["Plane", "Helicopter", "Rocket", "Balloon"], correct: "Plane" },
    { word: "Ракета", options: ["Rocket", "Plane", "Balloon", "Satellite"], correct: "Rocket" },
    { word: "Человек", options: ["Person", "Child", "Man", "Woman"], correct: "Person" },
    { word: "Ребёнок", options: ["Child", "Baby", "Adult", "Teen"], correct: "Child" },
    { word: "Женщина", options: ["Woman", "Girl", "Lady", "Sister"], correct: "Woman" },
    { word: "Мужчина", options: ["Man", "Boy", "Gentleman", "Brother"], correct: "Man" },
    { word: "Друзья", options: ["Friends", "Neighbors", "Guests", "Family"], correct: "Friends" },
    { word: "Школа", options: ["School", "Library", "College", "Gym"], correct: "School" },
    { word: "Учитель", options: ["Teacher", "Student", "Principal", "Coach"], correct: "Teacher" },
    { word: "Время", options: ["Time", "Hour", "Minute", "Day"], correct: "Time" },
    { word: "День", options: ["Day", "Night", "Morning", "Evening"], correct: "Day" },
    { word: "Ночь", options: ["Night", "Day", "Afternoon", "Dusk"], correct: "Night" }
    ],
    A2: [
        { word: "Университет", options: ["University", "School", "Library", "College"], correct: "University" },
    { word: "Общежитие", options: ["Dormitory", "Apartment", "House", "Hotel"], correct: "Dormitory" },
    { word: "Экзамен", options: ["Exam", "Homework", "Test", "Lecture"], correct: "Exam" },
    { word: "Лекция", options: ["Lecture", "Seminar", "Workshop", "Class"], correct: "Lecture" },
    { word: "Студент", options: ["Student", "Teacher", "Principal", "Coach"], correct: "Student" },
    { word: "Кафе", options: ["Cafe", "Restaurant", "Bar", "Store"], correct: "Cafe" },
    { word: "Ресторан", options: ["Restaurant", "Cafe", "Bar", "Market"], correct: "Restaurant" },
    { word: "Меню", options: ["Menu", "Bill", "Order", "Recipe"], correct: "Menu" },
    { word: "Официант", options: ["Waiter", "Cook", "Manager", "Cashier"], correct: "Waiter" },
    { word: "Счёт", options: ["Bill", "Card", "Cash", "Check"], correct: "Bill" },
    { word: "Магазин", options: ["Store", "Market", "Shop", "Mall"], correct: "Store" },
    { word: "Покупка", options: ["Purchase", "Sale", "Discount", "Gift"], correct: "Purchase" },
    { word: "День рождения", options: ["Birthday", "Anniversary", "Holiday", "Party"], correct: "Birthday" },
    { word: "Праздник", options: ["Holiday", "Celebration", "Weekend", "Event"], correct: "Holiday" },
    { word: "Путешествие", options: ["Travel", "Journey", "Vacation", "Adventure"], correct: "Travel" },
    { word: "Отдых", options: ["Rest", "Work", "Vacation", "Sleep"], correct: "Rest" },
    { word: "Квартира", options: ["Apartment", "House", "Dormitory", "Office"], correct: "Apartment" },
    { word: "Дом", options: ["House", "Building", "Office", "Apartment"], correct: "House" },
    { word: "Мебель", options: ["Furniture", "Table", "Chair", "Couch"], correct: "Furniture" },
    { word: "Кухня", options: ["Kitchen", "Room", "Bathroom", "Dining room"], correct: "Kitchen" },
    { word: "Гостиная", options: ["Living room", "Bedroom", "Office", "Kitchen"], correct: "Living room" },
    { word: "Спальня", options: ["Bedroom", "Bathroom", "Living room", "Hallway"], correct: "Bedroom" },
    { word: "Кровать", options: ["Bed", "Sofa", "Chair", "Table"], correct: "Bed" },
    { word: "Диван", options: ["Sofa", "Chair", "Table", "Desk"], correct: "Sofa" },
    { word: "Одежда", options: ["Clothing", "Shoes", "Hat", "Scarf"], correct: "Clothing" },
    { word: "Обувь", options: ["Shoes", "Clothing", "Boots", "Socks"], correct: "Shoes" },
    { word: "Шапка", options: ["Hat", "Scarf", "Gloves", "Jacket"], correct: "Hat" },
    { word: "Шарф", options: ["Scarf", "Hat", "Gloves", "Coat"], correct: "Scarf" },
    { word: "Пальто", options: ["Coat", "Jacket", "Sweater", "Shirt"], correct: "Coat" },
    { word: "Свитер", options: ["Sweater", "T-shirt", "Jacket", "Shirt"], correct: "Sweater" },
    { word: "Погода", options: ["Weather", "Rain", "Snow", "Temperature"], correct: "Weather" },
    { word: "Дождь", options: ["Rain", "Snow", "Fog", "Cloud"], correct: "Rain" },
    { word: "Снег", options: ["Snow", "Rain", "Hail", "Storm"], correct: "Snow" },
    { word: "Ветер", options: ["Wind", "Storm", "Breeze", "Air"], correct: "Wind" },
    { word: "Солнце", options: ["Sun", "Moon", "Sky", "Light"], correct: "Sun" },
    { word: "Луна", options: ["Moon", "Sun", "Star", "Sky"], correct: "Moon" },
    { word: "Звезда", options: ["Star", "Moon", "Planet", "Galaxy"], correct: "Star" },
    { word: "Космос", options: ["Space", "Sky", "Galaxy", "Universe"], correct: "Space" },
    { word: "Планета", options: ["Planet", "Star", "Moon", "Sun"], correct: "Planet" },
    { word: "Мир", options: ["World", "Earth", "Country", "Planet"], correct: "World" },
    { word: "Столица", options: ["Capital", "City", "Town", "Village"], correct: "Capital" },
    { word: "Деревня", options: ["Village", "City", "Town", "Street"], correct: "Village" },
    { word: "Семья", options: ["Family", "Friends", "Neighbors", "Relatives"], correct: "Family" },
    { word: "Родители", options: ["Parents", "Children", "Relatives", "Siblings"], correct: "Parents" },
    { word: "Бабушка", options: ["Grandmother", "Mother", "Aunt", "Sister"], correct: "Grandmother" },
    { word: "Дедушка", options: ["Grandfather", "Father", "Uncle", "Brother"], correct: "Grandfather" },
    { word: "Брат", options: ["Brother", "Sister", "Cousin", "Friend"], correct: "Brother" },
    { word: "Сестра", options: ["Sister", "Aunt", "Friend", "Cousin"], correct: "Sister" },
    { word: "Еда", options: ["Food", "Drink", "Meal", "Dish"], correct: "Food" },
    { word: "Напиток", options: ["Drink", "Food", "Meal", "Snack"], correct: "Drink" },{ word: "Учебник", options: ["Textbook", "Notebook", "Pen", "Folder"], correct: "Textbook" },
    { word: "Ручка", options: ["Pen", "Pencil", "Marker", "Eraser"], correct: "Pen" },
    { word: "Карандаш", options: ["Pencil", "Pen", "Brush", "Chalk"], correct: "Pencil" },
    { word: "Библиотека", options: ["Library", "Bookstore", "Classroom", "Museum"], correct: "Library" },
    { word: "Словарь", options: ["Dictionary", "Notebook", "Workbook", "Book"], correct: "Dictionary" },
    { word: "Тетрадь", options: ["Notebook", "Textbook", "Paper", "Binder"], correct: "Notebook" },
    { word: "Школа", options: ["School", "Classroom", "University", "Library"], correct: "School" },
    { word: "Класс", options: ["Classroom", "Lecture Hall", "Office", "Dorm"], correct: "Classroom" },
    { word: "Расписание", options: ["Schedule", "Timetable", "Agenda", "Calendar"], correct: "Schedule" },
    { word: "Урок", options: ["Lesson", "Break", "Test", "Exam"], correct: "Lesson" },
    { word: "Театр", options: ["Theater", "Cinema", "Concert", "Stage"], correct: "Theater" },
    { word: "Кино", options: ["Cinema", "Film", "Theater", "Play"], correct: "Cinema" },
    { word: "Фильм", options: ["Film", "Movie", "Series", "Show"], correct: "Film" },
    { word: "Музыка", options: ["Music", "Song", "Sound", "Melody"], correct: "Music" },
    { word: "Песня", options: ["Song", "Poem", "Melody", "Voice"], correct: "Song" },
    { word: "Художник", options: ["Artist", "Painter", "Writer", "Sculptor"], correct: "Artist" },
    { word: "Книга", options: ["Book", "Magazine", "Journal", "Paper"], correct: "Book" },
    { word: "Журнал", options: ["Magazine", "Book", "Newspaper", "Diary"], correct: "Magazine" },
    { word: "Газета", options: ["Newspaper", "Magazine", "Article", "Brochure"], correct: "Newspaper" },
    { word: "Спорт", options: ["Sport", "Game", "Exercise", "Competition"], correct: "Sport" },
    { word: "Футбол", options: ["Football", "Basketball", "Tennis", "Hockey"], correct: "Football" },
    { word: "Теннис", options: ["Tennis", "Table Tennis", "Badminton", "Squash"], correct: "Tennis" },
    { word: "Бег", options: ["Running", "Walking", "Jogging", "Sprinting"], correct: "Running" },
    { word: "Тренировка", options: ["Workout", "Exercise", "Practice", "Training"], correct: "Workout" },
    { word: "Плавание", options: ["Swimming", "Diving", "Rowing", "Sailing"], correct: "Swimming" },
    { word: "Соревнование", options: ["Competition", "Game", "Match", "Tournament"], correct: "Competition" },
    { word: "Велосипед", options: ["Bicycle", "Car", "Motorbike", "Scooter"], correct: "Bicycle" },
    { word: "Автобус", options: ["Bus", "Train", "Tram", "Taxi"], correct: "Bus" },
    { word: "Поезд", options: ["Train", "Bus", "Metro", "Tram"], correct: "Train" },
    { word: "Метро", options: ["Metro", "Train", "Bus", "Subway"], correct: "Metro" },
    { word: "Такси", options: ["Taxi", "Bus", "Car", "Ride"], correct: "Taxi" },
    { word: "Вокзал", options: ["Station", "Airport", "Stop", "Terminal"], correct: "Station" },
    { word: "Аэропорт", options: ["Airport", "Runway", "Terminal", "Flight"], correct: "Airport" },
    { word: "Самолёт", options: ["Airplane", "Helicopter", "Train", "Ship"], correct: "Airplane" },
    { word: "Корабль", options: ["Ship", "Boat", "Submarine", "Yacht"], correct: "Ship" },
    { word: "Вода", options: ["Water", "Juice", "Milk", "Tea"], correct: "Water" },
    { word: "Сок", options: ["Juice", "Water", "Soda", "Milk"], correct: "Juice" },
    { word: "Чай", options: ["Tea", "Coffee", "Milk", "Juice"], correct: "Tea" },
    { word: "Кофе", options: ["Coffee", "Tea", "Hot Chocolate", "Juice"], correct: "Coffee" },
    { word: "Молоко", options: ["Milk", "Water", "Juice", "Soda"], correct: "Milk" },
    { word: "Хлеб", options: ["Bread", "Roll", "Bagel", "Cake"], correct: "Bread" },
    { word: "Мясо", options: ["Meat", "Chicken", "Fish", "Pork"], correct: "Meat" },
    { word: "Курица", options: ["Chicken", "Fish", "Pork", "Beef"], correct: "Chicken" },
    { word: "Рыба", options: ["Fish", "Chicken", "Beef", "Pork"], correct: "Fish" },
    { word: "Суп", options: ["Soup", "Stew", "Salad", "Rice"], correct: "Soup" },
    { word: "Салат", options: ["Salad", "Soup", "Rice", "Pasta"], correct: "Salad" },
    { word: "Паста", options: ["Pasta", "Rice", "Soup", "Bread"], correct: "Pasta" },
    { word: "Рис", options: ["Rice", "Pasta", "Bread", "Soup"], correct: "Rice" }
    ],
    B1: [
        { word: "Друзья", options: ["Friends", "Family", "Colleagues", "Neighbors"], correct: "Friends" },
    { word: "Праздник", options: ["Holiday", "Event", "Festival", "Celebration"], correct: "Holiday" },
    { word: "Работа", options: ["Work", "Job", "Project", "Task"], correct: "Work" },
    { word: "Отпуск", options: ["Vacation", "Holiday", "Break", "Rest"], correct: "Vacation" },
    { word: "Туризм", options: ["Tourism", "Travel", "Vacation", "Exploration"], correct: "Tourism" },
    { word: "Музей", options: ["Museum", "Gallery", "Exhibition", "Monument"], correct: "Museum" },
    { word: "Кино", options: ["Cinema", "Theater", "Movie", "Film"], correct: "Cinema" },
    { word: "Книга", options: ["Book", "Novel", "Story", "Journal"], correct: "Book" },
    { word: "Живопись", options: ["Painting", "Art", "Drawing", "Sculpture"], correct: "Painting" },
    { word: "Музыка", options: ["Music", "Song", "Melody", "Tune"], correct: "Music" },
    { word: "Спорт", options: ["Sport", "Exercise", "Game", "Competition"], correct: "Sport" },
    { word: "Футбол", options: ["Football", "Basketball", "Tennis", "Volleyball"], correct: "Football" },
    { word: "Тренировка", options: ["Training", "Exercise", "Workout", "Practice"], correct: "Training" },
    { word: "Соревнование", options: ["Competition", "Contest", "Match", "Challenge"], correct: "Competition" },
    { word: "Рекорд", options: ["Record", "Achievement", "Goal", "Result"], correct: "Record" },
    { word: "Команда", options: ["Team", "Group", "Squad", "Club"], correct: "Team" },
    { word: "Лидер", options: ["Leader", "Captain", "Coach", "Manager"], correct: "Leader" },
    { word: "Участник", options: ["Participant", "Player", "Member", "Contestant"], correct: "Participant" },
    { word: "Зритель", options: ["Spectator", "Audience", "Viewer", "Listener"], correct: "Spectator" },
    { word: "Приз", options: ["Prize", "Reward", "Award", "Trophy"], correct: "Prize" },
    { word: "Победа", options: ["Victory", "Win", "Success", "Achievement"], correct: "Victory" },
    { word: "Поражение", options: ["Defeat", "Loss", "Failure", "Setback"], correct: "Defeat" },
    { word: "Школа", options: ["School", "University", "College", "Academy"], correct: "School" },
    { word: "Урок", options: ["Lesson", "Class", "Lecture", "Session"], correct: "Lesson" },
    { word: "Учёба", options: ["Study", "Learning", "Schooling", "Education"], correct: "Study" },
    { word: "Задание", options: ["Task", "Assignment", "Project", "Exercise"], correct: "Task" },
    { word: "Экзамен", options: ["Exam", "Test", "Quiz", "Assessment"], correct: "Exam" },
    { word: "Библиотека", options: ["Library", "Study", "Reading", "Room"], correct: "Library" },
    { word: "Учитель", options: ["Teacher", "Instructor", "Tutor", "Mentor"], correct: "Teacher" },
    { word: "Студент", options: ["Student", "Pupil", "Learner", "Scholar"], correct: "Student" },
    { word: "Преподаватель", options: ["Lecturer", "Professor", "Teacher", "Tutor"], correct: "Lecturer" },
    { word: "Знания", options: ["Knowledge", "Information", "Skills", "Understanding"], correct: "Knowledge" },
    { word: "Умение", options: ["Skill", "Ability", "Talent", "Expertise"], correct: "Skill" },
    { word: "Грамматика", options: ["Grammar", "Syntax", "Structure", "Language"], correct: "Grammar" },
    { word: "Лексика", options: ["Vocabulary", "Lexicon", "Words", "Terminology"], correct: "Vocabulary" },
    { word: "Перевод", options: ["Translation", "Interpretation", "Conversion", "Switch"], correct: "Translation" },
    { word: "Язык", options: ["Language", "Speech", "Tongue", "Dialect"], correct: "Language" },
    { word: "Статья", options: ["Article", "Post", "Essay", "Paper"], correct: "Article" },
    { word: "Газета", options: ["Newspaper", "Magazine", "Journal", "Press"], correct: "Newspaper" },
    { word: "Интернет", options: ["Internet", "Web", "Network", "Online"], correct: "Internet" },
    { word: "Технология", options: ["Technology", "Tech", "Innovation", "Development"], correct: "Technology" },
    { word: "Наука", options: ["Science", "Knowledge", "Research", "Experiment"], correct: "Science" },
    { word: "Робот", options: ["Robot", "Machine", "Automaton", "Android"], correct: "Robot" },
    { word: "Компьютер", options: ["Computer", "PC", "Laptop", "Device"], correct: "Computer" },
    { word: "Машина", options: ["Car", "Machine", "Vehicle", "Engine"], correct: "Car" },
    { word: "Мобильный", options: ["Mobile", "Portable", "Cell", "Handheld"], correct: "Mobile" },
    { word: "Гаджет", options: ["Gadget", "Device", "Tool", "Invention"], correct: "Gadget" },
    { word: "Телефон", options: ["Phone", "Mobile", "Cell", "Smartphone"], correct: "Phone" },
    { word: "Фотоаппарат", options: ["Camera", "Photograph", "Snapshot", "Picture"], correct: "Camera" },
    { word: "Фото", options: ["Photo", "Picture", "Image", "Shot"], correct: "Photo" },
    { word: "Камера", options: ["Camera", "Lens", "Recorder", "Device"], correct: "Camera" },
    { word: "Платформа", options: ["Platform", "Stage", "Base", "System"], correct: "Platform" },
    { word: "Сайт", options: ["Website", "Page", "Site", "Portal"], correct: "Website" },
    { word: "Текст", options: ["Text", "Content", "Message", "Script"], correct: "Text" },
    { word: "Письмо", options: ["Letter", "Message", "Note", "Email"], correct: "Letter" },
    { word: "Курс", options: ["Course", "Training", "Study", "Class"], correct: "Course" },
    { word: "Рейтинг", options: ["Rating", "Ranking", "Score", "Position"], correct: "Rating" },{ word: "Поездка", options: ["Trip", "Journey", "Travel", "Excursion"], correct: "Trip" },
    { word: "Город", options: ["City", "Town", "Village", "District"], correct: "City" },
    { word: "Река", options: ["River", "Lake", "Stream", "Sea"], correct: "River" },
    { word: "Озеро", options: ["Lake", "Pond", "Stream", "Bay"], correct: "Lake" },
    { word: "Погода", options: ["Weather", "Climate", "Season", "Forecast"], correct: "Weather" },
    { word: "Зима", options: ["Winter", "Spring", "Summer", "Autumn"], correct: "Winter" },
    { word: "Лето", options: ["Summer", "Spring", "Autumn", "Winter"], correct: "Summer" },
    { word: "Осень", options: ["Autumn", "Fall", "Spring", "Winter"], correct: "Autumn" },
    { word: "Весна", options: ["Spring", "Summer", "Winter", "Autumn"], correct: "Spring" },
    { word: "Горы", options: ["Mountains", "Hills", "Valleys", "Rivers"], correct: "Mountains" },
    { word: "Пляж", options: ["Beach", "Shore", "Coast", "Cliff"], correct: "Beach" },
    { word: "Море", options: ["Sea", "Ocean", "Lake", "River"], correct: "Sea" },
    { word: "Остров", options: ["Island", "Continent", "Peninsula", "Coast"], correct: "Island" },
    { word: "Дорога", options: ["Road", "Street", "Path", "Way"], correct: "Road" },
    { word: "Мост", options: ["Bridge", "Tunnel", "Road", "Passage"], correct: "Bridge" },
    { word: "Автобус", options: ["Bus", "Car", "Tram", "Train"], correct: "Bus" },
    { word: "Поезд", options: ["Train", "Bus", "Car", "Plane"], correct: "Train" },
    { word: "Самолет", options: ["Plane", "Helicopter", "Jet", "Glider"], correct: "Plane" },
    { word: "Такси", options: ["Taxi", "Car", "Bus", "Bike"], correct: "Taxi" },
    { word: "Пешком", options: ["On foot", "By car", "By bus", "On bike"], correct: "On foot" },
    { word: "Велосипед", options: ["Bicycle", "Car", "Motorcycle", "Skates"], correct: "Bicycle" },
    { word: "Пешеход", options: ["Pedestrian", "Driver", "Cyclist", "Passenger"], correct: "Pedestrian" },
    { word: "Трафик", options: ["Traffic", "Flow", "Route", "Way"], correct: "Traffic" },
    { word: "Заправка", options: ["Gas station", "Rest stop", "Roadside", "Hotel"], correct: "Gas station" },
    { word: "Отель", options: ["Hotel", "Hostel", "Guesthouse", "Inn"], correct: "Hotel" },
    { word: "Ресторан", options: ["Restaurant", "Café", "Bistro", "Pub"], correct: "Restaurant" },
    { word: "Меню", options: ["Menu", "Card", "List", "Bill"], correct: "Menu" },
    { word: "Блюдо", options: ["Dish", "Course", "Meal", "Snack"], correct: "Dish" },
    { word: "Напиток", options: ["Drink", "Juice", "Coffee", "Tea"], correct: "Drink" },
    { word: "Салат", options: ["Salad", "Soup", "Stew", "Dessert"], correct: "Salad" },
    { word: "Суп", options: ["Soup", "Salad", "Stew", "Main course"], correct: "Soup" },
    { word: "Десерт", options: ["Dessert", "Cake", "Pastry", "Pie"], correct: "Dessert" },
    { word: "Шоколад", options: ["Chocolate", "Candy", "Sweet", "Cookie"], correct: "Chocolate" },
    { word: "Фрукты", options: ["Fruits", "Vegetables", "Berries", "Nuts"], correct: "Fruits" },
    { word: "Овощи", options: ["Vegetables", "Fruits", "Herbs", "Spices"], correct: "Vegetables" },
    { word: "Мясо", options: ["Meat", "Fish", "Poultry", "Vegetables"], correct: "Meat" },
    { word: "Рыба", options: ["Fish", "Meat", "Seafood", "Poultry"], correct: "Fish" },
    { word: "Яйцо", options: ["Egg", "Fruit", "Nut", "Berry"], correct: "Egg" },
    { word: "Молоко", options: ["Milk", "Juice", "Water", "Tea"], correct: "Milk" },
    { word: "Хлеб", options: ["Bread", "Cake", "Pastry", "Biscuit"], correct: "Bread" },
    { word: "Сыр", options: ["Cheese", "Butter", "Cream", "Yogurt"], correct: "Cheese" },
    { word: "Масло", options: ["Butter", "Cheese", "Oil", "Cream"], correct: "Butter" },
    { word: "Картофель", options: ["Potato", "Tomato", "Cucumber", "Carrot"], correct: "Potato" },
    { word: "Морковь", options: ["Carrot", "Cucumber", "Tomato", "Pepper"], correct: "Carrot" },
    { word: "Лук", options: ["Onion", "Garlic", "Pepper", "Tomato"], correct: "Onion" },
    { word: "Чеснок", options: ["Garlic", "Onion", "Cucumber", "Pepper"], correct: "Garlic" },
    { word: "Сахар", options: ["Sugar", "Salt", "Honey", "Pepper"], correct: "Sugar" },
    { word: "Соль", options: ["Salt", "Sugar", "Pepper", "Vinegar"], correct: "Salt" },
    { word: "Перец", options: ["Pepper", "Salt", "Chili", "Spice"], correct: "Pepper" },
    { word: "Ужин", options: ["Dinner", "Lunch", "Breakfast", "Snack"], correct: "Dinner" },
    { word: "Завтрак", options: ["Breakfast", "Brunch", "Snack", "Dinner"], correct: "Breakfast" },
    { word: "Полдник", options: ["Tea time", "Snack", "Brunch", "Evening meal"], correct: "Tea time" },
    { word: "Утро", options: ["Morning", "Night", "Afternoon", "Noon"], correct: "Morning" },
    { word: "Вечер", options: ["Evening", "Night", "Afternoon", "Morning"], correct: "Evening" },
    { word: "Ночь", options: ["Night", "Evening", "Day", "Morning"], correct: "Night" },
    { word: "День", options: ["Day", "Morning", "Afternoon", "Night"], correct: "Day" },
    { word: "Время", options: ["Time", "Clock", "Moment", "Hour"], correct: "Time" },
    { word: "Часы", options: ["Clock", "Watches", "Hour", "Time"], correct: "Clock" },
    { word: "Минуты", options: ["Minutes", "Hours", "Seconds", "Days"], correct: "Minutes" },
    { word: "Секунды", options: ["Seconds", "Minutes", "Hours", "Moments"], correct: "Seconds" },
    { word: "Год", options: ["Year", "Month", "Day", "Week"], correct: "Year" },
    { word: "Месяц", options: ["Month", "Day", "Week", "Year"], correct: "Month" },
    { word: "Неделя", options: ["Week", "Day", "Month", "Year"], correct: "Week" },
    { word: "Сезон", options: ["Season", "Year", "Month", "Week"], correct: "Season" },
    { word: "Календарь", options: ["Calendar", "Clock", "Schedule", "Diary"], correct: "Calendar" }
    ],
    B2: [
        { word: "Образование", options: ["Education", "Study", "Learning", "Knowledge"], correct: "Education" },
    { word: "Опыт", options: ["Experience", "Experiment", "Knowledge", "Skill"], correct: "Experience" },
    { word: "Успех", options: ["Success", "Failure", "Achievement", "Progress"], correct: "Success" },
    { word: "Технология", options: ["Technology", "Innovation", "Engineering", "Technique"], correct: "Technology" },
    { word: "Научный", options: ["Scientific", "Academic", "Technological", "Research"], correct: "Scientific" },
    { word: "Экономика", options: ["Economics", "Finance", "Business", "Trade"], correct: "Economics" },
    { word: "Политика", options: ["Politics", "Government", "Law", "Diplomacy"], correct: "Politics" },
    { word: "Здоровье", options: ["Health", "Fitness", "Wellness", "Medicine"], correct: "Health" },
    { word: "Психология", options: ["Psychology", "Sociology", "Philosophy", "Psychiatry"], correct: "Psychology" },
    { word: "Экология", options: ["Ecology", "Environment", "Nature", "Pollution"], correct: "Ecology" },
    { word: "Глобализация", options: ["Globalization", "Internationalization", "Integration", "Connection"], correct: "Globalization" },
    { word: "Демократия", options: ["Democracy", "Republic", "Autocracy", "Dictatorship"], correct: "Democracy" },
    { word: "Культура", options: ["Culture", "Art", "Tradition", "Civilization"], correct: "Culture" },
    { word: "Религия", options: ["Religion", "Belief", "Faith", "Spirituality"], correct: "Religion" },
    { word: "Семья", options: ["Family", "Parents", "Children", "Relatives"], correct: "Family" },
    { word: "Сообщество", options: ["Community", "Society", "Group", "Club"], correct: "Community" },
    { word: "Мечта", options: ["Dream", "Goal", "Wish", "Hope"], correct: "Dream" },
    { word: "Свобода", options: ["Freedom", "Liberty", "Independence", "Rights"], correct: "Freedom" },
    { word: "Ответственность", options: ["Responsibility", "Obligation", "Duty", "Liability"], correct: "Responsibility" },
    { word: "Надежда", options: ["Hope", "Expectation", "Wish", "Promise"], correct: "Hope" },
    { word: "Мотивация", options: ["Motivation", "Inspiration", "Drive", "Ambition"], correct: "Motivation" },
    { word: "Инновации", options: ["Innovation", "Technology", "Creation", "Invention"], correct: "Innovation" },
    { word: "Влияние", options: ["Influence", "Impact", "Effect", "Pressure"], correct: "Influence" },
    { word: "Прогресс", options: ["Progress", "Growth", "Advancement", "Development"], correct: "Progress" },
    { word: "Стратегия", options: ["Strategy", "Tactic", "Plan", "Method"], correct: "Strategy" },
    { word: "Перспектива", options: ["Perspective", "Outlook", "View", "Point of view"], correct: "Perspective" },
    { word: "Риск", options: ["Risk", "Danger", "Hazard", "Threat"], correct: "Risk" },
    { word: "Конфликт", options: ["Conflict", "Disagreement", "Dispute", "Controversy"], correct: "Conflict" },
    { word: "Проблема", options: ["Problem", "Issue", "Difficulty", "Challenge"], correct: "Problem" },
    { word: "Решение", options: ["Solution", "Answer", "Fix", "Resolution"], correct: "Solution" },
    { word: "Обсуждение", options: ["Discussion", "Debate", "Conversation", "Dialogue"], correct: "Discussion" },
    { word: "Конкуренция", options: ["Competition", "Rivalry", "Race", "Battle"], correct: "Competition" },
    { word: "Сотрудничество", options: ["Cooperation", "Collaboration", "Partnership", "Alliance"], correct: "Cooperation" },
    { word: "Партнерство", options: ["Partnership", "Alliance", "Cooperation", "Collaboration"], correct: "Partnership" },
    { word: "Взаимодействие", options: ["Interaction", "Communication", "Engagement", "Connection"], correct: "Interaction" },
    { word: "Новые технологии", options: ["New technologies", "Emerging technologies", "Advanced technologies", "Future technologies"], correct: "New technologies" },{ word: "Наука", options: ["Science", "Knowledge", "Research", "Discovery"], correct: "Science" },
    { word: "Исследование", options: ["Research", "Investigation", "Study", "Inquiry"], correct: "Research" },
    { word: "Лидер", options: ["Leader", "Chief", "Manager", "Head"], correct: "Leader" },
    { word: "Трудность", options: ["Difficulty", "Obstacle", "Problem", "Challenge"], correct: "Difficulty" },
    { word: "Общество", options: ["Society", "Community", "Population", "Group"], correct: "Society" },
    { word: "Население", options: ["Population", "People", "Citizens", "Inhabitants"], correct: "Population" },
    { word: "Требования", options: ["Requirements", "Expectations", "Demands", "Conditions"], correct: "Requirements" },
    { word: "Потенциал", options: ["Potential", "Capability", "Ability", "Possibility"], correct: "Potential" },
    { word: "Инструмент", options: ["Tool", "Instrument", "Device", "Equipment"], correct: "Tool" },
    { word: "Метод", options: ["Method", "Way", "Procedure", "Technique"], correct: "Method" },
    { word: "Формула", options: ["Formula", "Equation", "Expression", "Rule"], correct: "Formula" },
    { word: "Влияние", options: ["Influence", "Impact", "Effect", "Consequence"], correct: "Influence" },
    { word: "Связь", options: ["Connection", "Relation", "Link", "Bond"], correct: "Connection" },
    { word: "Коммуникация", options: ["Communication", "Interaction", "Discussion", "Dialogue"], correct: "Communication" },
    { word: "Образ", options: ["Image", "Picture", "Shape", "Form"], correct: "Image" },
    { word: "Мнение", options: ["Opinion", "View", "Belief", "Perspective"], correct: "Opinion" },
    { word: "Самосознание", options: ["Self-awareness", "Self-esteem", "Consciousness", "Identity"], correct: "Self-awareness" },
    { word: "Реальность", options: ["Reality", "Truth", "Fact", "Actuality"], correct: "Reality" },
    { word: "Система", options: ["System", "Structure", "Framework", "Network"], correct: "System" },
    { word: "Программа", options: ["Program", "Application", "Course", "Plan"], correct: "Program" },
    { word: "Обучение", options: ["Training", "Education", "Study", "Learning"], correct: "Training" },
    { word: "Призвание", options: ["Calling", "Profession", "Career", "Occupation"], correct: "Calling" },
    { word: "Образование", options: ["Education", "Learning", "Knowledge", "Study"], correct: "Education" },
    { word: "Перспективы", options: ["Prospects", "Opportunities", "Chances", "Aspirations"], correct: "Prospects" },
    { word: "Конструктор", options: ["Constructor", "Builder", "Designer", "Engineer"], correct: "Constructor" },
    { word: "Экспертиза", options: ["Expertise", "Knowledge", "Skill", "Qualification"], correct: "Expertise" },
    { word: "Креативность", options: ["Creativity", "Imagination", "Innovation", "Invention"], correct: "Creativity" },
    { word: "Глобальный", options: ["Global", "Worldwide", "Universal", "International"], correct: "Global" },
    { word: "Ресурсы", options: ["Resources", "Assets", "Materials", "Supplies"], correct: "Resources" },
    { word: "Инвестирование", options: ["Investment", "Financing", "Funding", "Sponsorship"], correct: "Investment" },
    { word: "Цель", options: ["Goal", "Objective", "Target", "Purpose"], correct: "Goal" },
    { word: "Рынок", options: ["Market", "Trade", "Industry", "Sector"], correct: "Market" },
    { word: "Ставка", options: ["Rate", "Bet", "Stake", "Interest"], correct: "Rate" },
    { word: "Доход", options: ["Income", "Profit", "Revenue", "Earnings"], correct: "Income" },
    { word: "Расходы", options: ["Expenses", "Costs", "Spending", "Outgoings"], correct: "Expenses" }
    ],
    C1: [
        { word: "Адаптация", options: ["Adaptation", "Adjustment", "Modification", "Acclimatization"], correct: "Adaptation" },
    { word: "Амбиции", options: ["Ambition", "Aspiration", "Desire", "Goal"], correct: "Ambition" },
    { word: "Баланс", options: ["Balance", "Equilibrium", "Stability", "Symmetry"], correct: "Balance" },
    { word: "Гармония", options: ["Harmony", "Balance", "Unity", "Agreement"], correct: "Harmony" },
    { word: "Диалог", options: ["Dialogue", "Discussion", "Conversation", "Debate"], correct: "Dialogue" },
    { word: "Эксперимент", options: ["Experiment", "Trial", "Test", "Study"], correct: "Experiment" },
    { word: "Инициатива", options: ["Initiative", "Action", "Step", "Proposal"], correct: "Initiative" },
    { word: "Интеграция", options: ["Integration", "Incorporation", "Unification", "Combination"], correct: "Integration" },
    { word: "Когнитивный", options: ["Cognitive", "Intellectual", "Mental", "Perceptual"], correct: "Cognitive" },
    { word: "Логика", options: ["Logic", "Reasoning", "Rationality", "Argument"], correct: "Logic" },
    { word: "Модернизация", options: ["Modernization", "Update", "Improvement", "Reform"], correct: "Modernization" },
    { word: "Наблюдение", options: ["Observation", "Watching", "Surveillance", "Examination"], correct: "Observation" },
    { word: "Образование", options: ["Education", "Learning", "Teaching", "Instruction"], correct: "Education" },
    { word: "Оценка", options: ["Evaluation", "Assessment", "Rating", "Judgment"], correct: "Evaluation" },
    { word: "Преобразование", options: ["Transformation", "Conversion", "Reformation", "Change"], correct: "Transformation" },
    { word: "Реализация", options: ["Realization", "Implementation", "Execution", "Enforcement"], correct: "Realization" },
    { word: "Синтез", options: ["Synthesis", "Combination", "Fusion", "Integration"], correct: "Synthesis" },
    { word: "Стратегия", options: ["Strategy", "Plan", "Approach", "Tactic"], correct: "Strategy" },
    { word: "Технология", options: ["Technology", "Technique", "Methodology", "Innovation"], correct: "Technology" },
    { word: "Устойчивость", options: ["Resilience", "Stability", "Durability", "Strength"], correct: "Resilience" },
    { word: "Феномен", options: ["Phenomenon", "Occurrence", "Event", "Fact"], correct: "Phenomenon" },
    { word: "Цивилизация", options: ["Civilization", "Culture", "Society", "Humanity"], correct: "Civilization" },
    { word: "Этика", options: ["Ethics", "Morality", "Principles", "Values"], correct: "Ethics" },
    { word: "Эксперт", options: ["Expert", "Specialist", "Authority", "Professional"], correct: "Expert" },
    { word: "Мотивация", options: ["Motivation", "Inspiration", "Drive", "Stimulus"], correct: "Motivation" },
    { word: "Невозможно", options: ["Impossible", "Unlikely", "Unfeasible", "Unachievable"], correct: "Impossible" },
    { word: "Открытие", options: ["Discovery", "Revelation", "Finding", "Unveiling"], correct: "Discovery" },
    { word: "Прогноз", options: ["Forecast", "Prediction", "Projection", "Estimate"], correct: "Forecast" },
    { word: "Университет", options: ["University", "College", "Academy", "Institute"], correct: "University" },
    { word: "Функция", options: ["Function", "Role", "Purpose", "Responsibility"], correct: "Function" },
    { word: "Характеристика", options: ["Characteristic", "Feature", "Trait", "Attribute"], correct: "Characteristic" },
    { word: "Цель", options: ["Goal", "Objective", "Target", "Purpose"], correct: "Goal" },
    { word: "Эволюция", options: ["Evolution", "Development", "Progress", "Advancement"], correct: "Evolution" },
    { word: "Юрисдикция", options: ["Jurisdiction", "Authority", "Control", "Power"], correct: "Jurisdiction" },{ word: "Администрирование", options: ["Administration", "Management", "Governance", "Control"], correct: "Administration" },
    { word: "Биография", options: ["Biography", "Autobiography", "Memoir", "Story"], correct: "Biography" },
    { word: "Влияние", options: ["Influence", "Impact", "Effect", "Power"], correct: "Influence" },
    { word: "Дискуссия", options: ["Discussion", "Debate", "Argument", "Conversation"], correct: "Discussion" },
    { word: "Интерпретация", options: ["Interpretation", "Explanation", "Clarification", "Meaning"], correct: "Interpretation" },
    { word: "Культура", options: ["Culture", "Tradition", "Custom", "Heritage"], correct: "Culture" },
    { word: "Литература", options: ["Literature", "Books", "Writing", "Art"], correct: "Literature" },
    { word: "Методология", options: ["Methodology", "Approach", "Technique", "System"], correct: "Methodology" },
    { word: "Наука", options: ["Science", "Knowledge", "Study", "Research"], correct: "Science" },
    { word: "Новая эпоха", options: ["New era", "Age", "Period", "Epoch"], correct: "New era" },
    { word: "Образование", options: ["Education", "Training", "Learning", "Schooling"], correct: "Education" },
    { word: "Опыт", options: ["Experience", "Practice", "Skill", "Knowledge"], correct: "Experience" },
    { word: "Подход", options: ["Approach", "Method", "Way", "Technique"], correct: "Approach" },
    { word: "Репрезентация", options: ["Representation", "Depiction", "Portrayal", "Image"], correct: "Representation" },
    { word: "Секрет", options: ["Secret", "Mystery", "Confidential", "Enigma"], correct: "Secret" },
    { word: "Социальная сеть", options: ["Social network", "Platform", "Site", "Community"], correct: "Social network" },
    { word: "Теория", options: ["Theory", "Concept", "Hypothesis", "Philosophy"], correct: "Theory" },
    { word: "Участник", options: ["Participant", "Member", "Attendee", "Contributor"], correct: "Participant" },
    { word: "Химия", options: ["Chemistry", "Science", "Research", "Physics"], correct: "Chemistry" },
    { word: "Цивилизация", options: ["Civilization", "Culture", "Society", "Community"], correct: "Civilization" },
    { word: "Этика", options: ["Ethics", "Morality", "Philosophy", "Principles"], correct: "Ethics" },
    { word: "Экспертиза", options: ["Expertise", "Skill", "Knowledge", "Competence"], correct: "Expertise" },
    { word: "Юриспруденция", options: ["Jurisprudence", "Law", "Legal studies", "Justice"], correct: "Jurisprudence" },
    { word: "Анализ", options: ["Analysis", "Examination", "Study", "Assessment"], correct: "Analysis" },
    { word: "Инфраструктура", options: ["Infrastructure", "System", "Framework", "Structure"], correct: "Infrastructure" },
    { word: "Координация", options: ["Coordination", "Organization", "Management", "Control"], correct: "Coordination" },
    { word: "Критика", options: ["Criticism", "Review", "Analysis", "Evaluation"], correct: "Criticism" },
    { word: "Наблюдатель", options: ["Observer", "Watcher", "Viewer", "Spectator"], correct: "Observer" },
    { word: "Трансформация", options: ["Transformation", "Change", "Alteration", "Conversion"], correct: "Transformation" },
    { word: "Феномен", options: ["Phenomenon", "Event", "Occurence", "Fact"], correct: "Phenomenon" }
    ],
    C2: [
        { word: "Абстракция", options: ["Abstraction", "Generalization", "Simplification", "Conceptualization"], correct: "Abstraction" },
    { word: "Альтернатива", options: ["Alternative", "Option", "Choice", "Substitute"], correct: "Alternative" },
    { word: "Биомеханика", options: ["Biomechanics", "Biology", "Mechanics", "Physiology"], correct: "Biomechanics" },
    { word: "Дистрибуция", options: ["Distribution", "Dispersal", "Allocation", "Transfer"], correct: "Distribution" },
    { word: "Интервенция", options: ["Intervention", "Action", "Interference", "Involvement"], correct: "Intervention" },
    { word: "Конгруэнтность", options: ["Congruence", "Consistency", "Agreement", "Symmetry"], correct: "Congruence" },
    { word: "Контексты", options: ["Contexts", "Circumstances", "Environments", "Settings"], correct: "Contexts" },
    { word: "Метафора", options: ["Metaphor", "Symbol", "Analogy", "Allegory"], correct: "Metaphor" },
    { word: "Неминуемый", options: ["Inevitable", "Unavoidable", "Certain", "Expected"], correct: "Inevitable" },
    { word: "Оккупация", options: ["Occupation", "Seizure", "Conquest", "Invasion"], correct: "Occupation" },
    { word: "Парадигма", options: ["Paradigm", "Model", "Pattern", "Concept"], correct: "Paradigm" },
    { word: "Преобладание", options: ["Dominance", "Supremacy", "Control", "Authority"], correct: "Dominance" },
    { word: "Ретрансляция", options: ["Relay", "Broadcast", "Transmission", "Rebroadcast"], correct: "Relay" },
    { word: "Синергия", options: ["Synergy", "Collaboration", "Cooperation", "Union"], correct: "Synergy" },
    { word: "Стратификация", options: ["Stratification", "Layering", "Categorization", "Class"], correct: "Stratification" },
    { word: "Трансцендентный", options: ["Transcendent", "Beyond", "Supernatural", "Otherworldly"], correct: "Transcendent" },
    { word: "Феноменология", options: ["Phenomenology", "Study of Experience", "Perception", "Consciousness"], correct: "Phenomenology" },
    { word: "Целостность", options: ["Integrity", "Wholeness", "Unity", "Completeness"], correct: "Integrity" },
    { word: "Эмпиризм", options: ["Empiricism", "Experience", "Observation", "Experimentation"], correct: "Empiricism" },
    { word: "Экспоненциальный", options: ["Exponential", "Rapid", "Explosive", "Increasing"], correct: "Exponential" },
    { word: "Этика", options: ["Ethics", "Morality", "Principles", "Values"], correct: "Ethics" },
    { word: "Эволюция", options: ["Evolution", "Development", "Progress", "Transformation"], correct: "Evolution" },
    { word: "Юриспруденция", options: ["Jurisprudence", "Law", "Legal Studies", "Justice"], correct: "Jurisprudence" },
    { word: "Актуализация", options: ["Actualization", "Implementation", "Realization", "Activation"], correct: "Actualization" },
    { word: "Интерсубъективность", options: ["Intersubjectivity", "Shared Understanding", "Mutuality", "Perspective"], correct: "Intersubjectivity" },
    { word: "Метамодернизм", options: ["Metamodernism", "Postmodernism", "Cultural Movement", "Philosophy"], correct: "Metamodernism" },
    { word: "Некомпетентность", options: ["Incompetence", "Inability", "Inexpertise", "Lack of Skill"], correct: "Incompetence" },
    { word: "Парадокс", options: ["Paradox", "Contradiction", "Anomaly", "Incongruity"], correct: "Paradox" },
    { word: "Когнитивный", options: ["Cognitive", "Mental", "Psychological", "Intellectual"], correct: "Cognitive" },{ word: "Парадигма", options: ["Paradigm", "Model", "Pattern", "Framework"], correct: "Paradigm" },
    { word: "Невозможность", options: ["Impossibility", "Infeasibility", "Unattainability", "Unlikeliness"], correct: "Impossibility" },
    { word: "Метамодернизм", options: ["Metamodernism", "Postmodernism", "Cultural Shift", "Philosophical Movement"], correct: "Metamodernism" },
    { word: "Феноменология", options: ["Phenomenology", "Consciousness Study", "Perception", "Existentialism"], correct: "Phenomenology" },
    { word: "Синергия", options: ["Synergy", "Cooperation", "Collaboration", "Unity"], correct: "Synergy" },
    { word: "Трансцендентность", options: ["Transcendence", "Supernatural", "Beyond", "Existence"], correct: "Transcendence" },
    { word: "Эмпиризм", options: ["Empiricism", "Experience-Based Knowledge", "Pragmatism", "Observation"], correct: "Empiricism" },
    { word: "Дистрибуция", options: ["Distribution", "Allocation", "Dispersion", "Delivery"], correct: "Distribution" },
    { word: "Интервенция", options: ["Intervention", "Action", "Involvement", "Interference"], correct: "Intervention" },
    { word: "Абстракция", options: ["Abstraction", "Simplification", "Conceptualization", "Generalization"], correct: "Abstraction" },
    { word: "Контекст", options: ["Context", "Situation", "Circumstances", "Environment"], correct: "Context" },
    { word: "Когнитивный", options: ["Cognitive", "Intellectual", "Mental", "Psychological"], correct: "Cognitive" },
    { word: "Онтология", options: ["Ontology", "Philosophy of Being", "Existentialism", "Metaphysics"], correct: "Ontology" },
    { word: "Абстракционизм", options: ["Abstractism", "Artistic Movement", "Philosophy", "Conceptualism"], correct: "Abstractism" },
    { word: "Метафизика", options: ["Metaphysics", "Philosophy of Reality", "Beyond the Physical", "Existential Studies"], correct: "Metaphysics" },
    { word: "Нейропластичность", options: ["Neuroplasticity", "Brain Adaptability", "Cognitive Flexibility", "Neural Growth"], correct: "Neuroplasticity" },
    { word: "Деконструкция", options: ["Deconstruction", "Analysis", "Disassembly", "Reinterpretation"], correct: "Deconstruction" },
    { word: "Антропоцентризм", options: ["Anthropocentrism", "Human-Centered Philosophy", "Humanism", "Philosophical View"], correct: "Anthropocentrism" },
    { word: "Прагматизм", options: ["Pragmatism", "Practicality", "Realism", "Utilitarianism"], correct: "Pragmatism" },
    { word: "Катарсис", options: ["Catharsis", "Emotional Release", "Cleansing", "Purification"], correct: "Catharsis" },
    { word: "Редукционизм", options: ["Reductionism", "Simplification", "Breaking Down", "Componentalism"], correct: "Reductionism" },
    { word: "Герменевтика", options: ["Hermeneutics", "Interpretation Theory", "Exegesis", "Textual Analysis"], correct: "Hermeneutics" },
    { word: "Постмодернизм", options: ["Postmodernism", "Cultural Movement", "Artistic Revolution", "Intellectual Movement"], correct: "Postmodernism" },
    { word: "Квазипериодичность", options: ["Quasiperiodicity", "Almost Periodic", "Irregular Regularity", "Non-repetitive Pattern"], correct: "Quasiperiodicity" },
    { word: "Семантика", options: ["Semantics", "Meaning Theory", "Study of Meaning", "Language Structure"], correct: "Semantics" },
    { word: "Аксиология", options: ["Axiology", "Value Theory", "Ethics", "Philosophy of Values"], correct: "Axiology" },
    { word: "Экзистенциализм", options: ["Existentialism", "Philosophy of Existence", "Individualism", "Freedom"], correct: "Existentialism" },
    { word: "Суперпозиция", options: ["Superposition", "Overlap", "Combination", "Layering"], correct: "Superposition" },
    { word: "Трансцендентальный", options: ["Transcendental", "Beyond Experience", "Philosophical", "Otherworldly"], correct: "Transcendental" },
    { word: "Гедонизм", options: ["Hedonism", "Pleasure Philosophy", "Pursuit of Happiness", "Life Philosophy"], correct: "Hedonism" },
    { word: "Иррациональность", options: ["Irrationality", "Illogicality", "Absurdity", "Non-reason"], correct: "Irrationality" },
    { word: "Абсолютный", options: ["Absolute", "Unconditional", "Complete", "Unrestricted"], correct: "Absolute" },
    { word: "Параллакс", options: ["Parallax", "Apparent Shift", "Optical Illusion", "Perspective"], correct: "Parallax" }
    ]
};

const russianWordList = [
    { "word": "собака", "meaning": "Dog", "plural": "собаки", "indefinite": "NA", "definite": "NA" },
{ "word": "книга", "meaning": "Book", "plural": "книги", "indefinite": "NA", "definite": "NA" },
{ "word": "море", "meaning": "Sea", "plural": "моря", "indefinite": "NA", "definite": "NA" },
{ "word": "машина", "meaning": "Car", "plural": "машины", "indefinite": "NA", "definite": "NA" },
{ "word": "дом", "meaning": "House", "plural": "дома", "indefinite": "NA", "definite": "NA" },
{ "word": "стул", "meaning": "Chair", "plural": "стулья", "indefinite": "NA", "definite": "NA" },
{ "word": "стол", "meaning": "Table", "plural": "столы", "indefinite": "NA", "definite": "NA" },
{ "word": "лампа", "meaning": "Lamp", "plural": "лампы", "indefinite": "NA", "definite": "NA" },
{ "word": "яблоко", "meaning": "Apple", "plural": "яблоки", "indefinite": "NA", "definite": "NA" },
{ "word": "цветок", "meaning": "Flower", "plural": "цветы", "indefinite": "NA", "definite": "NA" },
{ "word": "дерево", "meaning": "Tree", "plural": "деревья", "indefinite": "NA", "definite": "NA" },
{ "word": "чемодан", "meaning": "Suitcase", "plural": "чемоданы", "indefinite": "NA", "definite": "NA" },
{ "word": "ботинок", "meaning": "Shoe", "plural": "ботинки", "indefinite": "NA", "definite": "NA" },
{ "word": "куртка", "meaning": "Jacket", "plural": "куртки", "indefinite": "NA", "definite": "NA" },
{ "word": "окно", "meaning": "Window", "plural": "окна", "indefinite": "NA", "definite": "NA" },
{ "word": "карандаш", "meaning": "Pencil", "plural": "карандаши", "indefinite": "NA", "definite": "NA" },
{ "word": "тетрадь", "meaning": "Notebook", "plural": "тетради", "indefinite": "NA", "definite": "NA" },
{ "word": "очки", "meaning": "Glasses", "plural": "очки", "indefinite": "NA", "definite": "NA" },
{ "word": "поезд", "meaning": "Train", "plural": "поезда", "indefinite": "NA", "definite": "NA" },
{ "word": "кухня", "meaning": "Kitchen", "plural": "кухни", "indefinite": "NA", "definite": "NA" },
{ "word": "велосипед", "meaning": "Bicycle", "plural": "велосипеды", "indefinite": "NA", "definite": "NA" },
{ "word": "сумка", "meaning": "Bag", "plural": "сумки", "indefinite": "NA", "definite": "NA" },
{ "word": "часы", "meaning": "Clock", "plural": "часы", "indefinite": "NA", "definite": "NA" },
{ "word": "хлеб", "meaning": "Bread", "plural": "хлеба", "indefinite": "NA", "definite": "NA" },
{ "word": "вода", "meaning": "Water", "plural": "воды", "indefinite": "NA", "definite": "NA" },
{ "word": "нож", "meaning": "Knife", "plural": "ножи", "indefinite": "NA", "definite": "NA" },
{ "word": "вилка", "meaning": "Fork", "plural": "вилки", "indefinite": "NA", "definite": "NA" },
{ "word": "ложка", "meaning": "Spoon", "plural": "ложки", "indefinite": "NA", "definite": "NA" },
{ "word": "город", "meaning": "City", "plural": "города", "indefinite": "NA", "definite": "NA" },
{ "word": "деревня", "meaning": "Village", "plural": "деревни", "indefinite": "NA", "definite": "NA" },
{ "word": "школа", "meaning": "School", "plural": "школы", "indefinite": "NA", "definite": "NA" },
{ "word": "самолёт", "meaning": "Airplane", "plural": "самолёты", "indefinite": "NA", "definite": "NA" },
{ "word": "телефон", "meaning": "Phone", "plural": "телефоны", "indefinite": "NA", "definite": "NA" },
{ "word": "компьютер", "meaning": "Computer", "plural": "компьютеры", "indefinite": "NA", "definite": "NA" },
{ "word": "ребёнок", "meaning": "Child", "plural": "дети", "indefinite": "NA", "definite": "NA" },
{ "word": "учитель", "meaning": "Teacher (Male)", "plural": "учителя", "indefinite": "NA", "definite": "NA" },
{ "word": "учительница", "meaning": "Teacher (Female)", "plural": "учительницы", "indefinite": "NA", "definite": "NA" },
{ "word": "друг", "meaning": "Friend (Male)", "plural": "друзья", "indefinite": "NA", "definite": "NA" },
{ "word": "подруга", "meaning": "Friend (Female)", "plural": "подруги", "indefinite": "NA", "definite": "NA" },
{ "word": "семья", "meaning": "Family", "plural": "семьи", "indefinite": "NA", "definite": "NA" },
{ "word": "солнце", "meaning": "Sun", "plural": "солнца", "indefinite": "NA", "definite": "NA" },
{ "word": "река", "meaning": "River", "plural": "реки", "indefinite": "NA", "definite": "NA" },
{ "word": "кресло", "meaning": "Armchair", "plural": "кресла", "indefinite": "NA", "definite": "NA" },
{ "word": "молоко", "meaning": "Milk", "plural": "молока", "indefinite": "NA", "definite": "NA" },
{ "word": "птица", "meaning": "Bird", "plural": "птицы", "indefinite": "NA", "definite": "NA" },
{ "word": "дождь", "meaning": "Rain", "plural": "дожди", "indefinite": "NA", "definite": "NA" },
{ "word": "площадь", "meaning": "Square (in a city)", "plural": "площади", "indefinite": "NA", "definite": "NA" },
{ "word": "комната", "meaning": "Room", "plural": "комнаты", "indefinite": "NA", "definite": "NA" },
{ "word": "телевизор", "meaning": "Television", "plural": "телевизоры", "indefinite": "NA", "definite": "NA" },
{ "word": "письмо", "meaning": "Letter (correspondence)", "plural": "письма", "indefinite": "NA", "definite": "NA" },
{ "word": "апельсин", "meaning": "Orange (fruit)", "plural": "апельсины", "indefinite": "NA", "definite": "NA" },
{ "word": "картинка", "meaning": "Picture", "plural": "картинки", "indefinite": "NA", "definite": "NA" },
{ "word": "вино", "meaning": "Wine", "plural": "вина", "indefinite": "NA", "definite": "NA" },
{ "word": "техника", "meaning": "Technology", "plural": "техники", "indefinite": "NA", "definite": "NA" },
{ "word": "письменность", "meaning": "Writing", "plural": "письменности", "indefinite": "NA", "definite": "NA" },
{ "word": "весна", "meaning": "Spring", "plural": "весны", "indefinite": "NA", "definite": "NA" },
{ "word": "лето", "meaning": "Summer", "plural": "лета", "indefinite": "NA", "definite": "NA" },
{ "word": "осень", "meaning": "Autumn", "plural": "осени", "indefinite": "NA", "definite": "NA" },
{ "word": "зима", "meaning": "Winter", "plural": "зимы", "indefinite": "NA", "definite": "NA" },
{ "word": "метро", "meaning": "Metro", "plural": "метро", "indefinite": "NA", "definite": "NA" },
  { "word": "парк", "meaning": "Park", "plural": "парки", "indefinite": "NA", "definite": "NA" },
  { "word": "мост", "meaning": "Bridge", "plural": "мосты", "indefinite": "NA", "definite": "NA" },
  { "word": "гора", "meaning": "Mountain", "plural": "горы", "indefinite": "NA", "definite": "NA" },
  { "word": "песок", "meaning": "Sand", "plural": "пески", "indefinite": "NA", "definite": "NA" },
  { "word": "трава", "meaning": "Grass", "plural": "травы", "indefinite": "NA", "definite": "NA" },
  { "word": "здание", "meaning": "Building", "plural": "здания", "indefinite": "NA", "definite": "NA" },
  { "word": "дорога", "meaning": "Road", "plural": "дороги", "indefinite": "NA", "definite": "NA" },
  { "word": "облако", "meaning": "Cloud", "plural": "облака", "indefinite": "NA", "definite": "NA" },
  { "word": "книга", "meaning": "Library", "plural": "книги", "indefinite": "NA", "definite": "NA" },
  { "word": "площадка", "meaning": "Playground", "plural": "площадки", "indefinite": "NA", "definite": "NA" },
  { "word": "больница", "meaning": "Hospital", "plural": "больницы", "indefinite": "NA", "definite": "NA" },
  { "word": "собрание", "meaning": "Meeting", "plural": "собрания", "indefinite": "NA", "definite": "NA" },
  { "word": "озеро", "meaning": "Lake", "plural": "озёра", "indefinite": "NA", "definite": "NA" },
  { "word": "птица", "meaning": "Duck", "plural": "птицы", "indefinite": "NA", "definite": "NA" },
  { "word": "магазин", "meaning": "Store", "plural": "магазины", "indefinite": "NA", "definite": "NA" },
  { "word": "памятник", "meaning": "Monument", "plural": "памятники", "indefinite": "NA", "definite": "NA" },
  { "word": "ферма", "meaning": "Farm", "plural": "фермы", "indefinite": "NA", "definite": "NA" },
  { "word": "торговец", "meaning": "Merchant", "plural": "торговцы", "indefinite": "NA", "definite": "NA" },
  { "word": "рыба", "meaning": "Fish", "plural": "рыбы", "indefinite": "NA", "definite": "NA" },
  { "word": "лодка", "meaning": "Boat", "plural": "лодки", "indefinite": "NA", "definite": "NA" },
  { "word": "солнце", "meaning": "Moon", "plural": "солнца", "indefinite": "NA", "definite": "NA" },
  { "word": "тепло", "meaning": "Heat", "plural": "тепла", "indefinite": "NA", "definite": "NA" },
  { "word": "звезда", "meaning": "Star", "plural": "звёзды", "indefinite": "NA", "definite": "NA" },
  { "word": "лес", "meaning": "Forest", "plural": "леса", "indefinite": "NA", "definite": "NA" },
  { "word": "куст", "meaning": "Bush", "plural": "кусты", "indefinite": "NA", "definite": "NA" },
  { "word": "трактор", "meaning": "Tractor", "plural": "тракторы", "indefinite": "NA", "definite": "NA" },
  { "word": "поле", "meaning": "Field", "plural": "поля", "indefinite": "NA", "definite": "NA" },
  { "word": "фермер", "meaning": "Farmer", "plural": "фермеры", "indefinite": "NA", "definite": "NA" },
  { "word": "чай", "meaning": "Tea", "plural": "чаи", "indefinite": "NA", "definite": "NA" },
  { "word": "собственность", "meaning": "Property", "plural": "собственности", "indefinite": "NA", "definite": "NA" },
  { "word": "стена", "meaning": "Wall", "plural": "стены", "indefinite": "NA", "definite": "NA" },
  { "word": "доска", "meaning": "Board", "plural": "доски", "indefinite": "NA", "definite": "NA" },
  { "word": "карта", "meaning": "Map", "plural": "карты", "indefinite": "NA", "definite": "NA" },
  { "word": "ручка", "meaning": "Pen", "plural": "ручки", "indefinite": "NA", "definite": "NA" },
  { "word": "записка", "meaning": "Note", "plural": "записки", "indefinite": "NA", "definite": "NA" },
  { "word": "мыло", "meaning": "Soap", "plural": "мыла", "indefinite": "NA", "definite": "NA" },
  { "word": "чемпион", "meaning": "Champion", "plural": "чемпионы", "indefinite": "NA", "definite": "NA" },
  { "word": "праздник", "meaning": "Holiday", "plural": "праздники", "indefinite": "NA", "definite": "NA" },
  { "word": "улица", "meaning": "Street", "plural": "улицы", "indefinite": "NA", "definite": "NA" },
  { "word": "перекрёсток", "meaning": "Crossroad", "plural": "перекрёстки", "indefinite": "NA", "definite": "NA" },
  { "word": "свет", "meaning": "Light", "plural": "света", "indefinite": "NA", "definite": "NA" },
  { "word": "ключ", "meaning": "Key", "plural": "ключи", "indefinite": "NA", "definite": "NA" },
  { "word": "восток", "meaning": "East", "plural": "востоки", "indefinite": "NA", "definite": "NA" },
  { "word": "запад", "meaning": "West", "plural": "запады", "indefinite": "NA", "definite": "NA" },
  { "word": "север", "meaning": "North", "plural": "севера", "indefinite": "NA", "definite": "NA" },
  { "word": "юг", "meaning": "South", "plural": "юги", "indefinite": "NA", "definite": "NA" },
  { "word": "остров", "meaning": "Island", "plural": "острова", "indefinite": "NA", "definite": "NA" },
  { "word": "берег", "meaning": "Coast", "plural": "берега", "indefinite": "NA", "definite": "NA" },
  { "word": "скала", "meaning": "Rock", "plural": "скалы", "indefinite": "NA", "definite": "NA" },
  { "word": "залив", "meaning": "Bay", "plural": "заливы", "indefinite": "NA", "definite": "NA" },
  { "word": "животное", "meaning": "Animal", "plural": "животные", "indefinite": "NA", "definite": "NA" },
  { "word": "пещера", "meaning": "Cave", "plural": "пещеры", "indefinite": "NA", "definite": "NA" },
  { "word": "огонь", "meaning": "Fire", "plural": "огни", "indefinite": "NA", "definite": "NA" },
  { "word": "гора", "meaning": "Mountain", "plural": "горы", "indefinite": "NA", "definite": "NA" },
  { "word": "парк", "meaning": "Park", "plural": "парки", "indefinite": "NA", "definite": "NA" },
  { "word": "здание", "meaning": "Building", "plural": "здания", "indefinite": "NA", "definite": "NA" },
  { "word": "магазин", "meaning": "Store", "plural": "магазины", "indefinite": "NA", "definite": "NA" },
  { "word": "кафе", "meaning": "Cafe", "plural": "кафе", "indefinite": "NA", "definite": "NA" },
  { "word": "мост", "meaning": "Bridge", "plural": "мосты", "indefinite": "NA", "definite": "NA" },
  { "word": "рынок", "meaning": "Market", "plural": "рынки", "indefinite": "NA", "definite": "NA" },
  { "word": "площадка", "meaning": "Playground", "plural": "площадки", "indefinite": "NA", "definite": "NA" },
  { "word": "дорога", "meaning": "Road", "plural": "дороги", "indefinite": "NA", "definite": "NA" },
  { "word": "грузовик", "meaning": "Truck", "plural": "грузовики", "indefinite": "NA", "definite": "NA" },
  { "word": "трава", "meaning": "Grass", "plural": "травы", "indefinite": "NA", "definite": "NA" },
  { "word": "снег", "meaning": "Snow", "plural": "снега", "indefinite": "NA", "definite": "NA" },
  { "word": "лед", "meaning": "Ice", "plural": "лёд", "indefinite": "NA", "definite": "NA" },
  { "word": "звезда", "meaning": "Star", "plural": "звёзды", "indefinite": "NA", "definite": "NA" },
  { "word": "песок", "meaning": "Sand", "plural": "пески", "indefinite": "NA", "definite": "NA" },
  { "word": "камень", "meaning": "Stone", "plural": "камни", "indefinite": "NA", "definite": "NA" },
  { "word": "волна", "meaning": "Wave", "plural": "волны", "indefinite": "NA", "definite": "NA" },
  { "word": "жук", "meaning": "Beetle", "plural": "жуки", "indefinite": "NA", "definite": "NA" },
  { "word": "паук", "meaning": "Spider", "plural": "пауки", "indefinite": "NA", "definite": "NA" },
  { "word": "рыба", "meaning": "Fish", "plural": "рыбы", "indefinite": "NA", "definite": "NA" },
  { "word": "озеро", "meaning": "Lake", "plural": "озёра", "indefinite": "NA", "definite": "NA" },
  { "word": "луна", "meaning": "Moon", "plural": "луны", "indefinite": "NA", "definite": "NA" },
  { "word": "галактика", "meaning": "Galaxy", "plural": "галактики", "indefinite": "NA", "definite": "NA" },
  { "word": "космос", "meaning": "Space", "plural": "NA", "indefinite": "NA", "definite": "NA" },
  { "word": "планета", "meaning": "Planet", "plural": "планеты", "indefinite": "NA", "definite": "NA" },
  { "word": "звук", "meaning": "Sound", "plural": "звуки", "indefinite": "NA", "definite": "NA" },
  { "word": "вопрос", "meaning": "Question", "plural": "вопросы", "indefinite": "NA", "definite": "NA" },
  { "word": "ответ", "meaning": "Answer", "plural": "ответы", "indefinite": "NA", "definite": "NA" },
  { "word": "время", "meaning": "Time", "plural": "времена", "indefinite": "NA", "definite": "NA" },
  { "word": "история", "meaning": "History", "plural": "истории", "indefinite": "NA", "definite": "NA" }
]

module.exports = { russianQuizData, russianWordList };